<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Revised Form – Comparative analysis of the MINSA Health Map and the Harmonized Health Facility Assessment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./anexo-1.html" rel="next">
<link href="./05-decisoes.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-4d091dc1b1f655aa3f6f43fc4cc4ca42.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-d75d73574caadaa5e63e9cb958cfa0ff.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-4d091dc1b1f655aa3f6f43fc4cc4ca42.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&amp;family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400&amp;family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,400&amp;display=swap" rel="stylesheet">
<script>
  // Apply the reader's saved typeface and size before the page paints.
  (function () {
    try {
      var d = document.documentElement;
      var f = localStorage.getItem("reader-font");
      var s = localStorage.getItem("reader-fontsize");
      if (f && f !== "sans") d.setAttribute("data-font", f);
      if (s && s !== "0") d.setAttribute("data-fontsize", s);
    } catch (e) {}
  })();
</script>


</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-ficha-revista.html">Revised Form</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Comparative analysis of the MINSA Health Map and the Harmonized Health Facility Assessment</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/filustrias/mapa_sanitario_hhfa/tree/main/en/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Opening</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-panoramica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-formulacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">A note on the design and presentation of questions and response options</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-cobertura.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">What each instrument captures about the reality of health facilities</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-incrementos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">How we can enhance the Health Map Form using the HHFA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-decisoes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Decisions we will need to take to move forward together</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ficha-revista.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Revised Form</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Annex 1 — Proposed questionnaire</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#read-first-the-drafting-standard-adopted" id="toc-read-first-the-drafting-standard-adopted" class="nav-link active" data-scroll-target="#read-first-the-drafting-standard-adopted">⚠ READ FIRST: the drafting standard adopted</a></li>
  <li><a href="#section-0-identification-of-the-data-collection" id="toc-section-0-identification-of-the-data-collection" class="nav-link" data-scroll-target="#section-0-identification-of-the-data-collection">SECTION 0 — Identification of the data collection</a></li>
  <li><a href="#section-1-location" id="toc-section-1-location" class="nav-link" data-scroll-target="#section-1-location">SECTION 1 — Location</a></li>
  <li><a href="#section-2-ownership-and-management" id="toc-section-2-ownership-and-management" class="nav-link" data-scroll-target="#section-2-ownership-and-management">SECTION 2 — Ownership and management</a></li>
  <li><a href="#section-3-catchment-population-and-referral-system" id="toc-section-3-catchment-population-and-referral-system" class="nav-link" data-scroll-target="#section-3-catchment-population-and-referral-system">SECTION 3 — Catchment population and referral system</a>
  <ul class="collapse">
  <li><a href="#catchment-population" id="toc-catchment-population" class="nav-link" data-scroll-target="#catchment-population">3.1 Catchment population</a></li>
  <li><a href="#referral-facility" id="toc-referral-facility" class="nav-link" data-scroll-target="#referral-facility">3.2 Referral facility</a></li>
  <li><a href="#functioning-of-the-referral-system" id="toc-functioning-of-the-referral-system" class="nav-link" data-scroll-target="#functioning-of-the-referral-system">3.3 Functioning of the referral system</a></li>
  </ul></li>
  <li><a href="#section-4-buildings-and-construction" id="toc-section-4-buildings-and-construction" class="nav-link" data-scroll-target="#section-4-buildings-and-construction">SECTION 4 — Buildings and construction</a></li>
  <li><a href="#section-5-state-of-repair" id="toc-section-5-state-of-repair" class="nav-link" data-scroll-target="#section-5-state-of-repair">SECTION 5 — State of repair</a></li>
  <li><a href="#section-6-water-energy-sanitation-and-waste" id="toc-section-6-water-energy-sanitation-and-waste" class="nav-link" data-scroll-target="#section-6-water-energy-sanitation-and-waste">SECTION 6 — Water, energy, sanitation and waste</a>
  <ul class="collapse">
  <li><a href="#water" id="toc-water" class="nav-link" data-scroll-target="#water">6.1 Water</a></li>
  <li><a href="#energy" id="toc-energy" class="nav-link" data-scroll-target="#energy">6.2 Energy</a></li>
  <li><a href="#sanitation" id="toc-sanitation" class="nav-link" data-scroll-target="#sanitation">6.3 Sanitation</a></li>
  <li><a href="#waste" id="toc-waste" class="nav-link" data-scroll-target="#waste">6.4 Waste</a></li>
  </ul></li>
  <li><a href="#section-7-services" id="toc-section-7-services" class="nav-link" data-scroll-target="#section-7-services">SECTION 7 — Services</a>
  <ul class="collapse">
  <li><a href="#gateway-questions" id="toc-gateway-questions" class="nav-link" data-scroll-target="#gateway-questions">7.0 Gateway questions</a></li>
  <li><a href="#clinical-and-surgical-services" id="toc-clinical-and-surgical-services" class="nav-link" data-scroll-target="#clinical-and-surgical-services">7.1 Clinical and surgical services</a></li>
  <li><a href="#support-services-technologies-procedures-and-tests" id="toc-support-services-technologies-procedures-and-tests" class="nav-link" data-scroll-target="#support-services-technologies-procedures-and-tests">7.2 Support services — technologies, procedures and tests</a></li>
  <li><a href="#public-health-prevention-and-programmes" id="toc-public-health-prevention-and-programmes" class="nav-link" data-scroll-target="#public-health-prevention-and-programmes">7.3 Public health, prevention and programmes</a></li>
  <li><a href="#and-7.5-management-services-and-general-services" id="toc-and-7.5-management-services-and-general-services" class="nav-link" data-scroll-target="#and-7.5-management-services-and-general-services">7.4 and 7.5 Management services and general services</a></li>
  </ul></li>
  <li><a href="#section-8-beds" id="toc-section-8-beds" class="nav-link" data-scroll-target="#section-8-beds">SECTION 8 — Beds</a></li>
  <li><a href="#section-9-equipment" id="toc-section-9-equipment" class="nav-link" data-scroll-target="#section-9-equipment">SECTION 9 — Equipment</a></li>
  <li><a href="#section-10-means-of-transport" id="toc-section-10-means-of-transport" class="nav-link" data-scroll-target="#section-10-means-of-transport">SECTION 10 — Means of transport</a></li>
  <li><a href="#section-11-staff-assigned-to-the-facility" id="toc-section-11-staff-assigned-to-the-facility" class="nav-link" data-scroll-target="#section-11-staff-assigned-to-the-facility">SECTION 11 — Staff assigned to the facility</a>
  <ul class="collapse">
  <li><a href="#new-section" id="toc-new-section" class="nav-link" data-scroll-target="#new-section"><em>New section</em></a></li>
  </ul></li>
  <li><a href="#hhfa-indicators-captured-by-this-version" id="toc-hhfa-indicators-captured-by-this-version" class="nav-link" data-scroll-target="#hhfa-indicators-captured-by-this-version">HHFA indicators captured by this version</a></li>
  <li><a href="#what-this-version-delivers-and-what-it-leaves-for-later" id="toc-what-this-version-delivers-and-what-it-leaves-for-later" class="nav-link" data-scroll-target="#what-this-version-delivers-and-what-it-leaves-for-later">What this version delivers, and what it leaves for later</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/filustrias/mapa_sanitario_hhfa/blob/main/en/06-ficha-revista.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/filustrias/mapa_sanitario_hhfa/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Revised Form</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div style="border-left:6px solid #0b6e99;background:#eaf4f9;padding:14px 18px;border-radius:6px;">
<p class="chapter-lead">Health Facility Registration Form<br>Proposed revised version, with questions written out in full and HHFA indicators annotated</p>
<p>Working version for discussion with the Office of Studies, Planning and Statistics. It keeps the structure, the numbering and the purpose of Form version 19_01, and reformulates the questions and the response options following the wording of the Harmonized Health Facility Assessment, translated from the original.</p>
<p><strong>Every question is written out in full, exactly as it is to be read aloud</strong>, with the unit of measure, the reference period and the point of reference built into the text itself. <strong>Each one is annotated with the HHFA indicator that it makes computable.</strong></p>
</div>
<section id="read-first-the-drafting-standard-adopted" class="level3" style="border:3px solid #c0392b;background:#fdecea;padding:18px 20px;border-radius:8px;margin:18px 0;">
<h3 class="anchored" data-anchor-id="read-first-the-drafting-standard-adopted">⚠ READ FIRST: the drafting standard adopted</h3>
<p style="font-size:1.08em;line-height:1.55;margin:0 0 10px 0;"><strong style="color:#c0392b;">A question that each enumerator has to complete on their own is a different question in every health facility.</strong> "Distance to the referral facility — minutes, total km" forces the person collecting the data to decide alone which road, by which means of transport, in which season of the year, and measured how. The answers that come out of it are not comparable with one another, and no subsequent analysis can recover that variation.</p>
<p style="font-size:1.04em;line-height:1.5;margin:0 0 10px 0;">This version applies nine drafting rules to every question. They are the same ones the HHFA applies, and the effect is that the question stays identical across all facilities, whoever asks it.</p>
<ol style="font-size:1.0em;line-height:1.5;margin:0 0 12px 0;">
<li><strong>The question is read out in full, exactly as written.</strong> The enumerator neither completes nor summarises it.</li>
<li><strong>The unit of measure is inside the question</strong> — kilometres, minutes, number of people, square metres.</li>
<li><strong>The reference period is inside the question</strong> — today, in the past 7 days, in the past 3 months, in the past 12 months, in the past 2 years.</li>
<li><strong>The point of reference is inside the question</strong> — from where to where, counted how, by whom, under what conditions.</li>
<li><strong>One question yields one fact.</strong> Composite concepts are split into separate questions.</li>
<li><strong>The response options are mutually exclusive and exhaustive</strong>, and they are written on the form, not left to the judgement of whoever is recording the answer.</li>
<li><strong>There is always a code for "does not know"</strong> (98) and, where applicable, for "not applicable" (97). A blank field is no longer ambiguous.</li>
<li><strong>Instructions to the enumerator are set apart graphically</strong> from the text to be read to the respondent. In this document they appear in <em>italics and in capitals</em>.</li>
<li><strong>Consistency checks are stated</strong> alongside the questions they apply to, so that they can be programmed into the data collection application.</li>
</ol>
<hr style="border:none;border-top:2px dashed #c0392b;margin:14px 0;">
<p style="font-size:1.03em;line-height:1.5;margin:0 0 8px 0;"><strong style="color:#c0392b;">The HHFA foresees instruments exactly like the Health Map.</strong> The inventory has two subareas — <strong>1.3.2, availability of specific services</strong>, and <strong>1.3.3, availability of technologies and procedures</strong> — whose titles end with the note <em>"to be used only when the readiness module does not apply"</em>. This proposal rests on that route, and the consequence is highly favourable: <strong>more than nine in ten of the indicators captured here yield in self-reported mode</strong>, requiring neither observation nor any change to the current collection process.</p>
<p style="font-size:1.0em;line-height:1.45;margin:0;"><strong>Conventions.</strong> The numbering of existing items is retained, so that the historical series can be reconstructed. <strong>[MS]</strong> marks items specific to the Health Map, with no counterpart in the HHFA, which are kept because they are its own particular contribution — but <strong>they too are reformulated</strong>, because the drafting problem is independent of where the question came from. <strong>◆</strong> marks the questions that require an enumerator making observations. The lists so flagged still need validation by the national programmes.</p>
</section>
<hr>
<section id="section-0-identification-of-the-data-collection" class="level2">
<h2 class="anchored" data-anchor-id="section-0-identification-of-the-data-collection">SECTION 0 — Identification of the data collection</h2>
<p><strong>0.1</strong> Date on which this form was completed: |__|__| day · |__|__| month · |__|__|__|__| year</p>
<p><strong>0.2</strong> <strong>How was this form completed?</strong><br>
<em>READ THE OPTIONS.</em></p>
<blockquote class="blockquote">
<p>1 Completed by the facility staff and sent to GEPE, with no enumerator visit<br>
2 Completed by an enumerator during a visit to the facility<br>
3 Completed by the facility staff and then checked by an enumerator during a visit</p>
</blockquote>
<p><em>Indicator: essential metadata. Without it, the analysis cannot separate what was verified from what was merely declared.</em></p>
<p><strong>0.3</strong> <strong>What is the position of the person who answered most of this form?</strong></p>
<blockquote class="blockquote">
<p>1 Facility director · 2 Deputy director · 3 Head of nursing · 4 Head of administration · 5 Head of statistics · 6 Other position (specify) ______</p>
</blockquote>
<p><strong>0.4</strong> <strong>Does this facility have a budget of its own — that is, an allocation of funds assigned specifically to this facility, which its management can administer and execute?</strong><br>
<em>DO NOT COUNT FUNDS MANAGED ENTIRELY BY THE MUNICIPAL OR PROVINCIAL DIRECTORATE ON THE FACILITY’S BEHALF.</em></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No · 98 Does not know</p>
</blockquote>
<p><em>HHFA indicator: <strong>4.2.1.1.1</strong> (anchor — see note).</em></p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>Note on 0.4.</strong> In the current Form, item 0.2 says only “Tick if the facility has its OWN BUDGET”, without defining what counts as such. A director who receives a municipal allocation earmarked for their facility and a director who runs a bank account of their own both answer “yes”, and these are administratively very different situations. The wording above fixes the criterion — <strong>the power to administer and execute</strong> — and explicitly excludes the ambiguous case. HHFA indicator 4.2.1.1.1 is more demanding still (autonomy to manage a bank account of one’s own); it is proposed that the public financial management group decide which of the two criteria serves Angola better, and that it be fixed in the question.</p>
</div>
<hr>
</section>
<section id="section-1-location" class="level2">
<h2 class="anchored" data-anchor-id="section-1-location">SECTION 1 — Location</h2>
<p><strong>1.1 to 1.5</strong> Province · Municipality · Commune or urban district · Rural village or urban neighbourhood · Name of the health facility<br>
<em>RECORD THE NAME AND THE CODE GIVEN BY THE HEALTH MAP.</em></p>
<p><strong>1.6</strong> Category of the facility, according to the Health Map classification<br>
<em>THE PRINCIPAL STRATIFIER FOR ALL ANALYSIS. It is the national list of facility types that replaces the generic HHFA list.</em></p>
<p><strong>1.7 and 1.8</strong> <strong>Reading of the geographic coordinates.</strong><br>
<em>TAKE THE READING AT THE MAIN ENTRANCE OF THE MAIN BUILDING, IN THE OPEN AIR, WITH THE DEVICE HELD STEADY FOR AT LEAST 60 SECONDS. RECORD IN DECIMAL DEGREES, TO FIVE DECIMAL PLACES.</em></p>
<blockquote class="blockquote">
<p>1.7 Latitude: |__|__|.|__|__|__|__|__|<br>
1.8 Longitude: |__|__|.|__|__|__|__|__|<br>
1.8.1 Accuracy shown by the device, in metres: |__|__|__|</p>
</blockquote>
<p><strong>1.9</strong> <strong>Is this health facility located in an urban, a rural or a peri-urban area?</strong><br>
<em>USE THE ADMINISTRATIVE CLASSIFICATION IN FORCE. IF IN DOUBT, ASK THE RESPONDENT.</em></p>
<blockquote class="blockquote">
<p>1 Urban · 2 Rural · 3 Peri-urban</p>
</blockquote>
<p><em>Allows urban/rural disaggregation of every indicator in this form.</em></p>
<hr>
</section>
<section id="section-2-ownership-and-management" class="level2">
<h2 class="anchored" data-anchor-id="section-2-ownership-and-management">SECTION 2 — Ownership and management</h2>
<p><strong>2.1</strong> <strong>Who owns this health facility?</strong><br>
<em>MARK ONE OPTION ONLY.</em></p>
<blockquote class="blockquote">
<p>1 Public — National Health Service · 2 Public — Police or Armed Forces · 3 Private not-for-profit (religious denomination, non-governmental organization, association) · 4 Private for-profit · 96 Other situation (specify) ______</p>
</blockquote>
<p><strong>2.2</strong> <strong>Which entity is responsible for the day-to-day management of this facility — that is, who appoints the management and answers for its daily operation?</strong><br>
<em>THIS MAY DIFFER FROM THE OWNER RECORDED IN 2.1.</em></p>
<blockquote class="blockquote">
<p>1 Public · 2 Private · 3 Mixed · 96 Other situation (specify) ______</p>
</blockquote>
<hr>
</section>
<section id="section-3-catchment-population-and-referral-system" class="level2">
<h2 class="anchored" data-anchor-id="section-3-catchment-population-and-referral-system">SECTION 3 — Catchment population and referral system</h2>
<div style="border-left:5px solid #1e8449;background:#eafaf1;padding:10px 14px;border-radius:5px;">
<p><strong>Why this section matters more than it appears to.</strong> The catchment population is the denominator of the densities. Crossed with the staff count in Section 11 and with the beds in Section 8, it yields on its own twenty-three system-level indicators — the kind of figure that underpins resource allocation decisions and that no sample survey can deliver with national coverage.</p>
</div>
<section id="catchment-population" class="level3">
<h3 class="anchored" data-anchor-id="catchment-population">3.1 Catchment population</h3>
<p><strong>3.1</strong> <strong>What is the total resident population in the catchment area of this health facility, according to the most recent estimate available to the facility?</strong><br>
<em>RECORD THE NUMBER OF INHABITANTS. RECORD 999998 IF THE FACILITY HAS NO ESTIMATE.</em></p>
<blockquote class="blockquote">
<p>|__|__|__|__|__|__| inhabitants</p>
</blockquote>
<p><em>HHFA indicators: <strong>1.1.1.1.1 to 1.1.1.1.4</strong> (facility and bed density), <strong>1.2.2.1.1 to 1.2.2.4.8</strong> (health worker density per 10,000 population), <strong>1.4.1.1.1 to 1.4.1.1.3</strong> (density scores).</em></p>
<p><strong>3.1.1</strong> <strong>Where does that population estimate come from?</strong></p>
<blockquote class="blockquote">
<p>1 National census · 2 Projection by the National Institute of Statistics · 3 Registration or enumeration carried out by the facility itself · 4 Estimate provided by the Municipal Health Directorate · 5 Estimate provided by the Provincial Health Directorate · 96 Other (specify) ______ · 98 Does not know</p>
</blockquote>
<p><strong>3.1.2</strong> <strong>Which year does that estimate refer to?</strong> |__|__|__|__|</p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>Why these two questions.</strong> In the current Form, 3.1 asks for the catchment population “if known”, and nothing more. A 2014 census estimate and a head count made by the facility itself last year go into the same field and produce densities that cannot be compared. Two short questions qualify the denominator and make it possible, at the analysis stage, to decide which estimates to use.</p>
</div>
</section>
<section id="referral-facility" class="level3">
<h3 class="anchored" data-anchor-id="referral-facility">3.2 Referral facility</h3>
<p><strong>3.2.1</strong> <strong>To which health facility are patients from this facility usually transferred when they need care that cannot be provided here?</strong><br>
<em>IF THERE IS MORE THAN ONE, GIVE THE ONE TO WHICH THE LARGEST NUMBER OF PATIENTS WAS TRANSFERRED IN THE PAST 12 MONTHS.</em></p>
<blockquote class="blockquote">
<p>Name of the facility: ______ · Health Map code: |__|__|__|__|__|__|</p>
</blockquote>
<p><strong>3.2.2</strong> Category of that referral facility, according to the Health Map classification: |__|__|</p>
<p><strong>3.2.3</strong> <strong>What is the means of transport most frequently used to transfer patients from this facility to the facility named in 3.2.1?</strong><br>
<em>CONSIDER THE PAST 12 MONTHS. MARK ONE OPTION ONLY.</em></p>
<blockquote class="blockquote">
<p>1 Ambulance belonging to this facility · 2 Ambulance from another facility or from the Municipal Directorate · 3 Light vehicle belonging to the facility · 4 Motorcycle · 5 Public or private transport, paid for by the patient or the family · 6 On foot or by stretcher · 96 Other (specify) ______</p>
</blockquote>
<p><strong>3.2.4</strong> <strong>Considering the route usually taken by that means of transport, what is the total distance, in kilometres, between this health facility and the referral facility?</strong><br>
<em>DISTANCE ALONG THE ROAD ACTUALLY TRAVELLED, NOT IN A STRAIGHT LINE. RECORD 998 IF NOT KNOWN.</em></p>
<blockquote class="blockquote">
<p>|__|__|__| kilometres</p>
</blockquote>
<p><strong>3.2.5</strong> <strong>Of that route, how many kilometres are on paved road?</strong></p>
<blockquote class="blockquote">
<p>|__|__|__| kilometres</p>
</blockquote>
<p><strong>3.2.6</strong> <strong>And how many kilometres are on dirt road or dirt track?</strong></p>
<blockquote class="blockquote">
<p>|__|__|__| kilometres</p>
</blockquote>
<p><em>CONSISTENCY CHECK: 3.2.5 + 3.2.6 must equal 3.2.4. IF IT DOES NOT, CONFIRM WITH THE RESPONDENT BEFORE CONTINUING.</em></p>
<p><strong>3.2.7</strong> <strong>In the dry season, how long does that route usually take, in minutes, by the means of transport given in 3.2.3?</strong><br>
<em>TRAVEL TIME ONLY, NOT COUNTING TIME SPENT WAITING FOR TRANSPORT. RECORD 998 IF NOT KNOWN.</em></p>
<blockquote class="blockquote">
<p>|__|__|__| minutes</p>
</blockquote>
<p><strong>3.2.8</strong> <strong>And in the rainy season, how long does the same route usually take, in minutes?</strong><br>
<em>RECORD 997 IF THE ROUTE BECOMES IMPASSABLE AT ANY POINT DURING THE RAINY SEASON. RECORD 998 IF NOT KNOWN.</em></p>
<blockquote class="blockquote">
<p>|__|__|__| minutes</p>
</blockquote>
<p><em>Indicators: <strong>[MS]</strong>. Crossed with 2.1.1.1.7 (emergency transport), they make it possible to identify the areas where obstetric evacuation cannot be achieved within a useful time.</em></p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>What has changed, and why.</strong> The current Form has an item 3.2.3 with four fields — minutes, total km, km of paved road, km of dirt track — and no instruction at all. Nothing says which road is to be measured, in which means of transport the minutes are counted, whether the time includes waiting for the ambulance, or what to do when the dirt track becomes impassable in the rains. Three enumerators produce three different answers for the same facility, and the difference between them is indistinguishable from the real difference between facilities.</p>
<p>The six questions above fix: <strong>the means of transport</strong> (3.2.3, which becomes a datum with value in its own right — a facility that evacuates on foot is a different reality), <strong>the road actually travelled</strong> rather than the straight line, <strong>the breakdown verified by addition</strong>, and <strong>the two seasons of the year</strong>, with a code of its own for the impassable route. It becomes possible to calculate evacuation time in the worst season, which is the information that matters for maternal mortality.</p>
</div>
</section>
<section id="functioning-of-the-referral-system" class="level3">
<h3 class="anchored" data-anchor-id="functioning-of-the-referral-system">3.3 Functioning of the referral system</h3>
<p><strong>3.3</strong> <strong>Does this facility have an established system for referring patients to other health facilities?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No · 98 Does not know</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.7.1.1.1</strong>.</em></p>
<p><strong>3.4 ◆</strong> <strong>Are there written guidelines or protocols in this facility that guide the referral of patients to other facilities?</strong><br>
<em>IF YES, ASK TO SEE THE DOCUMENT.</em></p>
<blockquote class="blockquote">
<p>1 Yes, observed · 2 Yes, reported but not seen · 3 Not available</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.7.1.1.2</strong> (only option 1 counts).</em></p>
<p><strong>3.5 ◆</strong> <strong>And are there written guidelines or protocols for back-referral — that is, for the patient’s return to this facility after being seen at the referral facility?</strong><br>
<em>IF YES, ASK TO SEE THE DOCUMENT.</em></p>
<blockquote class="blockquote">
<p>1 Yes, observed · 2 Yes, reported but not seen · 3 Not available</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.7.1.1.3</strong>.</em></p>
<p><strong>3.6 ◆</strong> <strong>Does this facility keep a record, in a register book or in a file, of the patients it has referred to other facilities?</strong><br>
<em>IF YES, ASK TO SEE THE RECORD.</em></p>
<blockquote class="blockquote">
<p>1 Yes, observed · 2 Yes, reported but not seen · 3 Keeps no record</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.7.1.1.4</strong>.</em></p>
<p><strong>3.7</strong> <strong>In the past 3 months, has this facility received clinical information back about patients it had referred — in writing or by any other means?</strong></p>
<blockquote class="blockquote">
<p>1 Yes, about most of the patients referred · 2 Yes, about some patients · 3 Received no information back · 97 Referred no patients in the past 3 months · 98 Does not know</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.7.1.1.5</strong> (options 1 and 2 count).</em></p>
<p><strong>3.8</strong> <strong>Does this facility have access, 24 hours a day and every day of the week, to a vehicle in working order and to a driver available to transport patients?</strong><br>
<em>THE VEHICLE MAY BE STATIONED AT THIS FACILITY OR BE CALLED IN FROM ELSEWHERE.</em></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No · 98 Does not know</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.7.1.1.6</strong>.</em></p>
<hr>
</section>
</section>
<section id="section-4-buildings-and-construction" class="level2">
<h2 class="anchored" data-anchor-id="section-4-buildings-and-construction">SECTION 4 — Buildings and construction</h2>
<p><strong>[MS] — A section specific to the Health Map.</strong> The HHFA collects none of this information, and it is the basis of decisions on construction works. It is retained in full, with the wording made precise.</p>
<p><strong>4.1</strong> <strong>How many buildings, in total, make up this health facility?</strong><br>
<em>COUNT ALL BUILDINGS WITHIN THE GROUNDS THAT ARE USED BY THE FACILITY, INCLUDING SUPPORT BUILDINGS — STORE, KITCHEN, LAUNDRY, MORTUARY. DO NOT COUNT STAFF HOUSING, WHICH IS COUNTED IN 4.3. DO NOT COUNT BUILDINGS IN RUINS OR WITH NO USE AT ALL.</em></p>
<blockquote class="blockquote">
<p>|__|__| buildings</p>
</blockquote>
<p><strong>4.2</strong> <strong>What is the total covered floor area of those buildings, in square metres?</strong><br>
<em>ADD UP THE COVERED AREA OF ALL THE BUILDINGS COUNTED IN 4.1. RECORD 9998 IF NOT KNOWN.</em></p>
<blockquote class="blockquote">
<p>|__|__|__|__| m²</p>
</blockquote>
<p><strong>4.3</strong> <strong>How many staff houses are there within the grounds of this facility or under its responsibility?</strong></p>
<blockquote class="blockquote">
<p>|__|__| houses</p>
</blockquote>
<p><strong>4.4</strong> <strong>What is the total covered floor area of those houses, in square metres?</strong></p>
<blockquote class="blockquote">
<p>|__|__|__|__| m²</p>
</blockquote>
<p><strong>4.5</strong> <strong>In which year was construction of the main building of this facility completed?</strong><br>
<em>IF IT HAS BEEN SUBSTANTIALLY REBUILT, GIVE THE YEAR OF THE REBUILDING. RECORD 9998 IF NOT KNOWN.</em></p>
<blockquote class="blockquote">
<p>|__|__|__|__|</p>
</blockquote>
<p><strong>4.6</strong> <strong>In which period was the main building constructed?</strong><br>
<em>READ THE OPTIONS. THIS SERVES TO CLASSIFY THE CASES IN WHICH THE EXACT YEAR IS NOT KNOWN.</em></p>
<blockquote class="blockquote">
<p>1 Before 1975 · 2 Between 1975 and 1991 · 3 Between 1992 and 2002 · 4 Between 2003 and 2012 · 5 From 2013 onwards · 98 Does not know</p>
</blockquote>
<p><strong>4.7</strong> <strong>What is the predominant material of the exterior walls of the main building?</strong><br>
<em>MARK ONE OPTION ONLY — THE MATERIAL COVERING MOST OF THE WALL SURFACE.</em></p>
<blockquote class="blockquote">
<p>1 Cement blocks · 2 Fired brick · 3 Adobe or mud brick · 4 Wattle and daub or timber · 5 Metal sheeting · 96 Other (specify) ______</p>
</blockquote>
<hr>
</section>
<section id="section-5-state-of-repair" class="level2">
<h2 class="anchored" data-anchor-id="section-5-state-of-repair">SECTION 5 — State of repair</h2>
<p><strong>[MS] — A section specific to the Health Map.</strong> It is retained with the construction criteria from the Filling Guide, now made explicit in the question itself.</p>
<p><strong>5.1</strong> <strong>Considering the foundations, the structure, the flooring, the walls, the roof, the false ceiling and the sanitary installations of the main building, which of the following situations best describes its current state?</strong><br>
<em>READ ALL THE OPTIONS BEFORE MARKING. APPLY THE DETAILED CRITERIA IN THE FILLING GUIDE. MARK ONE OPTION ONLY.</em></p>
<blockquote class="blockquote">
<p>1 Needs no intervention — all elements in good condition<br>
2 Needs routine maintenance — minor repairs, painting, occasional replacements<br>
3 Needs rehabilitation — one or more elements degraded, but the structure is sound<br>
4 Needs reconstruction — structure compromised or building unusable</p>
</blockquote>
<p><strong>5.2</strong> <strong>What is the covered floor area, in square metres, that is in each of the following states?</strong><br>
<em>THE SUM MUST EQUAL THE TOTAL FLOOR AREA GIVEN IN 4.2.</em></p>
<blockquote class="blockquote">
<p>5.2.1 In good condition: |__|__|__|__| m²<br>
5.2.2 Needing routine maintenance: |__|__|__|__| m²<br>
5.2.3 Needing rehabilitation: |__|__|__|__| m²<br>
5.2.4 Needing reconstruction: |__|__|__|__| m²</p>
</blockquote>
<p><em>CONSISTENCY CHECK: 5.2.1 + 5.2.2 + 5.2.3 + 5.2.4 must equal 4.2.</em></p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>What has changed.</strong> In the current Form, 5.2 is a free-text field. Four numeric fields with a sum check make the information directly usable for costing the works, which is the purpose the Filling Guide declares for this item — and they oblige whoever completes the form to apportion the area, rather than write a sentence.</p>
</div>
<hr>
</section>
<section id="section-6-water-energy-sanitation-and-waste" class="level2">
<h2 class="anchored" data-anchor-id="section-6-water-energy-sanitation-and-waste">SECTION 6 — Water, energy, sanitation and waste</h2>
<section id="water" class="level3">
<h3 class="anchored" data-anchor-id="water">6.1 Water</h3>
<p><strong>6.1</strong> <strong>What is the water source most used by this health facility at present?</strong><br>
<em>READ THE OPTIONS. MARK ONE ONLY. IF THE ANSWER DIFFERS BETWEEN INPATIENT CARE AND OUTPATIENT CARE, GIVE THE ONE FOR INPATIENT CARE.</em></p>
<blockquote class="blockquote">
<p>01 Piped into the building · 02 Piped into the facility grounds · 03 Public tap or standpipe · 04 Borehole · 05 Protected dug well · 06 Unprotected dug well · 07 Protected spring · 08 Unprotected spring · 09 Rainwater · 10 Bottled water · 11 Cart with small tank · 12 Tanker truck · 13 Surface water — river, dam, lake or pond · 96 Other (specify) ______ · 00 Has no water source at all · 98 Does not know</p>
</blockquote>
<p><strong>6.1.2</strong> <strong>Besides that one, what other water sources does this facility use when the main source is not available?</strong><br>
<em>MARK ALL THAT APPLY, USING THE SAME CODES AS IN 6.1. RECORD 00 IF THERE IS NO ALTERNATIVE SOURCE.</em></p>
<p><em>Indicator: <strong>[MS]</strong> — the HHFA does not collect secondary water sources. This is a contribution specific to the Health Map.</em></p>
<p><strong>6.2 ◆</strong> <strong>Is water from that source available within the facility grounds — inside the building or inside the grounds?</strong><br>
<em>IF YES, ASK: may I see the water that is available today? If it is inside the building, show me there; otherwise, show me in the grounds. THE WATER MAY BE PIPED OR IN A CONTAINER.</em></p>
<blockquote class="blockquote">
<p>1 Yes, observed inside the building · 2 Yes, observed in the facility grounds · 3 Yes, reported but not seen · 4 No, or available only outside the grounds</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.1.1.1.2</strong> — improved water source = 6.1 in an improved category <strong>and</strong> 6.2 other than 3 and 4.</em></p>
<p><strong>6.3</strong> <strong>In the past 30 days, was there any period in which this facility was without water and this forced it to suspend or limit the provision of services?</strong></p>
<blockquote class="blockquote">
<p>1 There was no such period · 2 Yes, less than a week in total · 3 Yes, a week or more in total · 98 Does not know</p>
</blockquote>
</section>
<section id="energy" class="level3">
<h3 class="anchored" data-anchor-id="energy">6.2 Energy</h3>
<p><strong>6.4</strong> <strong>Does this facility have electricity from any source — public grid, generator, solar power or other — including electricity that powers only stand-alone appliances, such as those of the Expanded Programme on Immunization cold chain?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No</p>
</blockquote>
<p><em>IF 2, GO TO 6.7.</em></p>
<p><strong>6.5</strong> <strong>What is the electricity source most used by this facility?</strong><br>
<em>MARK ONE OPTION ONLY.</em></p>
<blockquote class="blockquote">
<p>1 Public grid · 2 Facility generator · 3 Solar panels · 4 Grid of a neighbouring institution · 96 Other (specify) ______</p>
</blockquote>
<p><strong>6.5.1</strong> <strong>What back-up sources are there, for the periods when the main source fails?</strong><br>
<em>MARK ALL THAT APPLY. RECORD 00 IF THERE IS NO BACK-UP SOURCE.</em></p>
<blockquote class="blockquote">
<p>1 Public grid · 2 Generator · 3 Solar panels · 4 Batteries · 96 Other (specify) ______ · 00 Has no back-up source</p>
</blockquote>
<p><strong>6.6</strong> <strong>In the past 7 days, was there electricity — from the main source or from any back-up source — at all times when this facility was open to the public?</strong><br>
<em>READ ALL THREE OPTIONS.</em></p>
<blockquote class="blockquote">
<p>1 Always available, with no interruptions<br>
2 Often available, with interruptions of less than 2 hours a day<br>
3 Sometimes available, with frequent interruptions or interruptions of more than 2 hours a day</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.1.1.1.1</strong> — facilities with power = 6.4 equal to 1 <strong>and</strong> 6.6 equal to 1 or 2.</em></p>
</section>
<section id="sanitation" class="level3">
<h3 class="anchored" data-anchor-id="sanitation">6.3 Sanitation</h3>
<p><strong>6.7</strong> <strong>Is there a toilet or latrine within the grounds of this facility that can be used by outpatient department users or by staff?</strong><br>
<em>IF YES, ASK: what type is it? May I see it? IF THERE ARE SEVERAL, CONSIDER THE MOST MODERN TYPE.</em></p>
<blockquote class="blockquote">
<p>Flush toilet connected to: 1 sewer system · 2 septic tank · 3 open or unknown outlet<br>
4 Ventilated improved pit latrine · 5 Pit latrine with slab · 6 Composting latrine · 7 Open pit latrine, without slab · 8 Bucket · 9 Hanging toilet · 10 There is no toilet or latrine within the grounds</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.1.1.1.3</strong> — improved sanitation = options 1, 2, 4 or 6.</em></p>
</section>
<section id="waste" class="level3">
<h3 class="anchored" data-anchor-id="waste">6.4 Waste</h3>
<p><strong>6.8</strong> <strong>How is the general waste of this facility collected?</strong></p>
<blockquote class="blockquote">
<p>1 By the municipal administrative services · 2 By a contracted company · 3 By the facility itself · 4 There is no organized collection · 98 Does not know</p>
</blockquote>
<p><em>Indicator: <strong>[MS]</strong>.</em></p>
<p><strong>6.9</strong> <strong>What is the final destination of the sharps waste produced in this facility — needles, blades, broken ampoules?</strong><br>
<em>MARK ONE OPTION ONLY — THE DESTINATION OF MOST OF THIS WASTE.</em></p>
<blockquote class="blockquote">
<p>1 Collected and treated off site · 2 Incinerated at this facility · 3 Burned in the open · 4 Buried in a protected pit · 5 Dumped without any treatment · 96 Other (specify) ______ · 98 Does not know</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.5.1.1.12</strong> (with 6.11 and 6.12).</em></p>
<p><strong>6.10</strong> <strong>And what is the final destination of non-sharp infectious waste — dressings, gauze, used gloves, contaminated materials?</strong><br>
<em>SAME OPTIONS AS 6.9.</em></p>
<p><em>HHFA indicator: <strong>2.5.1.1.13</strong> (with 6.11 and 6.12).</em></p>
<p><strong>6.11 ◆</strong> <strong>Was the incinerator or other waste treatment facility of this facility working today?</strong><br>
<em>ASK TO SEE IT. IF THE DESTINATION GIVEN IN 6.9 AND 6.10 DOES NOT INVOLVE TREATMENT AT THE FACILITY, RECORD 97.</em></p>
<blockquote class="blockquote">
<p>1 Yes, observed working · 2 Was not working · 97 Not applicable · 98 Does not know</p>
</blockquote>
<p><strong>6.12 ◆</strong> <strong>Was fuel available for the incinerator today?</strong></p>
<blockquote class="blockquote">
<p>1 Yes, observed · 2 No · 97 Not applicable · 98 Does not know</p>
</blockquote>
<p><strong>6.13</strong> <strong>Are there written guidelines or standard operating procedures on health care waste management in this facility?</strong><br>
<em>IF YES, ASK TO SEE THEM.</em></p>
<blockquote class="blockquote">
<p>1 Yes, observed · 2 Yes, reported but not seen · 3 There are none</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.5.1.1.2</strong>.</em></p>
<p><strong>6.14</strong> <strong>In the past 2 years, has any health worker currently working in this facility received training in health care waste management?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No · 98 Does not know</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.5.1.1.4</strong>.</em></p>
<p><strong>6.15</strong> <strong>Is there a wastewater treatment plant or system in this facility?</strong></p>
<blockquote class="blockquote">
<p>1 Yes, and it was working in the past 30 days · 2 Yes, but it was not working in the past 30 days · 3 There is none</p>
</blockquote>
<p><em>Indicator: <strong>[MS]</strong>.</em></p>
<hr>
</section>
</section>
<section id="section-7-services" class="level2">
<h2 class="anchored" data-anchor-id="section-7-services">SECTION 7 — Services</h2>
<p>The central section of the Form. It rests on subareas <strong>1.3.2</strong> and <strong>1.3.3</strong> of the HHFA — the ones the instrument reserves for measuring availability without a readiness module.</p>
<p><strong>A note on reading this section.</strong> Two formats are used here. Stand-alone questions are written out in full. Lists of items — vaccines, tests, contraceptive methods — are set out in a table, which is the HHFA’s own format: <strong>the lead-in is read once, in full, and then the items are read one by one</strong>. It is an efficient format provided the lead-in is complete, and that is why all the lead-ins below are written out in full.</p>
<section id="gateway-questions" class="level3">
<h3 class="anchored" data-anchor-id="gateway-questions">7.0 Gateway questions</h3>
<p><strong>7.0.1</strong> <strong>Does this facility provide outpatient care — that is, care for patients who are seen and return home the same day?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No</p>
</blockquote>
<p><em>HHFA indicator: <strong>1.3.1.1.1</strong>.</em></p>
<p><strong>7.0.2</strong> <strong>Does this facility provide inpatient care — that is, care for patients who stay overnight at the facility?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No</p>
</blockquote>
<p><em>HHFA indicator: <strong>1.3.1.1.2</strong>.</em></p>
<p><strong>7.0.3</strong> <strong>On a normal weekday, for how many hours is the outpatient department of this facility open to the public?</strong><br>
<em>COUNT ONLY THE HOURS DURING WHICH PATIENTS ARE ATTENDED TO. IF CARE IS PROVIDED CONTINUOUSLY 24 HOURS, RECORD 24.</em></p>
<blockquote class="blockquote">
<p>|__|__| hours</p>
</blockquote>
<p><strong>7.0.4</strong> <strong>And on how many days a week is the outpatient department open to the public?</strong></p>
<blockquote class="blockquote">
<p>|__| days</p>
</blockquote>
<p><em>HHFA indicators: <strong>1.3.1.2.1 to 1.3.1.2.4</strong>, <strong>1.3.1.3.1</strong>, <strong>1.3.1.3.2</strong>.</em></p>
</section>
<section id="clinical-and-surgical-services" class="level3">
<h3 class="anchored" data-anchor-id="clinical-and-surgical-services">7.1 Clinical and surgical services</h3>
<p><strong>7.1.1 to 7.1.28 — List of specialties.</strong></p>
<p><em>LEAD-IN TO BE READ: “I am going to read out a list of clinical specialties. For each one, tell me whether this facility has a regular clinic in that specialty — that is, on a set day or days of the week — delivered by a qualified health worker. Do not count occasional consultations or clinics that have been suspended for more than 3 months.”</em></p>
<blockquote class="blockquote">
<p>For each specialty: 1 Yes, regular clinic · 2 No</p>
</blockquote>
<p><em>Indicator: <strong>[MS]</strong> — the list of 28 specialties is a contribution specific to the Health Map. The lead-in above fixes the criterion (“regular clinic, on a set day, by a qualified health worker”) that is today left to the judgement of the respondent.</em></p>
<p><strong>7.1.29</strong> <strong>Does this facility carry out any surgical procedure, minor or major?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>IF 2, GO TO 7.2.</em></p>
</blockquote>
<p><em>HHFA indicator: <strong>1.3.2.7.1</strong>.</em></p>
<p><strong>7.1.29.1</strong> <strong>Does this facility carry out minor surgical procedures — that is, procedures performed under local anaesthesia, without the need for an operating theatre?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>1.3.2.7.2</strong></em></p>
</blockquote>
<p><strong>7.1.29.2</strong> <strong>Does this facility carry out major surgical procedures — that is, procedures performed under general or regional anaesthesia, in an operating theatre?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>1.3.2.7.3</strong></em></p>
</blockquote>
<p><strong>7.1.29.3</strong> <strong>Does this facility carry out voluntary medical male circumcision?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>1.3.2.7.4</strong></em></p>
</blockquote>
<p><strong>7.1.29.4</strong> <strong>Of the following three procedures, which have been carried out in this facility in the past 12 months?</strong><br>
<em>READ ALL THREE. MARK EACH ONE.</em></p>
<blockquote class="blockquote">
<ol type="a">
<li>Caesarean section: 1 Yes · 2 No</li>
<li>Laparotomy: 1 Yes · 2 No</li>
<li>Treatment of open fracture: 1 Yes · 2 No</li>
</ol>
</blockquote>
<p><em>HHFA indicators: <strong>1.3.2.7.5</strong> (any of the three) and <strong>1.3.2.7.6</strong> (all three).</em></p>
<p><strong>7.1.30 to 7.1.34</strong> <strong>Does this facility carry out surgical procedures in any of the following specialty areas?</strong></p>
<blockquote class="blockquote">
<p>Paediatric surgery · Maxillofacial surgery · Vascular surgery · Neurosurgery · Plastic surgery — <em>1 Yes · 2 No, for each</em></p>
</blockquote>
<p><em>HHFA indicator: <strong>1.3.2.7.7</strong>.</em></p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>About the marker procedures.</strong> Caesarean section, laparotomy and treatment of open fracture are the three procedures that global surgery uses as markers of essential surgical capacity — they cover obstetrics, the abdomen and trauma. Three questions with a stated reference period say more about actual surgical capacity than the list of specialties does, and the two pieces of information do not exclude each other.</p>
</div>
</section>
<section id="support-services-technologies-procedures-and-tests" class="level3">
<h3 class="anchored" data-anchor-id="support-services-technologies-procedures-and-tests">7.2 Support services — technologies, procedures and tests</h3>
<p>The greatest gain of the form. Where the Form has fourteen yes-or-no boxes, thirty-six indicators are produced, <strong>all in self-reported mode</strong>, because what is asked is what the facility offers, not what is on the shelf.</p>
<section id="a-imaging" class="level4">
<h4 class="anchored" data-anchor-id="a-imaging">7.2.A Imaging</h4>
<p><em>LEAD-IN TO BE READ: “I am going to ask about some imaging examinations. For each one, tell me whether it is performed at this facility, with this facility’s own equipment. Do not count examinations that patients obtain elsewhere on their own initiative.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Examination</th>
<th>Response</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.2.A.1</td>
<td>Ultrasound</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.1.1</strong></td>
</tr>
<tr class="even">
<td>7.2.A.2</td>
<td>Radiography (X-ray)</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.1.2</strong></td>
</tr>
<tr class="odd">
<td>7.2.A.3</td>
<td>Mammography</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.1.3</strong></td>
</tr>
<tr class="even">
<td>7.2.A.4</td>
<td>Computed tomography</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.1.4</strong></td>
</tr>
<tr class="odd">
<td>7.2.A.5</td>
<td>Magnetic resonance imaging</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.1.5</strong></td>
</tr>
<tr class="even">
<td>7.2.A.6</td>
<td>Angiography or catheterization</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.1.6</strong></td>
</tr>
<tr class="odd">
<td>7.2.A.7</td>
<td>Fluoroscopy</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.1.7</strong></td>
</tr>
<tr class="even">
<td>7.2.A.8</td>
<td>Nuclear medicine</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.1.8</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="b-procedures-and-technologies" class="level4">
<h4 class="anchored" data-anchor-id="b-procedures-and-technologies">7.2.B Procedures and technologies</h4>
<p><em>LEAD-IN TO BE READ: “I am going to ask about some procedures. For each one, tell me whether this facility has performed it at least once in the past 3 months. Do not count procedures that the facility could perform but does not perform in practice.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Procedure</th>
<th>Response</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.2.B.1</td>
<td>Defibrillation</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.2.1</strong></td>
</tr>
<tr class="even">
<td>7.2.B.2</td>
<td>Electrocardiogram</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.2.2</strong></td>
</tr>
<tr class="odd">
<td>7.2.B.3</td>
<td>Electroencephalogram</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.2.3</strong></td>
</tr>
<tr class="even">
<td>7.2.B.4</td>
<td>Incubator for newborns</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.2.4</strong></td>
</tr>
<tr class="odd">
<td>7.2.B.5</td>
<td>Phototherapy for neonatal jaundice</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.2.5</strong></td>
</tr>
<tr class="even">
<td>7.2.B.6</td>
<td>Radiotherapy</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.2.6</strong></td>
</tr>
<tr class="odd">
<td>7.2.B.7</td>
<td>Renal dialysis</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.2.7</strong></td>
</tr>
<tr class="even">
<td>7.2.B.8</td>
<td>Mechanical ventilation</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.2.8</strong></td>
</tr>
<tr class="odd">
<td>7.2.B.9</td>
<td>Blood transfusion</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.2.9</strong>, <strong>3.1.4.1.4</strong></td>
</tr>
<tr class="even">
<td>7.2.B.10</td>
<td>Colonoscopy</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.2.10</strong></td>
</tr>
<tr class="odd">
<td>7.2.B.11</td>
<td>Administration of oxygen to patients</td>
<td>1 Yes · 2 No</td>
<td><strong>1.3.3.2.11</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="c-laboratory-tests" class="level4">
<h4 class="anchored" data-anchor-id="c-laboratory-tests">7.2.C Laboratory tests</h4>
<div style="border-left:5px solid #1e8449;background:#eafaf1;padding:10px 14px;border-radius:5px;">
<p><strong>The laboratory case, resolved.</strong> The Filling Guide already requires, in order to tick “1. Laboratory”, that at a minimum thick blood smear, haemoglobin or haematocrit, and simple stool and urine tests be performed — but the Form retains a single tick box. This list writes that definition out, broadens it, and adds the distinction between the test done here and the test sent away. <strong>Seventeen indicators where there was one box, and none of them requires observation.</strong></p>
</div>
<p><em>LEAD-IN TO BE READ: “I am going to ask about laboratory tests. For each one, tell me whether it is performed at this facility, whether the sample is sent to another laboratory with the result coming back to this facility, or whether it is not available to patients of this facility. Consider the usual situation over the past 3 months, and not a one-off stock-out of reagent.”</em></p>
<blockquote class="blockquote">
<p><strong>1</strong> Performed at this facility · <strong>2</strong> Sample sent away, with the result returned · <strong>3</strong> Not available</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Test</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.2.C.1</td>
<td>General microscopy</td>
<td><strong>1.3.3.3.1</strong></td>
</tr>
<tr class="even">
<td>7.2.C.2</td>
<td>Culture and antibiotic sensitivity testing</td>
<td><strong>1.3.3.3.2</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.3</td>
<td>Malaria diagnosis — thick blood smear or rapid test</td>
<td><strong>1.3.3.3.3</strong></td>
</tr>
<tr class="even">
<td>7.2.C.4</td>
<td>Rapid syphilis test</td>
<td><strong>1.3.3.3.4</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.5</td>
<td>HIV diagnostic test</td>
<td><strong>1.3.3.3.5</strong></td>
</tr>
<tr class="even">
<td>7.2.C.6</td>
<td>Tuberculosis diagnostic test</td>
<td><strong>1.3.3.3.6</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.7</td>
<td>Urine pregnancy test</td>
<td><strong>1.3.3.3.7</strong></td>
</tr>
<tr class="even">
<td>7.2.C.8</td>
<td>Urine dipstick — protein</td>
<td><strong>1.3.3.3.8</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.9</td>
<td>Urine dipstick — glucose</td>
<td><strong>1.3.3.3.9</strong></td>
</tr>
<tr class="even">
<td>7.2.C.10</td>
<td>Urine dipstick — ketones</td>
<td><strong>1.3.3.3.10</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.11</td>
<td>Haemoglobin or haematocrit</td>
<td><strong>1.3.3.3.11</strong></td>
</tr>
<tr class="even">
<td>7.2.C.12</td>
<td>Full blood count</td>
<td><strong>1.3.3.3.12</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.13</td>
<td>Blood typing and grouping</td>
<td><strong>1.3.3.3.13</strong></td>
</tr>
<tr class="even">
<td>7.2.C.14</td>
<td>Blood glucose</td>
<td><strong>1.3.3.3.14</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.15</td>
<td>Serum electrolytes</td>
<td><strong>1.3.3.3.15</strong></td>
</tr>
<tr class="even">
<td>7.2.C.16</td>
<td>Renal function tests — urea or creatinine</td>
<td><strong>1.3.3.3.16</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.17</td>
<td>Liver function tests — transaminases or bilirubin</td>
<td><strong>1.3.3.3.17</strong></td>
</tr>
</tbody>
</table>
<p><em>The HHFA indicators count only option 1 (performed at this facility). Option 2 is additional information, useful for planning the laboratory network.</em></p>
</section>
<section id="d-other-support-services" class="level4">
<h4 class="anchored" data-anchor-id="d-other-support-services">7.2.D Other support services</h4>
<p><strong>7.2.6</strong> <strong>Does this facility have a pathology service, unit or section, separate from the clinical analysis laboratory?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>[MS]</strong></em></p>
</blockquote>
<p><strong>7.2.8</strong> <strong>Does this facility provide rehabilitation services — physiotherapy, occupational therapy, speech therapy or physical rehabilitation?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>1.3.2.10.1</strong></em></p>
</blockquote>
<p><strong>7.2.9</strong> <strong>Does this facility have an operating theatre?</strong> If yes, how many operating theatres are in usable condition?</p>
<blockquote class="blockquote">
<p>1 Yes, |__| theatres · 2 No — <em>Indicator: <strong>[MS]</strong> for the count</em></p>
</blockquote>
<p><strong>7.2.10</strong> <strong>Does this facility have a pharmacy or medicines store, with a designated person in charge, that dispenses medicines to patients?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>See the closing note on this item.</em></p>
</blockquote>
<p><strong>7.2.15</strong> <strong>Does this facility provide palliative care — care intended to relieve the suffering of patients with advanced disease, including pain control?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>1.3.2.9.1</strong></em></p>
</blockquote>
</section>
<section id="e-emergency-services" class="level4">
<h4 class="anchored" data-anchor-id="e-emergency-services">7.2.E Emergency services</h4>
<p><strong>7.2.12.1</strong> <strong>Does this facility attend to patients in emergency situations who arrive without an appointment, as the first point of entry into the system?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>IF 2, GO TO 7.3. Indicators: <strong>3.5.1.1.1</strong>, <strong>1.3.2.8.1</strong></em></p>
</blockquote>
<p><strong>7.2.12.2</strong> <strong>Is there a dedicated emergency unit in this facility — a space of its own for emergencies, separate from the outpatient department — open 24 hours a day, every day?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicators: <strong>3.5.1.1.2</strong>, <strong>1.3.2.8.2</strong></em></p>
</blockquote>
<p><strong>7.2.12.3</strong> <strong>Are medical and nursing staff present in the emergency unit 24 hours a day, every day?</strong><br>
<em>CONSIDER PHYSICAL PRESENCE AT THE FACILITY, NOT AVAILABILITY ON CALL.</em></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No · 98 Does not know — <em>Indicator: <strong>3.5.1.1.3</strong></em></p>
</blockquote>
<p><strong>7.2.12.4</strong> <strong>Does the emergency unit have rapid access to emergency transport to refer patients, 24 hours a day?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>3.5.1.1.4</strong></em></p>
</blockquote>
<p><strong>7.2.12.5</strong> <strong>Does the pharmacy of this facility dispense medicines 24 hours a day, every day?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>3.5.1.1.5</strong></em></p>
</blockquote>
<p><strong>7.2.12.6</strong> <strong>Are the radiology services of this facility available 24 hours a day, every day?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No · 97 Has no radiology — <em>Indicator: <strong>3.5.1.1.6</strong></em></p>
</blockquote>
<p><strong>7.2.12.7</strong> <strong>Are the laboratory services of this facility available 24 hours a day, every day?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No · 97 Has no laboratory — <em>Indicator: <strong>3.5.1.1.7</strong></em></p>
</blockquote>
<p><strong>7.2.12.8</strong> <strong>When a patient is transported to another facility in an emergency, are they usually accompanied by a doctor or nurse from this facility?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No · 98 Does not know — <em>Indicator: <strong>3.5.1.1.8</strong></em></p>
</blockquote>
<p><strong>7.2.12.9</strong> <strong>Does the emergency unit have staff of its own, assigned exclusively to this service, who do not rotate through other services of the facility?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>3.5.1.1.9</strong></em></p>
</blockquote>
<p><strong>7.2.12.10</strong> <strong>Is there a formal triage system in the emergency unit, with written criteria for classifying the severity of patients on arrival?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>3.5.1.1.10</strong></em></p>
</blockquote>
</section>
</section>
<section id="public-health-prevention-and-programmes" class="level3">
<h3 class="anchored" data-anchor-id="public-health-prevention-and-programmes">7.3 Public health, prevention and programmes</h3>
<p>Each box of the current Form becomes a gateway question written out in full, followed by a list of components with a lead-in of its own.</p>
<section id="immunization" class="level4">
<h4 class="anchored" data-anchor-id="immunization">7.3.1 Immunization</h4>
<p><strong>GATEWAY:</strong> <strong>Does this facility administer vaccines of the Expanded Programme on Immunization on a regular basis?</strong><br>
<em>DO NOT COUNT ONE-OFF CAMPAIGNS RUN BY EXTERNAL TEAMS.</em></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>IF 2, GO TO 7.3.2. Indicators: <strong>3.2.1.1.1</strong>, <strong>1.3.2.2.1</strong></em></p>
</blockquote>
<p><strong>7.3.1.a</strong> <strong>How often are routine childhood vaccines administered at this facility?</strong></p>
<blockquote class="blockquote">
<p>1 Every day the facility is open · 2 Once or more a week · 3 Monthly or quarterly · 4 Only during campaigns<br>
<em>Indicators: <strong>3.2.1.1.6</strong>, <strong>3.2.1.1.7</strong>, <strong>3.2.1.1.8</strong>.</em></p>
</blockquote>
<p><strong>7.3.1.b to 7.3.1.e</strong> <em>LEAD-IN TO BE READ: “I am going to read out the list of vaccines in the national schedule. For each one, tell me whether this facility usually administers it to the age group indicated. Consider usual practice, and not a one-off stock-out.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Vaccines</th>
<th>Indicators</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>At birth</td>
<td>BCG · Oral polio · Hepatitis B</td>
<td><strong>3.2.1.1.2</strong>, <strong>.9</strong>, <strong>.10</strong>, <strong>.11</strong></td>
</tr>
<tr class="even">
<td>Infants (&lt; 1 year)</td>
<td>BCG · OPV · DPT-HepB-Hib · Rotavirus · IPV</td>
<td><strong>3.2.1.1.3</strong>, <strong>.12</strong> to <strong>.16</strong></td>
</tr>
<tr class="odd">
<td>Children (1 to 5 years)</td>
<td>Measles · Pneumococcal · COVID-19</td>
<td><strong>3.2.1.1.4</strong>, <strong>.17</strong>, <strong>.18</strong>, <strong>.19</strong></td>
</tr>
<tr class="even">
<td>Adolescents and adults</td>
<td>Tetanus · HPV · Influenza · COVID-19 · Pneumococcal · Hepatitis B</td>
<td><strong>3.2.1.1.5</strong>, <strong>.20</strong> to <strong>.25</strong></td>
</tr>
</tbody>
</table>
<p><em>The list needs validation against the national immunization schedule in force.</em></p>
</section>
<section id="to-7.3.5-child-health-and-nutrition" class="level4">
<h4 class="anchored" data-anchor-id="to-7.3.5-child-health-and-nutrition">7.3.2 to 7.3.5 Child health and nutrition</h4>
<p><strong>GATEWAY:</strong> <strong>Does this facility provide preventive or curative care to children under 5 years of age?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>IF 2, GO TO 7.3.6. Indicators: <strong>3.1.8.1.1</strong>, <strong>1.3.2.1.1</strong></em></p>
</blockquote>
<p><em>LEAD-IN TO BE READ: “I am going to ask about services provided to children under 5 years of age. For each one, tell me whether it is usually provided at this facility.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Service</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.5</td>
<td>Routine growth monitoring, with weighing and recording on the child health card</td>
<td><strong>3.1.8.1.2</strong></td>
</tr>
<tr class="even">
<td>7.3.4</td>
<td>Diagnosis or treatment of malnutrition</td>
<td><strong>3.1.8.1.3</strong></td>
</tr>
<tr class="odd">
<td>7.3.4.2</td>
<td>Outpatient management of severe acute malnutrition without complications, with ready-to-use therapeutic food</td>
<td><strong>3.1.8.1.4</strong></td>
</tr>
<tr class="even">
<td>7.3.4.3</td>
<td>Outpatient management of moderate acute malnutrition or other categories</td>
<td><strong>3.1.8.1.5</strong></td>
</tr>
<tr class="odd">
<td>7.3.4.4</td>
<td>Inpatient management of severe malnutrition with complications</td>
<td><strong>3.1.8.1.6</strong></td>
</tr>
<tr class="even">
<td>7.3.2</td>
<td>Routine administration of vitamin A</td>
<td><strong>3.1.8.1.7</strong></td>
</tr>
<tr class="odd">
<td>7.3.2.1</td>
<td>Diagnosis and treatment of anaemia with iron supplementation</td>
<td><strong>3.1.8.1.8</strong></td>
</tr>
<tr class="even">
<td>7.3.4.1</td>
<td>Diagnosis and treatment of diarrhoea with oral rehydration salts and zinc</td>
<td><strong>3.1.8.1.9</strong></td>
</tr>
<tr class="odd">
<td>7.3.2.2</td>
<td>Diagnosis and first-line treatment of pneumonia</td>
<td><strong>3.1.8.1.10</strong></td>
</tr>
<tr class="even">
<td>7.3.2.3</td>
<td>Diagnosis of malaria with a laboratory test and its treatment</td>
<td><strong>3.1.8.1.11</strong></td>
</tr>
<tr class="odd">
<td>7.3.14</td>
<td>Provision of an insecticide-treated net or of a voucher to collect one</td>
<td><strong>3.1.8.1.12</strong></td>
</tr>
<tr class="even">
<td>7.3.17</td>
<td>Regular liaison with community health workers for the follow-up of children</td>
<td><strong>3.1.8.1.13</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="antenatal-care" class="level4">
<h4 class="anchored" data-anchor-id="antenatal-care">7.3.6 Antenatal care</h4>
<p><strong>GATEWAY:</strong> <strong>Does this facility provide antenatal care consultations to pregnant women?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>IF 2, GO TO 7.3.7. Indicators: <strong>3.1.2.1.1</strong>, <strong>1.3.2.1.4</strong></em></p>
</blockquote>
<p><em>LEAD-IN TO BE READ: “I am going to read out a list of actions that may form part of antenatal care. For each one, tell me whether it is usually carried out at this facility, for the women who receive antenatal care here.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Component</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.6.a</td>
<td>Prescription or provision of iron supplements</td>
<td><strong>3.1.2.1.2</strong></td>
</tr>
<tr class="even">
<td>7.3.6.b</td>
<td>Prescription or provision of folic acid</td>
<td><strong>3.1.2.1.3</strong></td>
</tr>
<tr class="odd">
<td>7.3.6.c</td>
<td>Administration of tetanus toxoid vaccine</td>
<td><strong>3.1.2.1.4</strong></td>
</tr>
<tr class="even">
<td>7.3.6.d</td>
<td>Blood pressure measurement at every consultation, to detect hypertensive disorders of pregnancy</td>
<td><strong>3.1.2.1.5</strong></td>
</tr>
<tr class="odd">
<td>7.3.6.e</td>
<td>Routine testing of urine for protein</td>
<td><strong>3.1.2.1.6</strong></td>
</tr>
<tr class="even">
<td>7.3.6.f</td>
<td>Administration of intermittent preventive treatment for malaria</td>
<td><strong>3.1.2.1.9</strong></td>
</tr>
<tr class="odd">
<td>7.3.6.g</td>
<td>Offer of HIV testing to all pregnant women</td>
<td><strong>3.1.2.1.10</strong>, <strong>1.3.2.1.5</strong></td>
</tr>
<tr class="even">
<td>7.3.6.h</td>
<td>Provision of an insecticide-treated net or of a voucher to collect one</td>
<td><strong>3.1.2.1.11</strong></td>
</tr>
<tr class="odd">
<td>7.3.6.i</td>
<td>Routine syphilis testing</td>
<td><strong>3.1.2.1.12</strong></td>
</tr>
<tr class="even">
<td>7.3.6.j</td>
<td>Treatment of syphilis in pregnant women who test positive</td>
<td><strong>3.1.2.1.13</strong></td>
</tr>
<tr class="odd">
<td>7.3.6.k</td>
<td>Diagnosis and treatment of other sexually transmitted infections</td>
<td><strong>3.1.2.1.14</strong></td>
</tr>
<tr class="even">
<td>7.3.6.l</td>
<td>Liaison with community health workers for the identification and follow-up of pregnant women</td>
<td><strong>3.1.2.1.16</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="deliveries-and-emergency-obstetric-care" class="level4">
<h4 class="anchored" data-anchor-id="deliveries-and-emergency-obstetric-care">7.3.7 Deliveries and emergency obstetric care</h4>
<p><strong>GATEWAY:</strong> <strong>Does this facility attend deliveries?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>IF 2, GO TO 7.3.8. Indicators: <strong>3.1.3.1.1</strong>, <strong>1.3.2.1.6</strong></em></p>
</blockquote>
<p><strong>7.3.7.0</strong> <strong>Is delivery care by a skilled health worker — a doctor, nurse or trained midwife — available at this facility 24 hours a day, every day of the week?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>3.1.3.1.2</strong></em></p>
</blockquote>
<p><em>LEAD-IN TO BE READ: “I am going to read out a list of procedures and practices related to delivery. For each one, tell me whether it has been carried out at this facility at least once in the past 3 months. If the procedure is practised here but there has been no case in the past 3 months, answer ‘yes, but no recent cases’.”</em></p>
<blockquote class="blockquote">
<p><strong>1</strong> Yes, carried out in the past 3 months · <strong>2</strong> Yes, practised here, but no cases in the past 3 months · <strong>3</strong> Not carried out at this facility</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Procedure</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.7.a</td>
<td>Administration of parenteral antibiotics to the mother</td>
<td><strong>3.1.3.2.1</strong></td>
</tr>
<tr class="even">
<td>7.3.7.b</td>
<td>Administration of parenteral uterotonics for the treatment of postpartum haemorrhage</td>
<td><strong>3.1.3.2.2</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.c</td>
<td>Administration of parenteral magnesium sulfate for pre-eclampsia or eclampsia</td>
<td><strong>3.1.3.2.3</strong></td>
</tr>
<tr class="even">
<td>7.3.7.d</td>
<td>Assisted vaginal delivery with vacuum extractor or forceps</td>
<td><strong>3.1.3.2.4</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.e</td>
<td>Manual removal of the placenta</td>
<td><strong>3.1.3.2.5</strong></td>
</tr>
<tr class="even">
<td>7.3.7.f</td>
<td>Removal of retained products of conception, by curettage or manual vacuum aspiration</td>
<td><strong>3.1.3.2.6</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.g</td>
<td>Newborn resuscitation with bag and mask</td>
<td><strong>3.1.3.2.7</strong></td>
</tr>
<tr class="even">
<td>7.3.7.h</td>
<td>Administration of antibiotics for premature rupture of membranes</td>
<td><strong>3.1.3.2.8</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.i</td>
<td>Administration of corticosteroids in preterm labour</td>
<td><strong>3.1.3.2.9</strong></td>
</tr>
<tr class="even">
<td>7.3.7.j</td>
<td>Kangaroo mother care for preterm or low-birth-weight newborns</td>
<td><strong>3.1.3.2.10</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.k</td>
<td>Administration of injectable antibiotics for neonatal sepsis</td>
<td><strong>3.1.3.2.11</strong></td>
</tr>
<tr class="even">
<td>7.3.7.l</td>
<td>Administration of oxytocin for the prevention of postpartum haemorrhage</td>
<td><strong>3.1.3.2.12</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.m</td>
<td>Monitoring of labour with a partograph</td>
<td><strong>3.1.3.2.13</strong></td>
</tr>
<tr class="even">
<td>7.3.7.n</td>
<td>Initiation of breastfeeding within the first hour of life</td>
<td><strong>3.1.3.2.14</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.o</td>
<td>Hygienic umbilical cord care</td>
<td><strong>3.1.3.2.15</strong></td>
</tr>
<tr class="even">
<td>7.3.7.p</td>
<td>Drying of the newborn and immediate skin-to-skin contact</td>
<td><strong>3.1.3.2.16</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.q</td>
<td>Rooming-in of mother and newborn</td>
<td><strong>3.1.3.2.17</strong></td>
</tr>
<tr class="even">
<td>7.3.7.r</td>
<td>Delayed umbilical cord clamping</td>
<td><strong>3.1.3.2.18</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.s</td>
<td>Caesarean section</td>
<td><strong>3.1.4.1.3</strong></td>
</tr>
<tr class="even">
<td>7.3.7.t</td>
<td>Blood transfusion for women in labour or postpartum</td>
<td><strong>3.1.4.1.4</strong></td>
</tr>
</tbody>
</table>
<p><strong>Computed from the components, and no longer declared:</strong> <strong>3.1.3.1.3</strong> basic emergency obstetric care, <strong>3.1.3.1.4</strong> all 7 basic signal functions, <strong>3.1.3.1.5</strong> and <strong>3.1.4.1.1</strong> comprehensive care, <strong>3.1.4.1.2</strong> all 9 signal functions, <strong>1.3.2.1.7</strong> and <strong>1.3.2.1.8</strong>, and the indices <strong>3.1.3.2.19 to 3.1.3.2.24</strong>.</p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>The concrete gain, and the reason for the third response option.</strong> Today, ticking BEmONC is a judgement call by whoever fills in the Form. With these twenty lines, BEmONC and CEmONC become <strong>computed results</strong>, and it becomes known <em>which</em> function is missing in each facility — the information that makes action possible. Option 2, “practised here but no recent cases”, exists because in a small facility a quarter can pass without a single manual removal of the placenta without this meaning any lack of capacity. Without that option, the respondent is forced to choose between two wrong answers.</p>
</div>
</section>
<section id="postpartum-care" class="level4">
<h4 class="anchored" data-anchor-id="postpartum-care">7.3.8 Postpartum care</h4>
<p><strong>GATEWAY:</strong> <strong>Does this facility provide postpartum care to the mother, to the newborn, or to both, in the six weeks following delivery?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicators: <strong>3.1.6.1.1</strong>, <strong>1.3.2.1.12</strong></em></p>
</blockquote>
<p><em>LEAD-IN TO BE READ: “For each of the following actions, tell me whether it is usually carried out in the postpartum consultation at this facility.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Component</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.8.a</td>
<td>Family planning counselling</td>
<td><strong>3.1.6.1.2</strong></td>
</tr>
<tr class="even">
<td>7.3.8.b</td>
<td>Counselling on newborn danger signs</td>
<td><strong>3.1.6.1.3</strong></td>
</tr>
<tr class="odd">
<td>7.3.8.c</td>
<td>Counselling on umbilical cord care and hygiene</td>
<td><strong>3.1.6.1.4</strong></td>
</tr>
<tr class="even">
<td>7.3.8.d</td>
<td>Counselling on child nutrition and feeding</td>
<td><strong>3.1.6.1.5</strong></td>
</tr>
<tr class="odd">
<td>7.3.8.e</td>
<td>Counselling on exclusive breastfeeding up to 6 months</td>
<td><strong>3.1.6.1.6</strong></td>
</tr>
<tr class="even">
<td>7.3.8.f</td>
<td>Counselling on the childhood immunization schedule</td>
<td><strong>3.1.6.1.7</strong></td>
</tr>
<tr class="odd">
<td>7.3.8.g</td>
<td>Administration of BCG vaccine to the newborn</td>
<td><strong>3.1.6.1.8</strong></td>
</tr>
<tr class="even">
<td>7.3.8.h</td>
<td>Administration of polio vaccine to the newborn</td>
<td><strong>3.1.6.1.9</strong></td>
</tr>
<tr class="odd">
<td>7.3.8.i</td>
<td>Provision of an insecticide-treated net for the infant</td>
<td><strong>3.1.6.1.10</strong></td>
</tr>
<tr class="even">
<td>7.3.8.j</td>
<td>Liaison with community health workers for the follow-up of the newborn</td>
<td><strong>3.1.6.1.11</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="family-planning" class="level4">
<h4 class="anchored" data-anchor-id="family-planning">7.3.9 Family planning</h4>
<p><strong>GATEWAY:</strong> <strong>Does this facility provide family planning services — counselling, prescription or provision of contraceptive methods?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicators: <strong>3.1.1.1.1</strong>, <strong>1.3.2.1.3</strong></em></p>
</blockquote>
<p><em>LEAD-IN TO BE READ: “I am going to read out a list of contraceptive methods. For each one, tell me whether this facility usually provides or inserts it. Consider usual practice, and not a one-off stock-out.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Method</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.9.a</td>
<td>Combined oral contraceptive pill</td>
<td><strong>3.1.1.1.3</strong></td>
</tr>
<tr class="even">
<td>7.3.9.b</td>
<td>Progestogen-only pill</td>
<td><strong>3.1.1.1.4</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.c</td>
<td>Combined injectable contraceptive</td>
<td><strong>3.1.1.1.5</strong></td>
</tr>
<tr class="even">
<td>7.3.9.d</td>
<td>Progestogen-only injectable contraceptive</td>
<td><strong>3.1.1.1.6</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.e</td>
<td>Male condom</td>
<td><strong>3.1.1.1.7</strong></td>
</tr>
<tr class="even">
<td>7.3.9.f</td>
<td>Female condom</td>
<td><strong>3.1.1.1.8</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.g</td>
<td>Intrauterine device</td>
<td><strong>3.1.1.1.9</strong></td>
</tr>
<tr class="even">
<td>7.3.9.h</td>
<td>Subcutaneous implant</td>
<td><strong>3.1.1.1.10</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.i</td>
<td>Emergency contraception</td>
<td><strong>3.1.1.1.11</strong></td>
</tr>
<tr class="even">
<td>7.3.9.j</td>
<td>Male sterilization (vasectomy)</td>
<td><strong>3.1.1.1.12</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.k</td>
<td>Female sterilization (tubal ligation)</td>
<td><strong>3.1.1.1.13</strong></td>
</tr>
<tr class="even">
<td>7.3.9.l</td>
<td>Cycle beads, for the standard days method</td>
<td><strong>3.1.1.1.14</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.m</td>
<td>Liaison with community health workers for the distribution of methods</td>
<td><strong>3.1.1.1.15</strong></td>
</tr>
</tbody>
</table>
<p><strong>Computed:</strong> <strong>3.1.1.1.2</strong> provision of at least one modern method of contraception.</p>
</section>
<section id="to-7.3.12-hiv" class="level4">
<h4 class="anchored" data-anchor-id="to-7.3.12-hiv">7.3.10 to 7.3.12 HIV</h4>
<p><strong>GATEWAY A:</strong> <strong>Does this facility carry out HIV testing with counselling, on request or on clinical indication?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicators: <strong>3.2.4.1.1</strong>, <strong>1.3.2.3.3</strong></em></p>
</blockquote>
<blockquote class="blockquote">
<p>7.3.10.a Testing of adolescents and adults (15 years and over) — <strong>3.2.4.1.2</strong><br>
7.3.10.b Testing of children aged 5 to 14 years — <strong>3.2.4.1.3</strong><br>
7.3.10.c Testing of children under 5 years of age — <strong>3.2.4.1.4</strong></p>
</blockquote>
<p><strong>GATEWAY B:</strong> <strong>Does this facility provide antiretroviral treatment or follow up patients already on antiretroviral treatment?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicators: <strong>3.2.5.1.1</strong>, <strong>1.3.2.3.5</strong></em></p>
</blockquote>
<blockquote class="blockquote">
<p>7.3.12.a Antiretroviral treatment for adults and adolescents — <strong>3.2.5.1.2</strong><br>
7.3.11.a Antiretroviral treatment for children aged 5 to 14 years — <strong>3.2.5.1.3</strong><br>
7.3.11.b Antiretroviral treatment for children under 5 years of age — <strong>3.2.5.1.4</strong>, <strong>1.3.2.3.6</strong><br>
7.3.12.b Dispensing or prescription of antiretroviral medicines — <strong>3.2.5.1.5</strong><br>
7.3.12.c Clinical follow-up consultations for patients on treatment — <strong>3.2.5.1.6</strong><br>
7.3.12.d Counselling and follow-up of treatment adherence — <strong>3.2.5.1.7</strong></p>
</blockquote>
</section>
<section id="tuberculosis" class="level4">
<h4 class="anchored" data-anchor-id="tuberculosis">7.3.13 Tuberculosis</h4>
<p><strong>GATEWAY:</strong> <strong>Does this facility provide any tuberculosis-related service — diagnosis, treatment or patient follow-up?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicators: <strong>3.2.3.1.1</strong>, <strong>1.3.2.3.7</strong></em></p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Service</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.13.a</td>
<td>Diagnosis or treatment of drug-resistant tuberculosis</td>
<td><strong>3.2.3.1.2</strong></td>
</tr>
<tr class="even">
<td>7.3.13.b</td>
<td>Performance of tuberculosis diagnostic tests</td>
<td><strong>3.2.3.1.3</strong>, <strong>1.3.2.3.8</strong></td>
</tr>
<tr class="odd">
<td>7.3.13.c</td>
<td>Clinical follow-up consultations and prescription of medicines</td>
<td><strong>3.2.3.1.4</strong>, <strong>1.3.2.3.9</strong></td>
</tr>
<tr class="even">
<td>7.3.13.d</td>
<td>Resupply of medicines at follow-up consultations</td>
<td><strong>3.2.3.1.5</strong></td>
</tr>
<tr class="odd">
<td>7.3.13.e</td>
<td>Treatment adherence support, including directly observed treatment</td>
<td><strong>3.2.3.1.6</strong></td>
</tr>
<tr class="even">
<td>7.3.13.f</td>
<td>Offer of HIV testing to all tuberculosis patients</td>
<td><strong>3.2.3.1.7</strong></td>
</tr>
<tr class="odd">
<td>7.3.13.g</td>
<td>Liaison with community health workers to trace defaulters or support treatment</td>
<td><strong>3.2.3.1.8</strong></td>
</tr>
<tr class="even">
<td>7.3.13.h</td>
<td>Inpatient room or ward dedicated to respiratory isolation</td>
<td><strong>3.2.3.1.9</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="malaria-new-block" class="level4">
<h4 class="anchored" data-anchor-id="malaria-new-block">7.3.18 Malaria — new block</h4>
<p><strong>GATEWAY:</strong> <strong>Does this facility carry out malaria diagnosis or treatment?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicators: <strong>1.3.2.3.1</strong>, <strong>3.2.2.1.1</strong></em></p>
</blockquote>
<blockquote class="blockquote">
<p>7.3.18.a Diagnosis by rapid test — <strong>3.2.2.1.3</strong><br>
7.3.18.b Diagnosis by microscopy (thick blood smear) — <strong>3.2.2.1.4</strong><br>
7.3.18.c Treatment started on the basis of signs and symptoms alone, without a laboratory test — <strong>3.2.2.1.5</strong><br>
7.3.18.d Treatment of malaria with antimalarial medicines — <strong>3.2.2.1.6</strong><br>
7.3.18.e Liaison with community health workers for malaria diagnosis or treatment — <strong>3.2.2.1.7</strong></p>
</blockquote>
</section>
<section id="noncommunicable-diseases-new-block" class="level4">
<h4 class="anchored" data-anchor-id="noncommunicable-diseases-new-block">7.3.19 Noncommunicable diseases — new block</h4>
<p><strong>GATEWAY:</strong> <strong>Does this facility carry out diagnosis, treatment or follow-up of patients with any chronic noncommunicable disease?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No — <em>Indicator: <strong>1.3.2.4.1</strong></em></p>
</blockquote>
<p><em>LEAD-IN TO BE READ: “I am going to read out a list of conditions. For each one, tell me whether this facility carries out diagnosis, treatment or regular follow-up of patients with that condition. Answer according to what the facility does in practice, and not according to whether there is a specialist clinic.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Condition</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.19.a</td>
<td>Cardiovascular diseases, including hypertension</td>
<td><strong>1.3.2.4.2</strong></td>
</tr>
<tr class="even">
<td>7.3.19.b</td>
<td>Diabetes</td>
<td><strong>1.3.2.4.3</strong></td>
</tr>
<tr class="odd">
<td>7.3.19.c</td>
<td>Chronic respiratory disease — asthma or chronic obstructive pulmonary disease</td>
<td><strong>1.3.2.4.4</strong></td>
</tr>
<tr class="even">
<td>7.3.19.d</td>
<td>Cervical cancer, including screening</td>
<td><strong>1.3.2.4.6</strong></td>
</tr>
<tr class="odd">
<td>7.3.19.e</td>
<td>Breast cancer, including screening</td>
<td><strong>1.3.2.4.7</strong></td>
</tr>
<tr class="even">
<td>7.3.19.f</td>
<td>Mental disorders — depression, anxiety, psychosis, substance use</td>
<td><strong>1.3.2.5.1</strong></td>
</tr>
<tr class="odd">
<td>7.3.19.g</td>
<td>Neurological diseases, including epilepsy</td>
<td><strong>1.3.2.5.2</strong></td>
</tr>
</tbody>
</table>
<p><strong>Computed:</strong> <strong>1.3.2.4.5</strong> provision of any cancer-related service.</p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>Why the closing instruction in the lead-in is essential.</strong> Without it, a respondent at a health centre with no endocrinologist answers “no” to diabetes, even though diabetes is diagnosed and treated there every day. The instruction “answer according to what the facility does in practice, and not according to whether there is a specialist clinic” is what sets this question apart from the “9. Endocrinology” box of the current Form — and it is what makes the data useful for planning the decentralization of chronic disease management.</p>
</div>
</section>
<section id="to-7.3.17-community-outreach" class="level4">
<h4 class="anchored" data-anchor-id="to-7.3.17-community-outreach">7.3.15 to 7.3.17 Community outreach</h4>
<p><strong>7.3.15</strong> <strong>In the past 12 months, has this facility organized mobile brigades — visits by teams from this facility to locations outside the grounds, to provide care?</strong></p>
<blockquote class="blockquote">
<p>1 Yes, regularly · 2 Yes, occasionally · 3 No</p>
</blockquote>
<p><strong>7.3.16</strong> <strong>In the past 12 months, has this facility organized advanced teams — temporary service points set up outside the grounds?</strong></p>
<blockquote class="blockquote">
<p>1 Yes, regularly · 2 Yes, occasionally · 3 No</p>
</blockquote>
<p><strong>7.3.17</strong> <strong>Are there community development and health agents working in the catchment area of this facility and liaising with it?</strong> If yes, how many?</p>
<blockquote class="blockquote">
<p>1 Yes, |__|__| agents · 2 No · 98 Does not know</p>
</blockquote>
<p><em>Indicator: <strong>[MS]</strong> — these describe the reach of the service beyond the walls of the facility, a dimension the HHFA barely covers and which is a contribution specific to the Health Map.</em></p>
</section>
</section>
<section id="and-7.5-management-services-and-general-services" class="level3">
<h3 class="anchored" data-anchor-id="and-7.5-management-services-and-general-services">7.4 and 7.5 Management services and general services</h3>
<p><strong>7.4.1 to 7.4.17</strong> <em>LEAD-IN TO BE READ: “I am going to read out a list of services and management bodies. For each one, tell me whether it exists in this facility and whether it has been operating in the past 3 months.”</em></p>
<blockquote class="blockquote">
<p>1 Exists and operated in the past 3 months · 2 Exists but did not operate in the past 3 months · 3 Does not exist</p>
</blockquote>
<p><em>Indicator: <strong>[MS]</strong>. The three-point scale replaces the 0-1 box and distinguishes the body that has been set up from the body that is active, without adding any questions.</em></p>
<p><strong>7.5.7</strong> <strong>Does this facility have a means of communication with the outside — fixed telephone, mobile phone or radio — paid for or provided by the facility itself?</strong><br>
<em>DO NOT COUNT STAFF MEMBERS’ PERSONAL MOBILE PHONES.</em></p>
<blockquote class="blockquote">
<p>1 Yes, and it is working · 2 Yes, but it is out of order · 3 No, there are only staff members’ personal mobile phones · 4 There is no means of communication with the outside at all</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.1.1.1.5</strong> (only option 1 counts).</em></p>
<p><strong>7.5.7.1</strong> <strong>Does this facility have at least one working computer?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No</p>
</blockquote>
<p><strong>7.5.7.2</strong> <strong>Is there access to email or to the internet at this facility today?</strong></p>
<blockquote class="blockquote">
<p>1 Yes, through equipment belonging to the facility · 2 Yes, but only through staff members’ personal equipment · 3 There is no access</p>
</blockquote>
<p><strong>7.5.7.3</strong> <strong>Is the cost of the internet connection paid or reimbursed by the management of this facility?</strong></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No · 97 Not applicable</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.1.1.1.6</strong> = 7.5.7.1 equal to 1 <strong>and</strong> 7.5.7.2 equal to 1 <strong>and</strong> 7.5.7.3 equal to 1.</em></p>
<p><strong>7.5.1</strong> <strong>Does this facility have access to an ambulance or to another vehicle in working order for the emergency transport of patients — whether it is stationed at this facility or can be called in from elsewhere?</strong></p>
<blockquote class="blockquote">
<p>1 Yes, ambulance · 2 Yes, another type of vehicle · 3 No</p>
</blockquote>
<p><em>IF 3, GO TO 7.5.2.</em></p>
<p><strong>7.5.1.1</strong> <strong>Is that vehicle available today, in working order, with fuel and with a driver?</strong><br>
<em>IF THE RESPONDENT IS NOT SURE, ASK THEM TO CONFIRM WITH SOMEONE WHO KNOWS.</em></p>
<blockquote class="blockquote">
<p>1 Yes · 2 No · 98 Does not know</p>
</blockquote>
<p><em>HHFA indicator: <strong>2.1.1.1.7</strong> = 7.5.1 equal to 1 or 2 <strong>and</strong> 7.5.1.1 equal to 1.</em></p>
<p><strong>7.5.2 to 7.5.18</strong> <em>LEAD-IN TO BE READ: “I am going to read out a list of general support services. For each one, tell me whether it exists in this facility and whether it has been operating in the past 3 months.”</em></p>
<blockquote class="blockquote">
<p>Kitchen · Dining hall or canteen · Laundry · Mortuary · Hygiene and cleaning · Maintenance · Security · Assembly hall · Library · Staff housing · Chapel · Parking · Grounds and landscaping · Video surveillance · Patient services office<br>
1 Exists and operated in the past 3 months · 2 Exists but did not operate · 3 Does not exist</p>
</blockquote>
<p><strong>7.5.5.2</strong> <strong>How many mortuary drawers does the mortuary of this facility have?</strong> |__|__| · 97 Has no mortuary</p>
<hr>
</section>
</section>
<section id="section-8-beds" class="level2">
<h2 class="anchored" data-anchor-id="section-8-beds">SECTION 8 — Beds</h2>
<p><em>LEAD-IN TO BE READ: “I am going to ask about the number of beds in this facility. Count only the beds that are installed and available to receive patients today. Do not count broken beds, beds kept in a store room, or beds that are planned but not yet installed.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Question</th>
<th>Field</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8.1.1</td>
<td>Observation beds — where the patient stays a few hours and does not stay overnight</td>
<td>|__|__|__|</td>
<td><strong>[MS]</strong> (excluded by definition in the HHFA)</td>
</tr>
<tr class="even">
<td>8.1.2</td>
<td>Adult-size inpatient beds</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.1.1</strong>; with 3.1 → <strong>1.1.1.1.3</strong></td>
</tr>
<tr class="odd">
<td>8.1.2.1</td>
<td>Paediatric-size inpatient beds</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.1.2</strong></td>
</tr>
<tr class="even">
<td>8.1.5</td>
<td>Cots for newborns</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.1.3</strong></td>
</tr>
<tr class="odd">
<td>8.1.6</td>
<td>Of the beds counted above, how many are dedicated to maternity</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.1</strong>; with 3.1 → <strong>1.1.1.1.4</strong></td>
</tr>
<tr class="even">
<td>8.1.7</td>
<td>How many are dedicated to surgery</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.2</strong></td>
</tr>
<tr class="odd">
<td>8.1.8</td>
<td>How many are dedicated to psychiatry</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.3</strong></td>
</tr>
<tr class="even">
<td>8.1.9</td>
<td>How many are dedicated to the emergency unit</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.4</strong></td>
</tr>
<tr class="odd">
<td>8.1.10</td>
<td>How many are adult intensive care beds</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.5</strong></td>
</tr>
<tr class="even">
<td>8.1.11</td>
<td>How many are paediatric intensive care beds</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.6</strong></td>
</tr>
<tr class="odd">
<td>8.1.12</td>
<td>How many are neonatal intensive care cots</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.7</strong></td>
</tr>
<tr class="even">
<td>8.1.13</td>
<td>How many are intermediate care beds</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.8</strong></td>
</tr>
<tr class="odd">
<td>8.1.14</td>
<td>How many are isolation beds</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.9</strong></td>
</tr>
<tr class="even">
<td>8.1.3</td>
<td>Delivery couches installed and usable</td>
<td>|__|__|</td>
<td><strong>[MS]</strong></td>
</tr>
<tr class="odd">
<td>8.1.4</td>
<td>Dental chairs installed and usable</td>
<td>|__|__|</td>
<td><strong>[MS]</strong></td>
</tr>
</tbody>
</table>
<p><em>CONSISTENCY CHECK: the sum of 8.1.6 to 8.1.14 cannot exceed the sum of 8.1.2 and 8.1.2.1.</em></p>
<hr>
</section>
<section id="section-9-equipment" class="level2">
<h2 class="anchored" data-anchor-id="section-9-equipment">SECTION 9 — Equipment</h2>
<p><strong>The only section that requires an enumerator making observations.</strong> It is proposed that the current count be retained in self-reported completion, and that the two verification columns be applied only in the facilities that are visited. The same form thus serves both modes.</p>
<p><em>LEAD-IN TO BE READ, DURING A VISIT ONLY: “I am going to ask about some items of equipment that should be present in the main service area of this facility. For each one, please show me the item and tell me, where applicable, whether it is working. Consider only the equipment available in the service area, and not equipment kept in a store room.”</em></p>
<blockquote class="blockquote">
<p><strong>Column A — availability:</strong> 1 Observed · 2 Reported, not seen · 3 Not available<br>
<strong>Column B — functioning:</strong> 1 Yes, working · 2 Not working · 98 Does not know</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Item</th>
<th>Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9.1.4 ◆</td>
<td>Adult scale</td>
<td><strong>2.2.1.1.8</strong></td>
</tr>
<tr class="even">
<td>9.1.16 ◆</td>
<td>Child scale, graduated in 250 g</td>
<td><strong>2.2.1.1.9</strong></td>
</tr>
<tr class="odd">
<td>9.1.3 ◆</td>
<td>Infant scale, graduated in 100 g</td>
<td><strong>2.2.1.1.10</strong></td>
</tr>
<tr class="even">
<td>9.1.8 ◆</td>
<td>Blood pressure measuring device, digital or manual sphygmomanometer</td>
<td><strong>2.2.1.1.3</strong></td>
</tr>
<tr class="odd">
<td>9.1.7 ◆</td>
<td>Clinical stethoscope</td>
<td><strong>2.2.1.1.2</strong></td>
</tr>
<tr class="even">
<td>9.1.17 ◆</td>
<td>Thermometer</td>
<td><strong>2.2.1.1.1</strong></td>
</tr>
<tr class="odd">
<td>9.1.18 ◆</td>
<td>Pulse oximeter</td>
<td><strong>2.2.1.1.4</strong></td>
</tr>
<tr class="even">
<td>9.1.19 ◆</td>
<td>Adjustable examination light for examining the patient (a torch is acceptable)</td>
<td><strong>2.2.1.1.5</strong></td>
</tr>
<tr class="odd">
<td>9.1.20 ◆</td>
<td>Otoscope</td>
<td><strong>2.2.1.1.6</strong></td>
</tr>
<tr class="even">
<td>9.1.21 ◆</td>
<td>Ophthalmoscope</td>
<td><strong>2.2.1.1.7</strong></td>
</tr>
<tr class="odd">
<td>9.1.22 ◆</td>
<td>Measuring tape</td>
<td><strong>2.2.1.1.11</strong></td>
</tr>
<tr class="even">
<td>9.1.23 ◆</td>
<td>Height board or stadiometer</td>
<td><strong>2.2.1.1.12</strong></td>
</tr>
</tbody>
</table>
<p><strong>Count retained, with the lead-in made precise.</strong> <em>“For each of the following items of equipment, tell me how many units are present in this health facility and were in usable condition in the past month.”</em> — Sterilizer (hot air oven or autoclave) · EPI cold box · X-ray machine · Pinard stethoscope · Obstetric ultrasound machine · Vaginal examination kit with speculum · Uterine evacuation kit · Neonatal resuscitator · Instrumental delivery kit · Disposable delivery kit · Caesarean section kit.</p>
<p><em>Indicator: <strong>[MS]</strong> for the count. <strong>Computed with the full list in the grid:</strong> <strong>2.2.1.1.13</strong> and <strong>2.2.1.1.14</strong>.</em></p>
<hr>
</section>
<section id="section-10-means-of-transport" class="level2">
<h2 class="anchored" data-anchor-id="section-10-means-of-transport">SECTION 10 — Means of transport</h2>
<p><em>LEAD-IN TO BE READ: “I am going to ask about the vehicles assigned to this health facility. Count only the vehicles that belong to this facility or that are permanently assigned to it. For each type, tell me how many are roadworthy today and how many are off the road because of breakdown or missing documentation.”</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>No.</th>
<th>Type of vehicle</th>
<th>Roadworthy</th>
<th>Off the road</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10.1.1</td>
<td>Ambulance</td>
<td>|__|__|</td>
<td>|__|__|</td>
</tr>
<tr class="even">
<td>10.1.2</td>
<td>Light vehicle</td>
<td>|__|__|</td>
<td>|__|__|</td>
</tr>
<tr class="odd">
<td>10.1.3</td>
<td>Four-wheel-drive vehicle</td>
<td>|__|__|</td>
<td>|__|__|</td>
</tr>
<tr class="even">
<td>10.1.4</td>
<td>Motorcycle</td>
<td>|__|__|</td>
<td>|__|__|</td>
</tr>
<tr class="odd">
<td>10.1.5</td>
<td>Other (specify)</td>
<td>|__|__|</td>
<td>|__|__|</td>
</tr>
</tbody>
</table>
<p><em>Indicator: <strong>[MS]</strong> — information the HHFA does not collect and that is essential to the logistical management of the network.</em></p>
<hr>
</section>
<section id="section-11-staff-assigned-to-the-facility" class="level2">
<h2 class="anchored" data-anchor-id="section-11-staff-assigned-to-the-facility">SECTION 11 — Staff assigned to the facility</h2>
<section id="new-section" class="level3">
<h3 class="anchored" data-anchor-id="new-section"><em>New section</em></h3>
<div style="border-left:5px solid #1e8449;background:#eafaf1;padding:10px 14px;border-radius:5px;">
<p><strong>The section that closes the Form’s biggest gap, and the cheapest of them all.</strong> The information comes from the facility’s staffing table, requires no physical verification, and crossed with the catchment population from Section 3 it yields sixteen health worker densities per 10,000 population.</p>
</div>
<p><strong>11.1</strong> <strong>Does this facility have an approved staffing establishment that sets out the authorized number of health workers by qualification?</strong><br>
<em>IF YES, ASK TO SEE THE DOCUMENT.</em></p>
<blockquote class="blockquote">
<p>1 Yes, observed · 2 Yes, reported but not seen · 3 Does not have one</p>
</blockquote>
<p><em>HHFA indicator: <strong>1.2.1.1.1</strong>.</em></p>
<p><strong>11.2</strong> <em>LEAD-IN TO BE READ: “I am going to read out a list of staff categories. For each one, tell me how many people in that category are currently assigned to this health facility, and how many of them are women. Count the people on this facility’s staffing establishment, including those on leave or on sick leave, and not only those present today. Do not count visiting staff or volunteer staff, who are asked about further on.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>No.</th>
<th>Staff category</th>
<th>Total</th>
<th>Women</th>
<th>Indicators</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>11.2.a</td>
<td>General practitioners</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.2</strong>, <strong>1.2.2.2.1</strong>, <strong>1.2.3.2.2</strong></td>
</tr>
<tr class="even">
<td>11.2.b</td>
<td>Doctors specialized in family medicine</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.3</strong>, <strong>1.2.2.2.2</strong></td>
</tr>
<tr class="odd">
<td>11.2.c</td>
<td>Specialist doctors — medical specialties</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.6</strong>, <strong>1.2.2.3.2</strong></td>
</tr>
<tr class="even">
<td>11.2.d</td>
<td>Specialist doctors — paediatrics</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.7</strong>, <strong>1.2.2.3.3</strong></td>
</tr>
<tr class="odd">
<td>11.2.e</td>
<td>Specialist doctors — gynaecology and obstetrics</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.8</strong>, <strong>1.2.2.3.4</strong></td>
</tr>
<tr class="even">
<td>11.2.f</td>
<td>Specialist doctors — surgical specialties</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.9</strong>, <strong>1.2.2.3.5</strong></td>
</tr>
<tr class="odd">
<td>11.2.g</td>
<td>Specialist doctors — psychiatry</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.10</strong>, <strong>1.2.2.3.6</strong></td>
</tr>
<tr class="even">
<td>11.2.h</td>
<td>Nurses</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.3.2</strong>, <strong>1.2.2.1.3</strong></td>
</tr>
<tr class="odd">
<td>11.2.i</td>
<td>Midwives</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.3.3</strong>, <strong>1.2.2.1.4</strong></td>
</tr>
<tr class="even">
<td>11.2.j</td>
<td>Nurse-midwives with dual training</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.3.4</strong></td>
</tr>
<tr class="odd">
<td>11.2.k</td>
<td>Clinical officers</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.3.1</strong>, <strong>1.2.2.1.2</strong></td>
</tr>
<tr class="even">
<td>11.2.l</td>
<td>Dentists</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.4.1</strong>, <strong>1.2.2.4.1</strong></td>
</tr>
<tr class="odd">
<td>11.2.m</td>
<td>Pharmacists</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.4.2</strong>, <strong>1.2.2.4.2</strong></td>
</tr>
<tr class="even">
<td>11.2.n</td>
<td>Nutritionists</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.4.6</strong>, <strong>1.2.2.4.6</strong></td>
</tr>
<tr class="odd">
<td>11.2.o</td>
<td>Physiotherapists</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.4.4</strong>, <strong>1.2.2.4.4</strong></td>
</tr>
<tr class="even">
<td>11.2.p</td>
<td>Laboratory technicians</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.5.2</strong></td>
</tr>
<tr class="odd">
<td>11.2.q</td>
<td>Imaging technicians</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.5.1</strong></td>
</tr>
<tr class="even">
<td>11.2.r</td>
<td>Pharmacy technicians</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.5.3</strong></td>
</tr>
<tr class="odd">
<td>11.2.s</td>
<td>Statistics and medical records technicians</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.5.5</strong></td>
</tr>
<tr class="even">
<td>11.2.t</td>
<td>Other health workers</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.4.9</strong>, <strong>1.2.1.5.6</strong></td>
</tr>
</tbody>
</table>
<p><em>CONSISTENCY CHECK: the number of women cannot exceed the total, on any line.</em></p>
<p><strong>11.3</strong> <strong>How often does this facility receive visits from specialist doctors who are not assigned to it?</strong><br>
<em>CONSIDER THE PAST 12 MONTHS.</em></p>
<blockquote class="blockquote">
<p>1 Never receives any · 2 Daily or weekly · 3 At least once a month · 4 At least once a quarter · 5 Less frequently</p>
</blockquote>
<p><em>HHFA indicators: <strong>1.2.3.3.1</strong> to <strong>1.2.3.3.4</strong>.</em></p>
<p><strong>11.4 to 11.7</strong> <em>LEAD-IN TO BE READ: “For each of the following posts, tell me whether the person holding it has specific training in management — a course, a postgraduate qualification or a recognized qualification in health services management or in administration.”</em></p>
<blockquote class="blockquote">
<p>11.4 Facility director · 11.5 Administrator · 11.6 Clinical director · 11.7 Director of nursing<br>
1 Yes · 2 No · 97 The post does not exist in this facility · 98 Does not know</p>
</blockquote>
<p><em>HHFA indicators: <strong>1.2.3.4.1</strong> to <strong>1.2.3.4.4</strong>.</em></p>
<p><strong>11.8</strong> <strong>Does this facility have health workers who work on a voluntary basis, with no paid contract?</strong> If yes, in which categories?</p>
<blockquote class="blockquote">
<p>11.8.a General practitioner — <strong>1.2.3.5.1</strong><br>
11.8.b Specialist doctor — <strong>1.2.3.5.2</strong><br>
11.8.c Nurse or midwife — <strong>1.2.3.5.3</strong></p>
</blockquote>
<p><strong>Computed:</strong> <strong>1.2.1.2.1</strong> total number of doctors, <strong>1.2.1.2.4</strong> and <strong>1.2.1.2.5</strong>, <strong>1.2.3.1.1 to 1.2.3.1.7</strong> proportion of women by category, <strong>1.2.3.2.1</strong> and <strong>1.2.3.2.3</strong> facilities with at least one doctor.</p>
<p><em>The staff categories need validation against the career structure for health workers in Angola.</em></p>
<hr>
</section>
</section>
<section id="hhfa-indicators-captured-by-this-version" class="level2" style="border-left:6px solid #1e8449;background:#eafaf1;padding:16px 18px;border-radius:6px;">
<h2 class="anchored" data-anchor-id="hhfa-indicators-captured-by-this-version">HHFA indicators captured by this version</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>Subarea</th>
<th>Captured</th>
<th>Total in subarea</th>
<th>Mode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1. General availability</strong></td>
<td>1.1.1 Infrastructure density</td>
<td>4</td>
<td>4</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td></td>
<td>1.1.2 Beds</td>
<td>12</td>
<td>12</td>
<td>Self-reported</td>
</tr>
<tr class="odd">
<td></td>
<td>1.2.1 Number of health workers</td>
<td>26</td>
<td>31</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td></td>
<td>1.2.2 Health worker density</td>
<td>16</td>
<td>20</td>
<td>Self-reported</td>
</tr>
<tr class="odd">
<td></td>
<td>1.2.3 Other workforce indicators</td>
<td>21</td>
<td>21</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td></td>
<td>1.3.1 Outpatient and inpatient care</td>
<td>8</td>
<td>8</td>
<td>Self-reported</td>
</tr>
<tr class="odd">
<td></td>
<td>1.3.2 Availability of specific services</td>
<td>40</td>
<td>46</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td></td>
<td>1.3.3 Technologies and procedures</td>
<td>36</td>
<td>36</td>
<td>Self-reported</td>
</tr>
<tr class="odd">
<td></td>
<td>1.4.1 Density scores</td>
<td>3</td>
<td>3</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td></td>
<td><strong>Subtotal for dimension 1</strong></td>
<td><strong>166</strong></td>
<td><strong>428</strong></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>2. General readiness</strong></td>
<td>2.1.1 Basic amenities</td>
<td>6</td>
<td>9</td>
<td>5 self-reported, 1 with observation</td>
</tr>
<tr class="even">
<td></td>
<td>2.2.1 Basic equipment</td>
<td>14</td>
<td>14</td>
<td>Observation</td>
</tr>
<tr class="odd">
<td></td>
<td>2.5.1 Standard precautions (partial)</td>
<td>4</td>
<td>15</td>
<td>2 self-reported, 2 with observation</td>
</tr>
<tr class="even">
<td></td>
<td>2.7.1 Referral systems</td>
<td>6</td>
<td>6</td>
<td>3 self-reported, 3 with observation</td>
</tr>
<tr class="odd">
<td></td>
<td><strong>Subtotal for dimension 2</strong></td>
<td><strong>30</strong></td>
<td><strong>225</strong></td>
<td></td>
</tr>
<tr class="even">
<td><strong>3. Specific availability</strong></td>
<td>3.1.1 Family planning</td>
<td>15</td>
<td>15</td>
<td>Self-reported</td>
</tr>
<tr class="odd">
<td></td>
<td>3.1.2 Antenatal care</td>
<td>13</td>
<td>16</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td></td>
<td>3.1.3 Delivery and basic emergency obstetric care</td>
<td>29</td>
<td>29</td>
<td>Self-reported</td>
</tr>
<tr class="odd">
<td></td>
<td>3.1.4 Comprehensive emergency obstetric care</td>
<td>4</td>
<td>4</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td></td>
<td>3.1.6 Postpartum care</td>
<td>11</td>
<td>11</td>
<td>Self-reported</td>
</tr>
<tr class="odd">
<td></td>
<td>3.1.8 Child health</td>
<td>13</td>
<td>13</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td></td>
<td>3.2.1 Immunization</td>
<td>25</td>
<td>25</td>
<td>Self-reported</td>
</tr>
<tr class="odd">
<td></td>
<td>3.2.2 Malaria</td>
<td>8</td>
<td>8</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td></td>
<td>3.2.3 Tuberculosis</td>
<td>9</td>
<td>9</td>
<td>Self-reported</td>
</tr>
<tr class="odd">
<td></td>
<td>3.2.4 HIV testing</td>
<td>4</td>
<td>4</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td></td>
<td>3.2.5 Antiretroviral treatment</td>
<td>7</td>
<td>7</td>
<td>Self-reported</td>
</tr>
<tr class="odd">
<td></td>
<td>3.5.1 Emergency care</td>
<td>10</td>
<td>10</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td></td>
<td><strong>Subtotal for dimension 3</strong></td>
<td><strong>148</strong></td>
<td><strong>1,484</strong></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>4. Management and finance</strong></td>
<td>4.2.1 Budget (anchor)</td>
<td>1</td>
<td>11</td>
<td>Self-reported</td>
</tr>
<tr class="even">
<td><strong>TOTAL</strong></td>
<td></td>
<td><strong>345 indicators</strong></td>
<td><strong>2,604</strong></td>
<td><strong>≈ 94% self-reported</strong></td>
</tr>
</tbody>
</table>
<p><strong>Nineteen subareas are completed in full</strong> — every one of their indicators becomes computable, with no gaps: beds, infrastructure density, density scores, outpatient and inpatient care, technologies and procedures, other workforce indicators, family planning, delivery and basic and comprehensive emergency obstetric care, postpartum care, child health, immunization, malaria, tuberculosis, HIV testing, antiretroviral treatment, emergency care, basic equipment and referral systems.</p>
</section>
<section id="what-this-version-delivers-and-what-it-leaves-for-later" class="level2" style="border-left:6px solid #6c3483;background:#f4ecf7;padding:14px 18px;border-radius:6px;">
<h2 class="anchored" data-anchor-id="what-this-version-delivers-and-what-it-leaves-for-later">What this version delivers, and what it leaves for later</h2>
<p><strong>345 HHFA indicators</strong>, out of the 2,604 in the inventory. The number on its own says less than its composition does: <strong>nineteen subareas are completed in full</strong>, and they are precisely the availability subareas — what the Health Map Form was designed for. The instrument now produces, in internationally comparable language, exactly what it already set out to measure.</p>
<p><strong>More than nine in ten yield in self-reported mode.</strong> Only Section 9 requires observation throughout, and it can be applied only in the facilities that are visited without the form ceasing to work in the others.</p>
<p><strong>The greater gain, however, is not in the number of indicators.</strong> It is in the drafting. A question written out in full, with the unit, the period and the point of reference inside it, produces the same answer whoever asks it — and that is what makes two facilities, two provinces and two editions of the Health Map comparable. Several items in this form add no new indicator and are kept here for that reason alone: the distance to the referral facility, the state of repair, the vehicle fleet, the specialties, the general services. They are <strong>[MS]</strong>, they are the Health Map’s own contribution, and they gain in precision without changing their purpose.</p>
<p><strong>Three items are deliberately left unresolved</strong>, and it is worth saying so: the pharmacy (7.2.10), sterilization and the distribution of albendazole remain as questions about existence. In all three cases the corresponding HHFA indicator depends on physical verification — medicine within its expiry date, equipment working, product observed — and there is no honest way of producing it in self-reported mode. They stay as they are until the decision on observation is taken.</p>
<p><strong>What is left for the next phase</strong> is the readiness dimension: guidelines available, staff trained, medicines and diagnostic means verified. These are the Type 3 and Type 4 increments in document 4, and they all require an enumerator making observations. They are left out of this version not because they matter less — in many cases they matter more — but because adopting them depends on a decision about the mode of collection that has not yet been taken.</p>
</section>



</main> <!-- /main -->
<script>
(function () {
  var html = document.documentElement;
  var pt = (html.lang || "pt").toLowerCase().indexOf("pt") === 0;
  var L = pt
    ? { font: "Tipo de letra", size: "Tamanho", sans: "Sans", serif: "Serifa", legible: "Legível",
        smaller: "Diminuir letra", larger: "Aumentar letra", reset: "Tamanho normal",
        lang: "Idioma", other: "English", otherTitle: "Read this page in English", tools: "Leitura" }
    : { font: "Typeface", size: "Size", sans: "Sans", serif: "Serif", legible: "Legible",
        smaller: "Smaller text", larger: "Larger text", reset: "Normal size",
        lang: "Language", other: "Português", otherTitle: "Ler esta página em português", tools: "Reading" };

  function get(k) { try { return localStorage.getItem(k); } catch (e) { return null; } }
  function set(k, v) { try { localStorage.setItem(k, v); } catch (e) {} }

  function el(tag, attrs, text) {
    var n = document.createElement(tag);
    for (var a in attrs) n.setAttribute(a, attrs[a]);
    if (text) n.textContent = text;
    return n;
  }

  // Counterpart page in the other language: same file name in the sibling folder.
  function otherLangUrl() {
    var from = pt ? "/pt/" : "/en/", to = pt ? "/en/" : "/pt/";
    var p = location.pathname, i = p.lastIndexOf(from);
    if (i < 0) return null;
    return p.slice(0, i) + to + p.slice(i + from.length) + location.hash;
  }

  function build() {
    var box = el("div", { "class": "reader-tools", role: "group", "aria-label": L.tools });

    box.appendChild(el("span", { "class": "reader-label" }, L.font));
    var fonts = el("div", { "class": "reader-group" });
    var cur = get("reader-font") || "sans";
    [["sans", L.sans], ["serif", L.serif], ["legible", L.legible]].forEach(function (f) {
      var b = el("button", { type: "button", "aria-pressed": String(cur === f[0]) }, f[1]);
      b.addEventListener("click", function () {
        if (f[0] === "sans") html.removeAttribute("data-font"); else html.setAttribute("data-font", f[0]);
        set("reader-font", f[0]);
        fonts.querySelectorAll("button").forEach(function (x) {
          x.setAttribute("aria-pressed", String(x === b));
        });
      });
      fonts.appendChild(b);
    });
    box.appendChild(fonts);

    box.appendChild(el("span", { "class": "reader-label" }, L.size));
    var sizes = el("div", { "class": "reader-group" });
    function size() { return parseInt(html.getAttribute("data-fontsize") || "0", 10); }
    function applySize(n) {
      n = Math.max(-1, Math.min(2, n));
      if (n === 0) html.removeAttribute("data-fontsize"); else html.setAttribute("data-fontsize", String(n));
      set("reader-fontsize", String(n));
    }
    [["A−", L.smaller, -1], ["A", L.reset, 0], ["A+", L.larger, 1]].forEach(function (s) {
      var b = el("button", { type: "button", title: s[1], "aria-label": s[1] }, s[0]);
      b.addEventListener("click", function () { applySize(s[2] === 0 ? 0 : size() + s[2]); });
      sizes.appendChild(b);
    });
    box.appendChild(sizes);

    var url = otherLangUrl();
    if (url) {
      box.appendChild(el("span", { "class": "reader-label" }, L.lang));
      box.appendChild(el("a", { "class": "reader-lang", href: url, title: L.otherTitle, hreflang: pt ? "en" : "pt" }, L.other));
    }
    return box;
  }

  function mount() {
    var host = document.querySelector("#quarto-sidebar .sidebar-menu-container");
    if (!host) return;
    host.parentNode.insertBefore(build(), host);
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", mount);
  else mount();
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-decisoes.html" class="pagination-link" aria-label="Decisions we will need to take to move forward together">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Decisions we will need to take to move forward together</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./anexo-1.html" class="pagination-link" aria-label="Annex 1 — Proposed questionnaire">
        <span class="nav-page-text">Annex 1 — Proposed questionnaire</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/filustrias/mapa_sanitario_hhfa/blob/main/en/06-ficha-revista.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/filustrias/mapa_sanitario_hhfa/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>