<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Ficha revista – Análise comparativa entre o Mapa Sanitário do MINSA e o Harmonized Health Facility Assessment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./anexo-1.html" rel="next">
<link href="./05-decisoes.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9df49dacef94285149b7f8e8bdfea541.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-b5b6b8a11c53608ffce1e541cbc103e2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-9df49dacef94285149b7f8e8bdfea541.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&amp;family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400&amp;family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,400&amp;display=swap" rel="stylesheet">
<script>
  // Apply the reader's saved typeface and size before the page paints.
  (function () {
    try {
      var d = document.documentElement;
      var f = localStorage.getItem("reader-font");
      var s = localStorage.getItem("reader-fontsize");
      if (f && f !== "sans") d.setAttribute("data-font", f);
      if (s && s !== "0") d.setAttribute("data-fontsize", s);
    } catch (e) {}
  })();
</script>


</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-ficha-revista.html">Ficha revista</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Análise comparativa entre o Mapa Sanitário do MINSA e o Harmonized Health Facility Assessment</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/filustrias/mapa_sanitario_hhfa/tree/main/pt/" title="Código fonte" class="quarto-navigation-tool px-1" aria-label="Código fonte"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo escuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abertura</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-panoramica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Panorâmica</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-formulacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Nota sobre a formulação e apresentação das perguntas e opções de resposta</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-cobertura.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">O que cada instrumento capta sobre a realidade das unidades sanitárias</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-incrementos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Como podemos incrementar a Ficha do Mapa Sanitário usando o HHFA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-decisoes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Decisões que teremos que tomar para avançarmos juntos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ficha-revista.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Ficha revista</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Apêndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexo-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexo 1 — Proposta de questionário</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#leia-primeiro-o-padrão-de-formulação-adotado" id="toc-leia-primeiro-o-padrão-de-formulação-adotado" class="nav-link active" data-scroll-target="#leia-primeiro-o-padrão-de-formulação-adotado">⚠ LEIA PRIMEIRO: o padrão de formulação adotado</a></li>
  <li><a href="#secção-0-identificação-da-recolha" id="toc-secção-0-identificação-da-recolha" class="nav-link" data-scroll-target="#secção-0-identificação-da-recolha">SECÇÃO 0 — Identificação da recolha</a></li>
  <li><a href="#secção-1-localização" id="toc-secção-1-localização" class="nav-link" data-scroll-target="#secção-1-localização">SECÇÃO 1 — Localização</a></li>
  <li><a href="#secção-2-propriedade-e-gestão" id="toc-secção-2-propriedade-e-gestão" class="nav-link" data-scroll-target="#secção-2-propriedade-e-gestão">SECÇÃO 2 — Propriedade e gestão</a></li>
  <li><a href="#secção-3-população-adstrita-e-sistema-de-referência" id="toc-secção-3-população-adstrita-e-sistema-de-referência" class="nav-link" data-scroll-target="#secção-3-população-adstrita-e-sistema-de-referência">SECÇÃO 3 — População adstrita e sistema de referência</a>
  <ul class="collapse">
  <li><a href="#população-adstrita" id="toc-população-adstrita" class="nav-link" data-scroll-target="#população-adstrita">3.1 População adstrita</a></li>
  <li><a href="#unidade-de-referência" id="toc-unidade-de-referência" class="nav-link" data-scroll-target="#unidade-de-referência">3.2 Unidade de referência</a></li>
  <li><a href="#funcionamento-do-sistema-de-referência" id="toc-funcionamento-do-sistema-de-referência" class="nav-link" data-scroll-target="#funcionamento-do-sistema-de-referência">3.3 Funcionamento do sistema de referência</a></li>
  </ul></li>
  <li><a href="#secção-4-edifícios-e-construção" id="toc-secção-4-edifícios-e-construção" class="nav-link" data-scroll-target="#secção-4-edifícios-e-construção">SECÇÃO 4 — Edifícios e construção</a></li>
  <li><a href="#secção-5-estado-de-conservação" id="toc-secção-5-estado-de-conservação" class="nav-link" data-scroll-target="#secção-5-estado-de-conservação">SECÇÃO 5 — Estado de conservação</a></li>
  <li><a href="#secção-6-água-energia-saneamento-e-resíduos" id="toc-secção-6-água-energia-saneamento-e-resíduos" class="nav-link" data-scroll-target="#secção-6-água-energia-saneamento-e-resíduos">SECÇÃO 6 — Água, energia, saneamento e resíduos</a>
  <ul class="collapse">
  <li><a href="#água" id="toc-água" class="nav-link" data-scroll-target="#água">6.1 Água</a></li>
  <li><a href="#energia" id="toc-energia" class="nav-link" data-scroll-target="#energia">6.2 Energia</a></li>
  <li><a href="#saneamento" id="toc-saneamento" class="nav-link" data-scroll-target="#saneamento">6.3 Saneamento</a></li>
  <li><a href="#resíduos" id="toc-resíduos" class="nav-link" data-scroll-target="#resíduos">6.4 Resíduos</a></li>
  </ul></li>
  <li><a href="#secção-7-serviços" id="toc-secção-7-serviços" class="nav-link" data-scroll-target="#secção-7-serviços">SECÇÃO 7 — Serviços</a>
  <ul class="collapse">
  <li><a href="#perguntas-porta" id="toc-perguntas-porta" class="nav-link" data-scroll-target="#perguntas-porta">7.0 Perguntas-porta</a></li>
  <li><a href="#serviços-clínicos-e-cirúrgicos" id="toc-serviços-clínicos-e-cirúrgicos" class="nav-link" data-scroll-target="#serviços-clínicos-e-cirúrgicos">7.1 Serviços clínicos e cirúrgicos</a></li>
  <li><a href="#serviços-de-apoio-tecnologias-procedimentos-e-exames" id="toc-serviços-de-apoio-tecnologias-procedimentos-e-exames" class="nav-link" data-scroll-target="#serviços-de-apoio-tecnologias-procedimentos-e-exames">7.2 Serviços de apoio — tecnologias, procedimentos e exames</a></li>
  <li><a href="#saúde-pública-prevenção-e-programas" id="toc-saúde-pública-prevenção-e-programas" class="nav-link" data-scroll-target="#saúde-pública-prevenção-e-programas">7.3 Saúde pública, prevenção e programas</a></li>
  <li><a href="#e-7.5-serviços-de-gestão-e-serviços-gerais" id="toc-e-7.5-serviços-de-gestão-e-serviços-gerais" class="nav-link" data-scroll-target="#e-7.5-serviços-de-gestão-e-serviços-gerais">7.4 e 7.5 Serviços de gestão e serviços gerais</a></li>
  </ul></li>
  <li><a href="#secção-8-camas" id="toc-secção-8-camas" class="nav-link" data-scroll-target="#secção-8-camas">SECÇÃO 8 — Camas</a></li>
  <li><a href="#secção-9-aparelhos" id="toc-secção-9-aparelhos" class="nav-link" data-scroll-target="#secção-9-aparelhos">SECÇÃO 9 — Aparelhos</a></li>
  <li><a href="#secção-10-meios-de-transporte" id="toc-secção-10-meios-de-transporte" class="nav-link" data-scroll-target="#secção-10-meios-de-transporte">SECÇÃO 10 — Meios de transporte</a></li>
  <li><a href="#secção-11-pessoal-afecto-à-unidade" id="toc-secção-11-pessoal-afecto-à-unidade" class="nav-link" data-scroll-target="#secção-11-pessoal-afecto-à-unidade">SECÇÃO 11 — Pessoal afecto à unidade</a>
  <ul class="collapse">
  <li><a href="#secção-nova" id="toc-secção-nova" class="nav-link" data-scroll-target="#secção-nova"><em>Secção nova</em></a></li>
  </ul></li>
  <li><a href="#indicadores-do-hhfa-capturados-por-esta-versão" id="toc-indicadores-do-hhfa-capturados-por-esta-versão" class="nav-link" data-scroll-target="#indicadores-do-hhfa-capturados-por-esta-versão">Indicadores do HHFA capturados por esta versão</a></li>
  <li><a href="#o-que-esta-versão-produz-e-o-que-deixa-para-depois" id="toc-o-que-esta-versão-produz-e-o-que-deixa-para-depois" class="nav-link" data-scroll-target="#o-que-esta-versão-produz-e-o-que-deixa-para-depois">O que esta versão produz, e o que deixa para depois</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/filustrias/mapa_sanitario_hhfa/blob/main/pt/06-ficha-revista.qmd" class="toc-action"><i class="bi bi-github"></i>Ver o código fonte</a></li><li><a href="https://github.com/filustrias/mapa_sanitario_hhfa/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ficha revista</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div style="border-left:6px solid #0b6e99;background:#eaf4f9;padding:14px 18px;border-radius:6px;">
<p class="chapter-lead">Ficha de Cadastramento de Unidades Sanitárias<br>Proposta de versão revista, com perguntas formuladas por extenso e indicadores do HHFA anotados</p>
<p>Versão de trabalho para discussão com o Gabinete de Estudos, Planeamento e Estatística. Mantém a estrutura, a numeração e o propósito da Ficha versão 19_01, e reformula as perguntas e as opções de resposta segundo a redação do Harmonized Health Facility Assessment, traduzida do original.</p>
<p><strong>Cada pergunta está escrita na íntegra, tal como deve ser lida</strong>, com a unidade de medida, o período de referência e o ponto de referência incorporados no próprio texto. <strong>Cada uma é anotada com o indicador do HHFA que passa a poder ser calculado.</strong></p>
</div>
<section id="leia-primeiro-o-padrão-de-formulação-adotado" class="level3" style="border:3px solid #c0392b;background:#fdecea;padding:18px 20px;border-radius:8px;margin:18px 0;">
<h3 class="anchored" data-anchor-id="leia-primeiro-o-padrão-de-formulação-adotado">⚠ LEIA PRIMEIRO: o padrão de formulação adotado</h3>
<p style="font-size:1.08em;line-height:1.55;margin:0 0 10px 0;"><strong style="color:#c0392b;">Uma pergunta que cada inquiridor tem de completar por sua conta é uma pergunta diferente em cada unidade sanitária.</strong> "Distância à unidade de referência — minutos, km totais" obriga quem recolhe a decidir sozinho por que estrada, com que meio de transporte, em que época do ano e medida como. As respostas que daí saem não são comparáveis entre si, e nenhuma análise posterior consegue recuperar essa variação.</p>
<p style="font-size:1.04em;line-height:1.5;margin:0 0 10px 0;">Esta versão aplica nove regras de formulação a todas as perguntas. São as mesmas que o HHFA aplica, e o efeito é que a pergunta fica igual em todas as unidades, independentemente de quem a faz.</p>
<ol style="font-size:1.0em;line-height:1.5;margin:0 0 12px 0;">
<li><strong>A pergunta lê-se na íntegra, tal como está escrita.</strong> O inquiridor não completa nem resume.</li>
<li><strong>A unidade de medida está dentro da pergunta</strong> — quilómetros, minutos, número de pessoas, metros quadrados.</li>
<li><strong>O período de referência está dentro da pergunta</strong> — hoje, nos últimos 7 dias, nos últimos 3 meses, nos últimos 12 meses, nos últimos 2 anos.</li>
<li><strong>O ponto de referência está dentro da pergunta</strong> — de onde a onde, contado como, por quem, em que condições.</li>
<li><strong>Uma pergunta produz um facto.</strong> Conceitos compostos separam-se em perguntas distintas.</li>
<li><strong>As opções de resposta são mutuamente exclusivas e exaustivas</strong>, e estão escritas no formulário, não deixadas ao critério de quem anota.</li>
<li><strong>Há sempre código para "não sabe"</strong> (98) e, quando aplicável, para "não se aplica" (97). Um campo em branco deixa de ser ambíguo.</li>
<li><strong>As instruções ao inquiridor estão graficamente separadas</strong> do texto a ler ao respondente. Neste documento aparecem em <em>itálico e em maiúsculas</em>.</li>
<li><strong>As verificações de consistência estão declaradas</strong> junto das perguntas a que se aplicam, para serem programadas na aplicação de recolha.</li>
</ol>
<hr style="border:none;border-top:2px dashed #c0392b;margin:14px 0;">
<p style="font-size:1.03em;line-height:1.5;margin:0 0 8px 0;"><strong style="color:#c0392b;">O HHFA prevê instrumentos exatamente como o Mapa Sanitário.</strong> O inventário tem duas subáreas — <strong>1.3.2, disponibilidade de serviços específicos</strong>, e <strong>1.3.3, disponibilidade de tecnologias e procedimentos</strong> — cuja designação termina com a indicação <em>"a usar apenas quando não se aplica o módulo de prontidão"</em>. Esta proposta assenta nessa via, e a consequência é muito favorável: <strong>mais de nove em cada dez indicadores aqui capturados rendem em modo autorreferido</strong>, sem exigir observação nem alterar o processo de recolha atual.</p>
<p style="font-size:1.0em;line-height:1.45;margin:0;"><strong>Convenções.</strong> A numeração dos quesitos existentes é mantida, para que a série histórica se possa reconstruir. <strong>[MS]</strong> marca quesitos próprios do Mapa Sanitário, sem correspondência no HHFA, que se mantêm por serem o seu contributo específico — mas <strong>também eles são reformulados</strong>, porque o problema de formulação é independente da origem da pergunta. <strong>◆</strong> marca as perguntas que exigem inquiridor com observação. As listas assinaladas carecem de validação pelos programas nacionais.</p>
</section>
<hr>
<section id="secção-0-identificação-da-recolha" class="level2">
<h2 class="anchored" data-anchor-id="secção-0-identificação-da-recolha">SECÇÃO 0 — Identificação da recolha</h2>
<p><strong>0.1</strong> Data em que esta ficha foi preenchida: |__|__| dia · |__|__| mês · |__|__|__|__| ano</p>
<p><strong>0.2</strong> <strong>De que modo foi preenchida esta ficha?</strong><br>
<em>LER AS OPÇÕES.</em></p>
<blockquote class="blockquote">
<p>1 Preenchida pelo pessoal da unidade e enviada ao GEPE, sem visita de inquiridor<br>
2 Preenchida por inquiridor durante visita à unidade<br>
3 Preenchida pelo pessoal da unidade e depois conferida por inquiridor em visita</p>
</blockquote>
<p><em>Indicador: metadado essencial. Sem ele não é possível separar, na análise, o que foi verificado do que foi apenas declarado.</em></p>
<p><strong>0.3</strong> <strong>Qual é a função da pessoa que respondeu à maior parte desta ficha?</strong></p>
<blockquote class="blockquote">
<p>1 Director da unidade · 2 Director adjunto · 3 Responsável de enfermagem · 4 Responsável administrativo · 5 Responsável de estatística · 6 Outra função (especificar) ______</p>
</blockquote>
<p><strong>0.4</strong> <strong>Esta unidade dispõe de um orçamento próprio, isto é, de uma dotação de fundos atribuída especificamente a esta unidade, que a sua direcção pode gerir e executar?</strong><br>
<em>NÃO CONSIDERAR FUNDOS GERIDOS INTEGRALMENTE PELA DIRECÇÃO MUNICIPAL OU PROVINCIAL EM NOME DA UNIDADE.</em></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não · 98 Não sabe</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>4.2.1.1.1</strong> (âncora — ver nota).</em></p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>Nota sobre 0.4.</strong> Na Ficha atual, o quesito 0.2 diz apenas “Marcar se a unidade tem ORÇAMENTO PRÓPRIO”, sem definir o que conta como tal. Um director que recebe uma dotação municipal carimbada para a sua unidade e outro que gere uma conta bancária própria respondem os dois “sim”, e são situações administrativamente muito diferentes. A redação acima fixa o critério — <strong>poder gerir e executar</strong> — e exclui explicitamente o caso ambíguo. O indicador 4.2.1.1.1 do HHFA é mais exigente ainda (autonomia para gerir conta bancária própria); propõe-se decidir com o grupo da gestão de finanças públicas qual dos dois critérios serve melhor a Angola, e fixá-lo na pergunta.</p>
</div>
<hr>
</section>
<section id="secção-1-localização" class="level2">
<h2 class="anchored" data-anchor-id="secção-1-localização">SECÇÃO 1 — Localização</h2>
<p><strong>1.1 a 1.5</strong> Província · Município · Comuna ou distrito urbano · Aldeia rural ou bairro urbano · Nome da unidade sanitária<br>
<em>REGISTAR A DESIGNAÇÃO E O CÓDIGO INDICADO PELO MAPA SANITÁRIO.</em></p>
<p><strong>1.6</strong> Categoria da unidade, segundo a classificação do Mapa Sanitário<br>
<em>ESTRATIFICADOR PRINCIPAL DE TODA A ANÁLISE. É a lista nacional de tipos de unidade que substitui a lista genérica do HHFA.</em></p>
<p><strong>1.7 e 1.8</strong> <strong>Leitura das coordenadas geográficas.</strong><br>
<em>EFECTUAR A LEITURA À ENTRADA PRINCIPAL DO EDIFÍCIO PRINCIPAL, AO AR LIVRE, COM O APARELHO ESTÁVEL DURANTE PELO MENOS 60 SEGUNDOS. REGISTAR EM GRAUS DECIMAIS, COM CINCO CASAS DECIMAIS.</em></p>
<blockquote class="blockquote">
<p>1.7 Latitude: |__|__|.|__|__|__|__|__|<br>
1.8 Longitude: |__|__|.|__|__|__|__|__|<br>
1.8.1 Precisão indicada pelo aparelho, em metros: |__|__|__|</p>
</blockquote>
<p><strong>1.9</strong> <strong>Esta unidade sanitária situa-se numa zona urbana, rural ou periurbana?</strong><br>
<em>USAR A CLASSIFICAÇÃO ADMINISTRATIVA EM VIGOR. EM CASO DE DÚVIDA, PERGUNTAR AO RESPONDENTE.</em></p>
<blockquote class="blockquote">
<p>1 Urbana · 2 Rural · 3 Periurbana</p>
</blockquote>
<p><em>Permite a desagregação urbano/rural de todos os indicadores deste formulário.</em></p>
<hr>
</section>
<section id="secção-2-propriedade-e-gestão" class="level2">
<h2 class="anchored" data-anchor-id="secção-2-propriedade-e-gestão">SECÇÃO 2 — Propriedade e gestão</h2>
<p><strong>2.1</strong> <strong>A quem pertence esta unidade sanitária?</strong><br>
<em>MARCAR UMA ÚNICA OPÇÃO.</em></p>
<blockquote class="blockquote">
<p>1 Pública — Serviço Nacional de Saúde · 2 Pública — Polícia ou Forças Armadas · 3 Privada não lucrativa (confissão religiosa, organização não governamental, associação) · 4 Privada lucrativa · 96 Outra situação (especificar) ______</p>
</blockquote>
<p><strong>2.2</strong> <strong>Que entidade é responsável pela gestão corrente desta unidade — isto é, quem nomeia a direcção e responde pelo seu funcionamento no dia a dia?</strong><br>
<em>PODE SER DIFERENTE DO PROPRIETÁRIO INDICADO EM 2.1.</em></p>
<blockquote class="blockquote">
<p>1 Pública · 2 Privada · 3 Mista · 96 Outra situação (especificar) ______</p>
</blockquote>
<hr>
</section>
<section id="secção-3-população-adstrita-e-sistema-de-referência" class="level2">
<h2 class="anchored" data-anchor-id="secção-3-população-adstrita-e-sistema-de-referência">SECÇÃO 3 — População adstrita e sistema de referência</h2>
<div style="border-left:5px solid #1e8449;background:#eafaf1;padding:10px 14px;border-radius:5px;">
<p><strong>Porque esta secção é mais importante do que parece.</strong> A população adstrita é o denominador das densidades. Cruzada com a contagem de pessoal da Secção 11 e com as camas da Secção 8, produz sozinha vinte e três indicadores de nível de sistema — o tipo de número que sustenta decisões de afetação de recursos e que nenhum inquérito por amostra consegue dar com cobertura nacional.</p>
</div>
<section id="população-adstrita" class="level3">
<h3 class="anchored" data-anchor-id="população-adstrita">3.1 População adstrita</h3>
<p><strong>3.1</strong> <strong>Qual é a população total residente na área de abrangência desta unidade sanitária, de acordo com a estimativa mais recente de que a unidade dispõe?</strong><br>
<em>REGISTAR O NÚMERO DE HABITANTES. ANOTAR 999998 SE A UNIDADE NÃO DISPUSER DE ESTIMATIVA.</em></p>
<blockquote class="blockquote">
<p>|__|__|__|__|__|__| habitantes</p>
</blockquote>
<p><em>Indicadores do HHFA: <strong>1.1.1.1.1 a 1.1.1.1.4</strong> (densidade de unidades e de camas), <strong>1.2.2.1.1 a 1.2.2.4.8</strong> (densidade de profissionais por 10 000 habitantes), <strong>1.4.1.1.1 a 1.4.1.1.3</strong> (pontuações de densidade).</em></p>
<p><strong>3.1.1</strong> <strong>De onde provém essa estimativa da população?</strong></p>
<blockquote class="blockquote">
<p>1 Censo nacional · 2 Projeção do Instituto Nacional de Estatística · 3 Registo ou recenseamento feito pela própria unidade · 4 Estimativa fornecida pela Direcção Municipal de Saúde · 5 Estimativa fornecida pela Direcção Provincial de Saúde · 96 Outra (especificar) ______ · 98 Não sabe</p>
</blockquote>
<p><strong>3.1.2</strong> <strong>A que ano se refere essa estimativa?</strong> |__|__|__|__|</p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>Porquê estas duas perguntas.</strong> Na Ficha atual, 3.1 pede a população adstrita “se conhecida”, sem mais. Uma estimativa censitária de 2014 e uma contagem feita pela própria unidade no ano passado entram no mesmo campo e produzem densidades incomparáveis. Duas perguntas curtas qualificam o denominador e permitem, na análise, decidir que estimativas usar.</p>
</div>
</section>
<section id="unidade-de-referência" class="level3">
<h3 class="anchored" data-anchor-id="unidade-de-referência">3.2 Unidade de referência</h3>
<p><strong>3.2.1</strong> <strong>Para que unidade sanitária são habitualmente transferidos os doentes desta unidade que necessitam de cuidados que aqui não podem ser prestados?</strong><br>
<em>SE HOUVER MAIS DO QUE UMA, INDICAR AQUELA PARA ONDE FOI TRANSFERIDO O MAIOR NÚMERO DE DOENTES NOS ÚLTIMOS 12 MESES.</em></p>
<blockquote class="blockquote">
<p>Nome da unidade: ______ · Código do Mapa Sanitário: |__|__|__|__|__|__|</p>
</blockquote>
<p><strong>3.2.2</strong> Categoria dessa unidade de referência, segundo a classificação do Mapa Sanitário: |__|__|</p>
<p><strong>3.2.3</strong> <strong>Qual é o meio de transporte mais frequentemente utilizado para transferir doentes desta unidade para a unidade indicada em 3.2.1?</strong><br>
<em>CONSIDERAR OS ÚLTIMOS 12 MESES. MARCAR UMA ÚNICA OPÇÃO.</em></p>
<blockquote class="blockquote">
<p>1 Ambulância pertencente a esta unidade · 2 Ambulância de outra unidade ou da Direcção Municipal · 3 Viatura ligeira da unidade · 4 Motorizada · 5 Transporte público ou particular, pago pelo doente ou pela família · 6 A pé ou em maca · 96 Outro (especificar) ______</p>
</blockquote>
<p><strong>3.2.4</strong> <strong>Considerando o percurso habitualmente utilizado por esse meio de transporte, qual é a distância total, em quilómetros, entre esta unidade sanitária e a unidade de referência?</strong><br>
<em>DISTÂNCIA PELA ESTRADA EFECTIVAMENTE PERCORRIDA, E NÃO EM LINHA RECTA. ANOTAR 998 SE NÃO SOUBER.</em></p>
<blockquote class="blockquote">
<p>|__|__|__| quilómetros</p>
</blockquote>
<p><strong>3.2.5</strong> <strong>Desse percurso, quantos quilómetros são em estrada asfaltada?</strong></p>
<blockquote class="blockquote">
<p>|__|__|__| quilómetros</p>
</blockquote>
<p><strong>3.2.6</strong> <strong>E quantos quilómetros são em estrada de terra ou picada?</strong></p>
<blockquote class="blockquote">
<p>|__|__|__| quilómetros</p>
</blockquote>
<p><em>VERIFICAÇÃO DE CONSISTÊNCIA: 3.2.5 + 3.2.6 deve ser igual a 3.2.4. SE NÃO FOR, CONFIRMAR COM O RESPONDENTE ANTES DE PROSSEGUIR.</em></p>
<p><strong>3.2.7</strong> <strong>Na época seca, quanto tempo demora habitualmente esse percurso, em minutos, pelo meio de transporte indicado em 3.2.3?</strong><br>
<em>TEMPO DE VIAGEM APENAS, SEM CONTAR O TEMPO DE ESPERA PELO TRANSPORTE. ANOTAR 998 SE NÃO SOUBER.</em></p>
<blockquote class="blockquote">
<p>|__|__|__| minutos</p>
</blockquote>
<p><strong>3.2.8</strong> <strong>E na época das chuvas, quanto tempo demora habitualmente o mesmo percurso, em minutos?</strong><br>
<em>ANOTAR 997 SE O PERCURSO FICAR INTRANSITÁVEL EM ALGUM PERÍODO DA ÉPOCA DAS CHUVAS. ANOTAR 998 SE NÃO SOUBER.</em></p>
<blockquote class="blockquote">
<p>|__|__|__| minutos</p>
</blockquote>
<p><em>Indicadores: <strong>[MS]</strong>. Cruzados com 2.1.1.1.7 (transporte de emergência), permitem identificar as zonas onde a evacuação obstétrica não é exequível dentro do tempo útil.</em></p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>O que mudou, e porquê.</strong> A Ficha atual tem um quesito 3.2.3 com quatro campos — minutos, km totais, km de alcatrão, km de picada — e nenhuma instrução. Nada diz por que estrada se mede, em que meio de transporte se contam os minutos, se o tempo inclui a espera pela ambulância, nem o que fazer quando a picada fica intransitável nas chuvas. Três inquiridores produzem três respostas diferentes para a mesma unidade, e a diferença entre elas é indistinguível da diferença real entre unidades.</p>
<p>As seis perguntas acima fixam: <strong>o meio de transporte</strong> (3.2.3, que passa a ser um dado com valor próprio — uma unidade que evacua a pé é outra realidade), <strong>a estrada efectivamente percorrida</strong> e não a linha recta, <strong>a decomposição verificada por soma</strong>, e <strong>as duas épocas do ano</strong>, com um código próprio para o percurso intransitável. Passa a ser possível calcular o tempo de evacuação na pior época, que é a informação relevante para a mortalidade materna.</p>
</div>
</section>
<section id="funcionamento-do-sistema-de-referência" class="level3">
<h3 class="anchored" data-anchor-id="funcionamento-do-sistema-de-referência">3.3 Funcionamento do sistema de referência</h3>
<p><strong>3.3</strong> <strong>Esta unidade dispõe de um sistema estabelecido para referir doentes a outras unidades sanitárias?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não · 98 Não sabe</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.7.1.1.1</strong>.</em></p>
<p><strong>3.4 ◆</strong> <strong>Existem nesta unidade normas ou protocolos escritos que orientem a referência de doentes para outras unidades?</strong><br>
<em>SE SIM, PEDIR PARA VER O DOCUMENTO.</em></p>
<blockquote class="blockquote">
<p>1 Sim, observado · 2 Sim, referido mas não visto · 3 Não disponível</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.7.1.1.2</strong> (conta apenas a opção 1).</em></p>
<p><strong>3.5 ◆</strong> <strong>E existem normas ou protocolos escritos para a contrarreferência, isto é, para o retorno do doente a esta unidade depois de atendido na unidade de referência?</strong><br>
<em>SE SIM, PEDIR PARA VER O DOCUMENTO.</em></p>
<blockquote class="blockquote">
<p>1 Sim, observado · 2 Sim, referido mas não visto · 3 Não disponível</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.7.1.1.3</strong>.</em></p>
<p><strong>3.6 ◆</strong> <strong>Esta unidade mantém um registo, em livro ou em ficheiro, dos doentes que referiu para outras unidades?</strong><br>
<em>SE SIM, PEDIR PARA VER O REGISTO.</em></p>
<blockquote class="blockquote">
<p>1 Sim, observado · 2 Sim, referido mas não visto · 3 Não mantém registo</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.7.1.1.4</strong>.</em></p>
<p><strong>3.7</strong> <strong>Nos últimos 3 meses, esta unidade recebeu de volta informação clínica sobre doentes que tinha referido — por escrito ou por qualquer outro meio?</strong></p>
<blockquote class="blockquote">
<p>1 Sim, sobre a maioria dos doentes referidos · 2 Sim, sobre alguns doentes · 3 Não recebeu qualquer informação de retorno · 97 Não referiu doentes nos últimos 3 meses · 98 Não sabe</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.7.1.1.5</strong> (conta as opções 1 e 2).</em></p>
<p><strong>3.8</strong> <strong>Esta unidade tem acesso, 24 horas por dia e todos os dias da semana, a uma viatura em condições de funcionamento e a um motorista disponível para o transporte de doentes?</strong><br>
<em>A VIATURA PODE ESTAR ESTACIONADA NESTA UNIDADE OU SER CHAMADA DE OUTRO LOCAL.</em></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não · 98 Não sabe</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.7.1.1.6</strong>.</em></p>
<hr>
</section>
</section>
<section id="secção-4-edifícios-e-construção" class="level2">
<h2 class="anchored" data-anchor-id="secção-4-edifícios-e-construção">SECÇÃO 4 — Edifícios e construção</h2>
<p><strong>[MS] — Secção própria do Mapa Sanitário.</strong> O HHFA não recolhe nenhuma destas informações, e elas são a base das decisões de obra. Mantêm-se todas, com a formulação precisada.</p>
<p><strong>4.1</strong> <strong>Quantos edifícios, no total, compõem esta unidade sanitária?</strong><br>
<em>CONTAR TODOS OS EDIFÍCIOS DENTRO DO RECINTO QUE SEJAM UTILIZADOS PELA UNIDADE, INCLUINDO OS DE APOIO — ARMAZÉM, COZINHA, LAVANDARIA, MORGUE. NÃO CONTAR RESIDÊNCIAS DE TÉCNICOS, QUE SÃO CONTADAS EM 4.3. NÃO CONTAR EDIFÍCIOS EM RUÍNA OU SEM QUALQUER UTILIZAÇÃO.</em></p>
<blockquote class="blockquote">
<p>|__|__| edifícios</p>
</blockquote>
<p><strong>4.2</strong> <strong>Qual é a superfície total coberta desses edifícios, em metros quadrados?</strong><br>
<em>SOMAR A ÁREA COBERTA DE TODOS OS EDIFÍCIOS CONTADOS EM 4.1. ANOTAR 9998 SE NÃO SOUBER.</em></p>
<blockquote class="blockquote">
<p>|__|__|__|__| m²</p>
</blockquote>
<p><strong>4.3</strong> <strong>Quantas residências para técnicos existem no recinto desta unidade ou sob a sua responsabilidade?</strong></p>
<blockquote class="blockquote">
<p>|__|__| residências</p>
</blockquote>
<p><strong>4.4</strong> <strong>Qual é a superfície total coberta dessas residências, em metros quadrados?</strong></p>
<blockquote class="blockquote">
<p>|__|__|__|__| m²</p>
</blockquote>
<p><strong>4.5</strong> <strong>Em que ano foi concluída a construção do edifício principal desta unidade?</strong><br>
<em>SE FOI SUBSTANCIALMENTE RECONSTRUÍDO, INDICAR O ANO DA RECONSTRUÇÃO. ANOTAR 9998 SE NÃO SOUBER.</em></p>
<blockquote class="blockquote">
<p>|__|__|__|__|</p>
</blockquote>
<p><strong>4.6</strong> <strong>Em que período foi construído o edifício principal?</strong><br>
<em>LER AS OPÇÕES. SERVE PARA CLASSIFICAR OS CASOS EM QUE O ANO EXACTO NÃO É CONHECIDO.</em></p>
<blockquote class="blockquote">
<p>1 Antes de 1975 · 2 Entre 1975 e 1991 · 3 Entre 1992 e 2002 · 4 Entre 2003 e 2012 · 5 De 2013 em diante · 98 Não sabe</p>
</blockquote>
<p><strong>4.7</strong> <strong>Qual é o material predominante das paredes exteriores do edifício principal?</strong><br>
<em>MARCAR UMA ÚNICA OPÇÃO — O MATERIAL QUE COBRE A MAIOR PARTE DA SUPERFÍCIE DAS PAREDES.</em></p>
<blockquote class="blockquote">
<p>1 Blocos de cimento · 2 Tijolo cozido · 3 Adobe ou tijolo de barro · 4 Pau a pique ou madeira · 5 Chapa metálica · 96 Outro (especificar) ______</p>
</blockquote>
<hr>
</section>
<section id="secção-5-estado-de-conservação" class="level2">
<h2 class="anchored" data-anchor-id="secção-5-estado-de-conservação">SECÇÃO 5 — Estado de conservação</h2>
<p><strong>[MS] — Secção própria do Mapa Sanitário.</strong> Mantém-se com os critérios construtivos do Guião, agora explicitados na própria pergunta.</p>
<p><strong>5.1</strong> <strong>Considerando as fundações, a estrutura, o pavimento, as paredes, a cobertura, o tecto falso e as instalações sanitárias do edifício principal, qual das seguintes situações melhor descreve o seu estado actual?</strong><br>
<em>LER TODAS AS OPÇÕES ANTES DE MARCAR. APLICAR OS CRITÉRIOS DETALHADOS DO GUIÃO DE PREENCHIMENTO. MARCAR UMA ÚNICA OPÇÃO.</em></p>
<blockquote class="blockquote">
<p>1 Não necessita de intervenção — todos os elementos em bom estado<br>
2 Necessita de manutenção corrente — pequenas reparações, pintura, substituições pontuais<br>
3 Necessita de reabilitação — um ou mais elementos degradados, mas a estrutura está sã<br>
4 Necessita de reconstrução — estrutura comprometida ou edifício inutilizável</p>
</blockquote>
<p><strong>5.2</strong> <strong>Qual é a superfície coberta, em metros quadrados, que se encontra em cada um dos estados seguintes?</strong><br>
<em>A SOMA DEVE SER IGUAL À SUPERFÍCIE TOTAL INDICADA EM 4.2.</em></p>
<blockquote class="blockquote">
<p>5.2.1 Em bom estado: |__|__|__|__| m²<br>
5.2.2 A necessitar de manutenção corrente: |__|__|__|__| m²<br>
5.2.3 A necessitar de reabilitação: |__|__|__|__| m²<br>
5.2.4 A necessitar de reconstrução: |__|__|__|__| m²</p>
</blockquote>
<p><em>VERIFICAÇÃO DE CONSISTÊNCIA: 5.2.1 + 5.2.2 + 5.2.3 + 5.2.4 deve ser igual a 4.2.</em></p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>O que mudou.</strong> Na Ficha atual, 5.2 é um campo de texto livre. Quatro campos numéricos com verificação de soma tornam a informação directamente utilizável para custear a obra, que é o propósito declarado deste quesito no Guião — e obrigam quem preenche a repartir a área, em vez de escrever uma frase.</p>
</div>
<hr>
</section>
<section id="secção-6-água-energia-saneamento-e-resíduos" class="level2">
<h2 class="anchored" data-anchor-id="secção-6-água-energia-saneamento-e-resíduos">SECÇÃO 6 — Água, energia, saneamento e resíduos</h2>
<section id="água" class="level3">
<h3 class="anchored" data-anchor-id="água">6.1 Água</h3>
<p><strong>6.1</strong> <strong>Qual é a fonte de água mais utilizada por esta unidade sanitária neste momento?</strong><br>
<em>LER AS OPÇÕES. MARCAR UMA ÚNICA. SE A RESPOSTA FOR DIFERENTE PARA O INTERNAMENTO E PARA O AMBULATÓRIO, INDICAR A DO INTERNAMENTO.</em></p>
<blockquote class="blockquote">
<p>01 Canalizada para dentro do edifício · 02 Canalizada para o recinto da unidade · 03 Torneira ou fontanário público · 04 Furo · 05 Poço protegido · 06 Poço não protegido · 07 Nascente protegida · 08 Nascente não protegida · 09 Água da chuva · 10 Água engarrafada · 11 Carroça com pequeno depósito · 12 Camião cisterna · 13 Água de superfície — rio, barragem, lago ou lagoa · 96 Outra (especificar) ______ · 00 Não tem qualquer fonte de água · 98 Não sabe</p>
</blockquote>
<p><strong>6.1.2</strong> <strong>Além dessa, que outras fontes de água esta unidade utiliza quando a fonte principal não está disponível?</strong><br>
<em>MARCAR TODAS AS QUE SE APLICAM, USANDO OS MESMOS CÓDIGOS DE 6.1. ANOTAR 00 SE NÃO HOUVER FONTE ALTERNATIVA.</em></p>
<p><em>Indicador: <strong>[MS]</strong> — o HHFA não recolhe fontes secundárias de água. É contributo próprio do Mapa Sanitário.</em></p>
<p><strong>6.2 ◆</strong> <strong>Há água proveniente dessa fonte disponível no recinto da unidade — dentro do edifício ou dentro do recinto?</strong><br>
<em>SE SIM, PERGUNTAR: posso ver a água que está disponível hoje? Se estiver dentro do edifício, mostre-me aí; caso contrário, mostre-me no recinto. A ÁGUA PODE ESTAR CANALIZADA OU EM RECIPIENTE.</em></p>
<blockquote class="blockquote">
<p>1 Sim, observada dentro do edifício · 2 Sim, observada no recinto da unidade · 3 Sim, referida mas não vista · 4 Não, ou disponível apenas fora do recinto</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.1.1.1.2</strong> — fonte de água melhorada = 6.1 numa categoria melhorada <strong>e</strong> 6.2 diferente de 3 e de 4.</em></p>
<p><strong>6.3</strong> <strong>Nos últimos 30 dias, houve algum período em que esta unidade ficou sem água e isso obrigou a suspender ou a limitar a prestação de serviços?</strong></p>
<blockquote class="blockquote">
<p>1 Não houve nenhum período · 2 Sim, no total menos de uma semana · 3 Sim, no total uma semana ou mais · 98 Não sabe</p>
</blockquote>
</section>
<section id="energia" class="level3">
<h3 class="anchored" data-anchor-id="energia">6.2 Energia</h3>
<p><strong>6.4</strong> <strong>Esta unidade dispõe de electricidade proveniente de alguma fonte — rede pública, gerador, energia solar ou outra — incluindo a que alimenta apenas aparelhos autónomos, como os da cadeia de frio do Programa Alargado de Vacinação?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não</p>
</blockquote>
<p><em>SE 2, PASSAR A 6.7.</em></p>
<p><strong>6.5</strong> <strong>Qual é a fonte de electricidade mais utilizada por esta unidade?</strong><br>
<em>MARCAR UMA ÚNICA OPÇÃO.</em></p>
<blockquote class="blockquote">
<p>1 Rede pública · 2 Gerador da unidade · 3 Painéis solares · 4 Rede de uma instituição vizinha · 96 Outra (especificar) ______</p>
</blockquote>
<p><strong>6.5.1</strong> <strong>Que fontes de reserva existem, para os períodos em que a fonte principal falha?</strong><br>
<em>MARCAR TODAS AS QUE SE APLICAM. ANOTAR 00 SE NÃO HOUVER FONTE DE RESERVA.</em></p>
<blockquote class="blockquote">
<p>1 Rede pública · 2 Gerador · 3 Painéis solares · 4 Baterias · 96 Outra (especificar) ______ · 00 Não tem fonte de reserva</p>
</blockquote>
<p><strong>6.6</strong> <strong>Nos últimos 7 dias, houve electricidade — da fonte principal ou de qualquer fonte de reserva — em todos os momentos em que esta unidade esteve aberta ao público?</strong><br>
<em>LER AS TRÊS OPÇÕES.</em></p>
<blockquote class="blockquote">
<p>1 Sempre disponível, sem interrupções<br>
2 Muitas vezes disponível, com interrupções de menos de 2 horas por dia<br>
3 Algumas vezes disponível, com interrupções frequentes ou de mais de 2 horas por dia</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.1.1.1.1</strong> — unidades com energia = 6.4 igual a 1 <strong>e</strong> 6.6 igual a 1 ou 2.</em></p>
</section>
<section id="saneamento" class="level3">
<h3 class="anchored" data-anchor-id="saneamento">6.3 Saneamento</h3>
<p><strong>6.7</strong> <strong>Existe no recinto desta unidade um sanitário ou latrina que possa ser utilizado pelos utentes da consulta externa ou pelo pessoal?</strong><br>
<em>SE SIM, PERGUNTAR: de que tipo é? Posso vê-lo? SE HOUVER VÁRIOS, CONSIDERAR O TIPO MAIS MODERNO.</em></p>
<blockquote class="blockquote">
<p>Autoclismo ligado a: 1 rede de esgotos · 2 fossa séptica · 3 destino aberto ou desconhecido<br>
4 Latrina melhorada ventilada · 5 Latrina com laje · 6 Latrina com compostagem · 7 Latrina de fossa aberta, sem laje · 8 Balde · 9 Sanitário suspenso · 10 Não existe sanitário nem latrina no recinto</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.1.1.1.3</strong> — saneamento melhorado = opções 1, 2, 4 ou 6.</em></p>
</section>
<section id="resíduos" class="level3">
<h3 class="anchored" data-anchor-id="resíduos">6.4 Resíduos</h3>
<p><strong>6.8</strong> <strong>Como é feita a recolha do lixo comum desta unidade?</strong></p>
<blockquote class="blockquote">
<p>1 Pelos serviços administrativos municipais · 2 Por empresa contratada · 3 Pela própria unidade · 4 Não há recolha organizada · 98 Não sabe</p>
</blockquote>
<p><em>Indicador: <strong>[MS]</strong>.</em></p>
<p><strong>6.9</strong> <strong>Qual é o destino final dos resíduos cortantes e perfurantes produzidos nesta unidade — agulhas, lâminas, ampolas partidas?</strong><br>
<em>MARCAR UMA ÚNICA OPÇÃO — O DESTINO DA MAIOR PARTE DESTES RESÍDUOS.</em></p>
<blockquote class="blockquote">
<p>1 Recolhidos e tratados fora da unidade · 2 Incinerados nesta unidade · 3 Queimados a céu aberto · 4 Enterrados em vala protegida · 5 Despejados sem qualquer tratamento · 96 Outro (especificar) ______ · 98 Não sabe</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.5.1.1.12</strong> (com 6.11 e 6.12).</em></p>
<p><strong>6.10</strong> <strong>E qual é o destino final dos resíduos infecciosos não cortantes — pensos, compressas, luvas usadas, material contaminado?</strong><br>
<em>MESMAS OPÇÕES DE 6.9.</em></p>
<p><em>Indicador do HHFA: <strong>2.5.1.1.13</strong> (com 6.11 e 6.12).</em></p>
<p><strong>6.11 ◆</strong> <strong>O incinerador ou outro meio de tratamento de resíduos desta unidade estava a funcionar hoje?</strong><br>
<em>PEDIR PARA VER. SE O DESTINO INDICADO EM 6.9 E 6.10 NÃO ENVOLVER TRATAMENTO NA UNIDADE, ANOTAR 97.</em></p>
<blockquote class="blockquote">
<p>1 Sim, observado a funcionar · 2 Não estava a funcionar · 97 Não se aplica · 98 Não sabe</p>
</blockquote>
<p><strong>6.12 ◆</strong> <strong>Havia hoje combustível disponível para o incinerador?</strong></p>
<blockquote class="blockquote">
<p>1 Sim, observado · 2 Não · 97 Não se aplica · 98 Não sabe</p>
</blockquote>
<p><strong>6.13</strong> <strong>Existem nesta unidade normas escritas ou instruções de trabalho sobre a gestão de resíduos sanitários?</strong><br>
<em>SE SIM, PEDIR PARA VER.</em></p>
<blockquote class="blockquote">
<p>1 Sim, observadas · 2 Sim, referidas mas não vistas · 3 Não existem</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.5.1.1.2</strong>.</em></p>
<p><strong>6.14</strong> <strong>Nos últimos 2 anos, algum profissional que actualmente trabalha nesta unidade recebeu formação em gestão de resíduos sanitários?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não · 98 Não sabe</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.5.1.1.4</strong>.</em></p>
<p><strong>6.15</strong> <strong>Existe nesta unidade uma estação ou sistema de tratamento de águas residuais?</strong></p>
<blockquote class="blockquote">
<p>1 Sim, e estava a funcionar nos últimos 30 dias · 2 Sim, mas não estava a funcionar nos últimos 30 dias · 3 Não existe</p>
</blockquote>
<p><em>Indicador: <strong>[MS]</strong>.</em></p>
<hr>
</section>
</section>
<section id="secção-7-serviços" class="level2">
<h2 class="anchored" data-anchor-id="secção-7-serviços">SECÇÃO 7 — Serviços</h2>
<p>A secção central da Ficha. Assenta nas subáreas <strong>1.3.2</strong> e <strong>1.3.3</strong> do HHFA — as que o instrumento reserva para a medição de disponibilidade sem módulo de prontidão.</p>
<p><strong>Nota de leitura.</strong> Nesta secção usam-se dois formatos. As perguntas isoladas estão escritas por extenso. As listas de itens — vacinas, exames, métodos contraceptivos — são apresentadas em quadro, que é o formato do próprio HHFA: <strong>o enunciado é lido uma vez, na íntegra, e depois lê-se item a item</strong>. É um formato eficiente desde que o enunciado esteja completo, e por isso todos os enunciados abaixo estão escritos na íntegra.</p>
<section id="perguntas-porta" class="level3">
<h3 class="anchored" data-anchor-id="perguntas-porta">7.0 Perguntas-porta</h3>
<p><strong>7.0.1</strong> <strong>Esta unidade presta atendimento em regime de ambulatório, isto é, a doentes que são atendidos e regressam a casa no mesmo dia?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>1.3.1.1.1</strong>.</em></p>
<p><strong>7.0.2</strong> <strong>Esta unidade presta atendimento em regime de internamento, isto é, com doentes que pernoitam na unidade?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>1.3.1.1.2</strong>.</em></p>
<p><strong>7.0.3</strong> <strong>Num dia normal de semana, durante quantas horas está a consulta externa desta unidade aberta ao público?</strong><br>
<em>CONTAR APENAS AS HORAS EM QUE HÁ ATENDIMENTO A UTENTES. SE O ATENDIMENTO FOR CONTÍNUO 24 HORAS, ANOTAR 24.</em></p>
<blockquote class="blockquote">
<p>|__|__| horas</p>
</blockquote>
<p><strong>7.0.4</strong> <strong>E em quantos dias por semana está a consulta externa aberta ao público?</strong></p>
<blockquote class="blockquote">
<p>|__| dias</p>
</blockquote>
<p><em>Indicadores do HHFA: <strong>1.3.1.2.1 a 1.3.1.2.4</strong>, <strong>1.3.1.3.1</strong>, <strong>1.3.1.3.2</strong>.</em></p>
</section>
<section id="serviços-clínicos-e-cirúrgicos" class="level3">
<h3 class="anchored" data-anchor-id="serviços-clínicos-e-cirúrgicos">7.1 Serviços clínicos e cirúrgicos</h3>
<p><strong>7.1.1 a 7.1.28 — Lista das especialidades.</strong></p>
<p><em>ENUNCIADO A LER: “Vou ler uma lista de especialidades clínicas. Para cada uma, diga-me se esta unidade tem consulta regular nessa especialidade — isto é, com dia ou dias marcados na semana — prestada por um profissional habilitado. Não considerar atendimentos ocasionais nem consultas suspensas há mais de 3 meses.”</em></p>
<blockquote class="blockquote">
<p>Para cada especialidade: 1 Sim, consulta regular · 2 Não</p>
</blockquote>
<p><em>Indicador: <strong>[MS]</strong> — a lista de 28 especialidades é contributo próprio do Mapa Sanitário. O enunciado acima fixa o critério (“consulta regular, com dia marcado, por profissional habilitado”) que hoje fica ao critério de quem responde.</em></p>
<p><strong>7.1.29</strong> <strong>Esta unidade realiza algum procedimento cirúrgico, de pequena ou de grande cirurgia?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>SE 2, PASSAR A 7.2.</em></p>
</blockquote>
<p><em>Indicador do HHFA: <strong>1.3.2.7.1</strong>.</em></p>
<p><strong>7.1.29.1</strong> <strong>Esta unidade realiza procedimentos de pequena cirurgia, isto é, procedimentos efectuados sob anestesia local, sem necessidade de bloco operatório?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>1.3.2.7.2</strong></em></p>
</blockquote>
<p><strong>7.1.29.2</strong> <strong>Esta unidade realiza procedimentos de grande cirurgia, isto é, procedimentos efectuados sob anestesia geral ou regional, em bloco operatório?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>1.3.2.7.3</strong></em></p>
</blockquote>
<p><strong>7.1.29.3</strong> <strong>Esta unidade realiza circuncisão masculina médica voluntária?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>1.3.2.7.4</strong></em></p>
</blockquote>
<p><strong>7.1.29.4</strong> <strong>Dos três procedimentos seguintes, quais foram realizados nesta unidade nos últimos 12 meses?</strong><br>
<em>LER OS TRÊS. MARCAR CADA UM.</em></p>
<blockquote class="blockquote">
<ol type="a">
<li>Cesariana: 1 Sim · 2 Não</li>
<li>Laparotomia: 1 Sim · 2 Não</li>
<li>Tratamento de fractura exposta: 1 Sim · 2 Não</li>
</ol>
</blockquote>
<p><em>Indicadores do HHFA: <strong>1.3.2.7.5</strong> (algum dos três) e <strong>1.3.2.7.6</strong> (os três).</em></p>
<p><strong>7.1.30 a 7.1.34</strong> <strong>Esta unidade realiza procedimentos cirúrgicos em alguma das seguintes áreas de especialidade?</strong></p>
<blockquote class="blockquote">
<p>Cirurgia pediátrica · Cirurgia maxilofacial · Cirurgia vascular · Neurocirurgia · Cirurgia plástica — <em>1 Sim · 2 Não, para cada</em></p>
</blockquote>
<p><em>Indicador do HHFA: <strong>1.3.2.7.7</strong>.</em></p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>Sobre os procedimentos-marcadores.</strong> Cesariana, laparotomia e tratamento de fractura exposta são os três procedimentos que a cirurgia global usa como marcadores da capacidade cirúrgica essencial — cobrem obstetrícia, abdómen e trauma. Três perguntas com período de referência declarado dizem mais sobre a capacidade cirúrgica real do que a lista de especialidades, e as duas informações não se excluem.</p>
</div>
</section>
<section id="serviços-de-apoio-tecnologias-procedimentos-e-exames" class="level3">
<h3 class="anchored" data-anchor-id="serviços-de-apoio-tecnologias-procedimentos-e-exames">7.2 Serviços de apoio — tecnologias, procedimentos e exames</h3>
<p>O maior ganho do formulário. Onde a Ficha tem catorze caixas de sim ou não, produzem-se trinta e seis indicadores, <strong>todos em modo autorreferido</strong>, porque se pergunta o que a unidade oferece e não o que está na prateleira.</p>
<section id="a-imagiologia" class="level4">
<h4 class="anchored" data-anchor-id="a-imagiologia">7.2.A Imagiologia</h4>
<p><em>ENUNCIADO A LER: “Vou perguntar por alguns exames de imagem. Para cada um, diga-me se é realizado nesta unidade, com equipamento desta unidade. Não considerar exames que os doentes fazem noutro local por iniciativa própria.”</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Nº</th>
<th>Exame</th>
<th>Resposta</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.2.A.1</td>
<td>Ecografia</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.1.1</strong></td>
</tr>
<tr class="even">
<td>7.2.A.2</td>
<td>Radiografia (raios X)</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.1.2</strong></td>
</tr>
<tr class="odd">
<td>7.2.A.3</td>
<td>Mamografia</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.1.3</strong></td>
</tr>
<tr class="even">
<td>7.2.A.4</td>
<td>Tomografia computorizada</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.1.4</strong></td>
</tr>
<tr class="odd">
<td>7.2.A.5</td>
<td>Ressonância magnética</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.1.5</strong></td>
</tr>
<tr class="even">
<td>7.2.A.6</td>
<td>Angiografia ou cateterismo</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.1.6</strong></td>
</tr>
<tr class="odd">
<td>7.2.A.7</td>
<td>Fluoroscopia</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.1.7</strong></td>
</tr>
<tr class="even">
<td>7.2.A.8</td>
<td>Medicina nuclear</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.1.8</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="b-procedimentos-e-tecnologias" class="level4">
<h4 class="anchored" data-anchor-id="b-procedimentos-e-tecnologias">7.2.B Procedimentos e tecnologias</h4>
<p><em>ENUNCIADO A LER: “Vou perguntar por alguns procedimentos. Para cada um, diga-me se esta unidade o realizou pelo menos uma vez nos últimos 3 meses. Não considerar procedimentos que a unidade poderia realizar mas que não realiza na prática.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Procedimento</th>
<th>Resposta</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.2.B.1</td>
<td>Desfibrilhação</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.2.1</strong></td>
</tr>
<tr class="even">
<td>7.2.B.2</td>
<td>Electrocardiograma</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.2.2</strong></td>
</tr>
<tr class="odd">
<td>7.2.B.3</td>
<td>Electroencefalograma</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.2.3</strong></td>
</tr>
<tr class="even">
<td>7.2.B.4</td>
<td>Incubadora para recém-nascidos</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.2.4</strong></td>
</tr>
<tr class="odd">
<td>7.2.B.5</td>
<td>Fototerapia para icterícia neonatal</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.2.5</strong></td>
</tr>
<tr class="even">
<td>7.2.B.6</td>
<td>Radioterapia</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.2.6</strong></td>
</tr>
<tr class="odd">
<td>7.2.B.7</td>
<td>Diálise renal</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.2.7</strong></td>
</tr>
<tr class="even">
<td>7.2.B.8</td>
<td>Ventilação mecânica</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.2.8</strong></td>
</tr>
<tr class="odd">
<td>7.2.B.9</td>
<td>Transfusão de sangue</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.2.9</strong>, <strong>3.1.4.1.4</strong></td>
</tr>
<tr class="even">
<td>7.2.B.10</td>
<td>Colonoscopia</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.2.10</strong></td>
</tr>
<tr class="odd">
<td>7.2.B.11</td>
<td>Administração de oxigénio a doentes</td>
<td>1 Sim · 2 Não</td>
<td><strong>1.3.3.2.11</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="c-exames-laboratoriais" class="level4">
<h4 class="anchored" data-anchor-id="c-exames-laboratoriais">7.2.C Exames laboratoriais</h4>
<div style="border-left:5px solid #1e8449;background:#eafaf1;padding:10px 14px;border-radius:5px;">
<p><strong>O caso do laboratório, resolvido.</strong> O Guião já exige, para marcar “1. Laboratório”, a realização no mínimo de gota espessa, hemoglobina ou hematócrito e análises simples de fezes e urina — mas a Ficha guarda uma marcação única. Esta lista escreve essa definição, alarga-a, e acrescenta a distinção entre o exame feito aqui e o exame enviado para fora. <strong>Dezassete indicadores onde havia uma caixa, e nenhum exige observação.</strong></p>
</div>
<p><em>ENUNCIADO A LER: “Vou perguntar por exames laboratoriais. Para cada um, diga-me se é realizado nesta unidade, se a amostra é enviada para outro laboratório com o resultado a regressar a esta unidade, ou se não está disponível para os doentes desta unidade. Considere a situação habitual dos últimos 3 meses, e não uma falha pontual de reagente.”</em></p>
<blockquote class="blockquote">
<p><strong>1</strong> Realizado nesta unidade · <strong>2</strong> Amostra enviada para fora, com retorno do resultado · <strong>3</strong> Não disponível</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Exame</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.2.C.1</td>
<td>Microscopia geral</td>
<td><strong>1.3.3.3.1</strong></td>
</tr>
<tr class="even">
<td>7.2.C.2</td>
<td>Cultura e antibiograma</td>
<td><strong>1.3.3.3.2</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.3</td>
<td>Diagnóstico de malária — gota espessa ou teste rápido</td>
<td><strong>1.3.3.3.3</strong></td>
</tr>
<tr class="even">
<td>7.2.C.4</td>
<td>Teste rápido de sífilis</td>
<td><strong>1.3.3.3.4</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.5</td>
<td>Teste de diagnóstico do VIH</td>
<td><strong>1.3.3.3.5</strong></td>
</tr>
<tr class="even">
<td>7.2.C.6</td>
<td>Teste de diagnóstico da tuberculose</td>
<td><strong>1.3.3.3.6</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.7</td>
<td>Teste de gravidez na urina</td>
<td><strong>1.3.3.3.7</strong></td>
</tr>
<tr class="even">
<td>7.2.C.8</td>
<td>Tira de urina — proteínas</td>
<td><strong>1.3.3.3.8</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.9</td>
<td>Tira de urina — glicose</td>
<td><strong>1.3.3.3.9</strong></td>
</tr>
<tr class="even">
<td>7.2.C.10</td>
<td>Tira de urina — corpos cetónicos</td>
<td><strong>1.3.3.3.10</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.11</td>
<td>Hemoglobina ou hematócrito</td>
<td><strong>1.3.3.3.11</strong></td>
</tr>
<tr class="even">
<td>7.2.C.12</td>
<td>Hemograma completo</td>
<td><strong>1.3.3.3.12</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.13</td>
<td>Tipagem e grupo sanguíneo</td>
<td><strong>1.3.3.3.13</strong></td>
</tr>
<tr class="even">
<td>7.2.C.14</td>
<td>Glicemia</td>
<td><strong>1.3.3.3.14</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.15</td>
<td>Ionograma</td>
<td><strong>1.3.3.3.15</strong></td>
</tr>
<tr class="even">
<td>7.2.C.16</td>
<td>Provas de função renal — ureia ou creatinina</td>
<td><strong>1.3.3.3.16</strong></td>
</tr>
<tr class="odd">
<td>7.2.C.17</td>
<td>Provas de função hepática — transaminases ou bilirrubina</td>
<td><strong>1.3.3.3.17</strong></td>
</tr>
</tbody>
</table>
<p><em>Os indicadores do HHFA contam apenas a opção 1 (realizado nesta unidade). A opção 2 é informação adicional, útil para o planeamento da rede laboratorial.</em></p>
</section>
<section id="d-outros-serviços-de-apoio" class="level4">
<h4 class="anchored" data-anchor-id="d-outros-serviços-de-apoio">7.2.D Outros serviços de apoio</h4>
<p><strong>7.2.6</strong> <strong>Esta unidade tem um serviço, unidade ou secção de anatomia patológica, distinto do laboratório de análises clínicas?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>[MS]</strong></em></p>
</blockquote>
<p><strong>7.2.8</strong> <strong>Esta unidade presta serviços de reabilitação — fisioterapia, terapia ocupacional, terapia da fala ou reabilitação física?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>1.3.2.10.1</strong></em></p>
</blockquote>
<p><strong>7.2.9</strong> <strong>Esta unidade tem bloco operatório?</strong> Se sim, quantos blocos operatórios em condições de utilização?</p>
<blockquote class="blockquote">
<p>1 Sim, |__| blocos · 2 Não — <em>Indicador: <strong>[MS]</strong> para a contagem</em></p>
</blockquote>
<p><strong>7.2.10</strong> <strong>Esta unidade tem farmácia ou depósito de medicamentos, com responsável designado, que dispensa medicamentos aos doentes?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Ver nota final sobre este quesito.</em></p>
</blockquote>
<p><strong>7.2.15</strong> <strong>Esta unidade presta cuidados paliativos — cuidados destinados a aliviar o sofrimento de doentes com doença avançada, incluindo controlo da dor?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>1.3.2.9.1</strong></em></p>
</blockquote>
</section>
<section id="e-serviços-de-urgência" class="level4">
<h4 class="anchored" data-anchor-id="e-serviços-de-urgência">7.2.E Serviços de urgência</h4>
<p><strong>7.2.12.1</strong> <strong>Esta unidade atende doentes em situação de urgência que chegam sem marcação, como primeira porta de entrada no sistema?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>SE 2, PASSAR A 7.3. Indicadores: <strong>3.5.1.1.1</strong>, <strong>1.3.2.8.1</strong></em></p>
</blockquote>
<p><strong>7.2.12.2</strong> <strong>Existe nesta unidade um banco de urgência dedicado — um espaço próprio para urgências, distinto da consulta externa — aberto 24 horas por dia, todos os dias?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicadores: <strong>3.5.1.1.2</strong>, <strong>1.3.2.8.2</strong></em></p>
</blockquote>
<p><strong>7.2.12.3</strong> <strong>Há pessoal médico e de enfermagem presente no banco de urgência 24 horas por dia, todos os dias?</strong><br>
<em>CONSIDERAR PRESENÇA FÍSICA NA UNIDADE, E NÃO DISPONIBILIDADE POR CHAMADA.</em></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não · 98 Não sabe — <em>Indicador: <strong>3.5.1.1.3</strong></em></p>
</blockquote>
<p><strong>7.2.12.4</strong> <strong>O banco de urgência tem acesso rápido a transporte de emergência para referir doentes, 24 horas por dia?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>3.5.1.1.4</strong></em></p>
</blockquote>
<p><strong>7.2.12.5</strong> <strong>A farmácia desta unidade dispensa medicamentos 24 horas por dia, todos os dias?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>3.5.1.1.5</strong></em></p>
</blockquote>
<p><strong>7.2.12.6</strong> <strong>Os serviços de radiologia desta unidade estão disponíveis 24 horas por dia, todos os dias?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não · 97 Não tem radiologia — <em>Indicador: <strong>3.5.1.1.6</strong></em></p>
</blockquote>
<p><strong>7.2.12.7</strong> <strong>Os serviços de laboratório desta unidade estão disponíveis 24 horas por dia, todos os dias?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não · 97 Não tem laboratório — <em>Indicador: <strong>3.5.1.1.7</strong></em></p>
</blockquote>
<p><strong>7.2.12.8</strong> <strong>Quando um doente é transportado para outra unidade em situação de urgência, é habitualmente acompanhado por um médico ou enfermeiro desta unidade?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não · 98 Não sabe — <em>Indicador: <strong>3.5.1.1.8</strong></em></p>
</blockquote>
<p><strong>7.2.12.9</strong> <strong>O banco de urgência tem pessoal próprio, afecto exclusivamente a este serviço, que não roda por outros serviços da unidade?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>3.5.1.1.9</strong></em></p>
</blockquote>
<p><strong>7.2.12.10</strong> <strong>Existe no banco de urgência um sistema formal de triagem, com critérios escritos para classificar a gravidade dos doentes à chegada?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>3.5.1.1.10</strong></em></p>
</blockquote>
</section>
</section>
<section id="saúde-pública-prevenção-e-programas" class="level3">
<h3 class="anchored" data-anchor-id="saúde-pública-prevenção-e-programas">7.3 Saúde pública, prevenção e programas</h3>
<p>Cada caixa da Ficha atual passa a ser uma pergunta-porta formulada por extenso, seguida de uma lista de componentes com enunciado próprio.</p>
<section id="vacinação" class="level4">
<h4 class="anchored" data-anchor-id="vacinação">7.3.1 Vacinação</h4>
<p><strong>PORTA:</strong> <strong>Esta unidade administra vacinas do Programa Alargado de Vacinação, de forma regular?</strong><br>
<em>NÃO CONSIDERAR CAMPANHAS PONTUAIS REALIZADAS POR EQUIPAS EXTERNAS.</em></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>SE 2, PASSAR A 7.3.2. Indicadores: <strong>3.2.1.1.1</strong>, <strong>1.3.2.2.1</strong></em></p>
</blockquote>
<p><strong>7.3.1.a</strong> <strong>Com que frequência se administram as vacinas de rotina às crianças nesta unidade?</strong></p>
<blockquote class="blockquote">
<p>1 Todos os dias de atendimento · 2 Uma ou mais vezes por semana · 3 Mensalmente ou trimestralmente · 4 Apenas em campanhas<br>
<em>Indicadores: <strong>3.2.1.1.6</strong>, <strong>3.2.1.1.7</strong>, <strong>3.2.1.1.8</strong>.</em></p>
</blockquote>
<p><strong>7.3.1.b a 7.3.1.e</strong> <em>ENUNCIADO A LER: “Vou ler a lista das vacinas do calendário nacional. Para cada uma, diga-me se esta unidade a administra habitualmente ao grupo etário indicado. Considere a prática habitual, e não uma rutura pontual de stock.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Grupo</th>
<th>Vacinas</th>
<th>Indicadores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ao nascimento</td>
<td>BCG · Poliomielite oral · Hepatite B</td>
<td><strong>3.2.1.1.2</strong>, <strong>.9</strong>, <strong>.10</strong>, <strong>.11</strong></td>
</tr>
<tr class="even">
<td>Lactentes (&lt; 1 ano)</td>
<td>BCG · VOP · DPT-HepB-Hib · Rotavírus · VIP</td>
<td><strong>3.2.1.1.3</strong>, <strong>.12</strong> a <strong>.16</strong></td>
</tr>
<tr class="odd">
<td>Crianças (1 a 5 anos)</td>
<td>Sarampo · Pneumocócica · COVID-19</td>
<td><strong>3.2.1.1.4</strong>, <strong>.17</strong>, <strong>.18</strong>, <strong>.19</strong></td>
</tr>
<tr class="even">
<td>Adolescentes e adultos</td>
<td>Tétano · HPV · Gripe · COVID-19 · Pneumocócica · Hepatite B</td>
<td><strong>3.2.1.1.5</strong>, <strong>.20</strong> a <strong>.25</strong></td>
</tr>
</tbody>
</table>
<p><em>A lista carece de validação face ao calendário nacional de vacinação em vigor.</em></p>
</section>
<section id="a-7.3.5-saúde-da-criança-e-nutrição" class="level4">
<h4 class="anchored" data-anchor-id="a-7.3.5-saúde-da-criança-e-nutrição">7.3.2 a 7.3.5 Saúde da criança e nutrição</h4>
<p><strong>PORTA:</strong> <strong>Esta unidade presta cuidados preventivos ou curativos a crianças menores de 5 anos?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>SE 2, PASSAR A 7.3.6. Indicadores: <strong>3.1.8.1.1</strong>, <strong>1.3.2.1.1</strong></em></p>
</blockquote>
<p><em>ENUNCIADO A LER: “Vou perguntar por serviços prestados a crianças menores de 5 anos. Para cada um, diga-me se é prestado habitualmente nesta unidade.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Serviço</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.5</td>
<td>Vigilância do crescimento de rotina, com pesagem e registo no cartão da criança</td>
<td><strong>3.1.8.1.2</strong></td>
</tr>
<tr class="even">
<td>7.3.4</td>
<td>Diagnóstico ou tratamento da desnutrição</td>
<td><strong>3.1.8.1.3</strong></td>
</tr>
<tr class="odd">
<td>7.3.4.2</td>
<td>Manejo em ambulatório da desnutrição aguda grave sem complicações, com alimento terapêutico pronto a usar</td>
<td><strong>3.1.8.1.4</strong></td>
</tr>
<tr class="even">
<td>7.3.4.3</td>
<td>Manejo em ambulatório de desnutrição aguda moderada ou outras categorias</td>
<td><strong>3.1.8.1.5</strong></td>
</tr>
<tr class="odd">
<td>7.3.4.4</td>
<td>Manejo em internamento da desnutrição grave com complicações</td>
<td><strong>3.1.8.1.6</strong></td>
</tr>
<tr class="even">
<td>7.3.2</td>
<td>Administração de rotina de vitamina A</td>
<td><strong>3.1.8.1.7</strong></td>
</tr>
<tr class="odd">
<td>7.3.2.1</td>
<td>Diagnóstico e tratamento da anemia com suplementação de ferro</td>
<td><strong>3.1.8.1.8</strong></td>
</tr>
<tr class="even">
<td>7.3.4.1</td>
<td>Diagnóstico e tratamento da diarreia com sais de reidratação oral e zinco</td>
<td><strong>3.1.8.1.9</strong></td>
</tr>
<tr class="odd">
<td>7.3.2.2</td>
<td>Diagnóstico e tratamento de primeira linha da pneumonia</td>
<td><strong>3.1.8.1.10</strong></td>
</tr>
<tr class="even">
<td>7.3.2.3</td>
<td>Diagnóstico da malária com teste laboratorial e respectivo tratamento</td>
<td><strong>3.1.8.1.11</strong></td>
</tr>
<tr class="odd">
<td>7.3.14</td>
<td>Entrega de rede mosquiteira tratada ou de senha para a levantar</td>
<td><strong>3.1.8.1.12</strong></td>
</tr>
<tr class="even">
<td>7.3.17</td>
<td>Articulação regular com agentes comunitários de saúde para o seguimento de crianças</td>
<td><strong>3.1.8.1.13</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="consulta-pré-natal" class="level4">
<h4 class="anchored" data-anchor-id="consulta-pré-natal">7.3.6 Consulta pré-natal</h4>
<p><strong>PORTA:</strong> <strong>Esta unidade presta consultas pré-natais a mulheres grávidas?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>SE 2, PASSAR A 7.3.7. Indicadores: <strong>3.1.2.1.1</strong>, <strong>1.3.2.1.4</strong></em></p>
</blockquote>
<p><em>ENUNCIADO A LER: “Vou ler uma lista de acções que podem fazer parte da consulta pré-natal. Para cada uma, diga-me se é feita habitualmente nesta unidade, às mulheres que aqui fazem o pré-natal.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Componente</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.6.a</td>
<td>Prescrição ou entrega de suplemento de ferro</td>
<td><strong>3.1.2.1.2</strong></td>
</tr>
<tr class="even">
<td>7.3.6.b</td>
<td>Prescrição ou entrega de ácido fólico</td>
<td><strong>3.1.2.1.3</strong></td>
</tr>
<tr class="odd">
<td>7.3.6.c</td>
<td>Administração da vacina antitetânica</td>
<td><strong>3.1.2.1.4</strong></td>
</tr>
<tr class="even">
<td>7.3.6.d</td>
<td>Medição da tensão arterial em todas as consultas, para deteção de perturbações hipertensivas da gravidez</td>
<td><strong>3.1.2.1.5</strong></td>
</tr>
<tr class="odd">
<td>7.3.6.e</td>
<td>Pesquisa de proteínas na urina, de rotina</td>
<td><strong>3.1.2.1.6</strong></td>
</tr>
<tr class="even">
<td>7.3.6.f</td>
<td>Administração do tratamento intermitente preventivo da malária</td>
<td><strong>3.1.2.1.9</strong></td>
</tr>
<tr class="odd">
<td>7.3.6.g</td>
<td>Oferta de teste de VIH a todas as grávidas</td>
<td><strong>3.1.2.1.10</strong>, <strong>1.3.2.1.5</strong></td>
</tr>
<tr class="even">
<td>7.3.6.h</td>
<td>Entrega de rede mosquiteira tratada ou de senha para a levantar</td>
<td><strong>3.1.2.1.11</strong></td>
</tr>
<tr class="odd">
<td>7.3.6.i</td>
<td>Realização de teste de sífilis, de rotina</td>
<td><strong>3.1.2.1.12</strong></td>
</tr>
<tr class="even">
<td>7.3.6.j</td>
<td>Tratamento da sífilis nas grávidas com teste positivo</td>
<td><strong>3.1.2.1.13</strong></td>
</tr>
<tr class="odd">
<td>7.3.6.k</td>
<td>Diagnóstico e tratamento de outras infecções sexualmente transmissíveis</td>
<td><strong>3.1.2.1.14</strong></td>
</tr>
<tr class="even">
<td>7.3.6.l</td>
<td>Articulação com agentes comunitários para a captação e seguimento de grávidas</td>
<td><strong>3.1.2.1.16</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="partos-e-cuidados-obstétricos-de-emergência" class="level4">
<h4 class="anchored" data-anchor-id="partos-e-cuidados-obstétricos-de-emergência">7.3.7 Partos e cuidados obstétricos de emergência</h4>
<p><strong>PORTA:</strong> <strong>Esta unidade assiste partos?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>SE 2, PASSAR A 7.3.8. Indicadores: <strong>3.1.3.1.1</strong>, <strong>1.3.2.1.6</strong></em></p>
</blockquote>
<p><strong>7.3.7.0</strong> <strong>Há assistência ao parto por profissional qualificado — médico, enfermeiro ou parteira com formação — disponível nesta unidade 24 horas por dia, todos os dias da semana?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>3.1.3.1.2</strong></em></p>
</blockquote>
<p><em>ENUNCIADO A LER: “Vou ler uma lista de procedimentos e práticas relacionados com o parto. Para cada um, diga-me se foi realizado nesta unidade pelo menos uma vez nos últimos 3 meses. Se o procedimento é praticado aqui mas não houve nenhum caso nos últimos 3 meses, responda ‘sim, mas sem casos recentes’.”</em></p>
<blockquote class="blockquote">
<p><strong>1</strong> Sim, realizado nos últimos 3 meses · <strong>2</strong> Sim, praticado aqui, mas sem casos nos últimos 3 meses · <strong>3</strong> Não é realizado nesta unidade</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Procedimento</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.7.a</td>
<td>Administração de antibiótico por via parenteral à mãe</td>
<td><strong>3.1.3.2.1</strong></td>
</tr>
<tr class="even">
<td>7.3.7.b</td>
<td>Administração de ocitócico por via parenteral para tratamento da hemorragia pós-parto</td>
<td><strong>3.1.3.2.2</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.c</td>
<td>Administração de sulfato de magnésio por via parenteral para pré-eclâmpsia ou eclâmpsia</td>
<td><strong>3.1.3.2.3</strong></td>
</tr>
<tr class="even">
<td>7.3.7.d</td>
<td>Parto vaginal assistido com ventosa ou fórceps</td>
<td><strong>3.1.3.2.4</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.e</td>
<td>Remoção manual da placenta</td>
<td><strong>3.1.3.2.5</strong></td>
</tr>
<tr class="even">
<td>7.3.7.f</td>
<td>Remoção de restos ovulares, por curetagem ou aspiração manual intrauterina</td>
<td><strong>3.1.3.2.6</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.g</td>
<td>Reanimação do recém-nascido com insuflador e máscara</td>
<td><strong>3.1.3.2.7</strong></td>
</tr>
<tr class="even">
<td>7.3.7.h</td>
<td>Administração de antibiótico na rotura prematura de membranas</td>
<td><strong>3.1.3.2.8</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.i</td>
<td>Administração de corticosteroide no trabalho de parto pré-termo</td>
<td><strong>3.1.3.2.9</strong></td>
</tr>
<tr class="even">
<td>7.3.7.j</td>
<td>Método canguru para recém-nascidos prematuros ou de baixo peso</td>
<td><strong>3.1.3.2.10</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.k</td>
<td>Administração de antibiótico injectável para sépsis neonatal</td>
<td><strong>3.1.3.2.11</strong></td>
</tr>
<tr class="even">
<td>7.3.7.l</td>
<td>Administração de ocitocina para prevenção da hemorragia pós-parto</td>
<td><strong>3.1.3.2.12</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.m</td>
<td>Vigilância do trabalho de parto com partograma</td>
<td><strong>3.1.3.2.13</strong></td>
</tr>
<tr class="even">
<td>7.3.7.n</td>
<td>Início da amamentação na primeira hora de vida</td>
<td><strong>3.1.3.2.14</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.o</td>
<td>Cuidados higiénicos do cordão umbilical</td>
<td><strong>3.1.3.2.15</strong></td>
</tr>
<tr class="even">
<td>7.3.7.p</td>
<td>Secagem do recém-nascido e contacto pele a pele imediato</td>
<td><strong>3.1.3.2.16</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.q</td>
<td>Alojamento conjunto da mãe e do recém-nascido</td>
<td><strong>3.1.3.2.17</strong></td>
</tr>
<tr class="even">
<td>7.3.7.r</td>
<td>Clampagem tardia do cordão umbilical</td>
<td><strong>3.1.3.2.18</strong></td>
</tr>
<tr class="odd">
<td>7.3.7.s</td>
<td>Cesariana</td>
<td><strong>3.1.4.1.3</strong></td>
</tr>
<tr class="even">
<td>7.3.7.t</td>
<td>Transfusão de sangue a mulheres em trabalho de parto ou no pós-parto</td>
<td><strong>3.1.4.1.4</strong></td>
</tr>
</tbody>
</table>
<p><strong>Calculados a partir das componentes, e já não declarados:</strong> <strong>3.1.3.1.3</strong> cuidados obstétricos de emergência básicos, <strong>3.1.3.1.4</strong> todas as 7 funções-sinal básicas, <strong>3.1.3.1.5</strong> e <strong>3.1.4.1.1</strong> cuidados completos, <strong>3.1.4.1.2</strong> todas as 9 funções-sinal, <strong>1.3.2.1.7</strong> e <strong>1.3.2.1.8</strong>, e os índices <strong>3.1.3.2.19 a 3.1.3.2.24</strong>.</p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>O ganho concreto, e a razão da terceira opção de resposta.</strong> Hoje, marcar CONU-B é um juízo de quem preenche a Ficha. Com estas vinte linhas, CONU-B e CONU-C passam a ser <strong>resultados calculados</strong>, e sabe-se <em>qual</em> função falta em cada unidade — a informação que permite agir. A opção 2, “praticado aqui mas sem casos recentes”, existe porque numa unidade de pequena dimensão pode passar-se um trimestre sem nenhuma remoção manual de placenta sem que isso signifique incapacidade. Sem essa opção, o respondente é forçado a escolher entre duas respostas erradas.</p>
</div>
</section>
<section id="consulta-pós-parto" class="level4">
<h4 class="anchored" data-anchor-id="consulta-pós-parto">7.3.8 Consulta pós-parto</h4>
<p><strong>PORTA:</strong> <strong>Esta unidade presta cuidados pós-parto à mãe, ao recém-nascido, ou a ambos, nas seis semanas seguintes ao parto?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicadores: <strong>3.1.6.1.1</strong>, <strong>1.3.2.1.12</strong></em></p>
</blockquote>
<p><em>ENUNCIADO A LER: “Para cada uma das acções seguintes, diga-me se é feita habitualmente na consulta pós-parto desta unidade.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Componente</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.8.a</td>
<td>Aconselhamento em planeamento familiar</td>
<td><strong>3.1.6.1.2</strong></td>
</tr>
<tr class="even">
<td>7.3.8.b</td>
<td>Aconselhamento sobre sinais de perigo no recém-nascido</td>
<td><strong>3.1.6.1.3</strong></td>
</tr>
<tr class="odd">
<td>7.3.8.c</td>
<td>Aconselhamento sobre cuidados e higiene do cordão umbilical</td>
<td><strong>3.1.6.1.4</strong></td>
</tr>
<tr class="even">
<td>7.3.8.d</td>
<td>Aconselhamento sobre nutrição e alimentação da criança</td>
<td><strong>3.1.6.1.5</strong></td>
</tr>
<tr class="odd">
<td>7.3.8.e</td>
<td>Aconselhamento para amamentação exclusiva até aos 6 meses</td>
<td><strong>3.1.6.1.6</strong></td>
</tr>
<tr class="even">
<td>7.3.8.f</td>
<td>Aconselhamento sobre o calendário de vacinação da criança</td>
<td><strong>3.1.6.1.7</strong></td>
</tr>
<tr class="odd">
<td>7.3.8.g</td>
<td>Administração da vacina BCG ao recém-nascido</td>
<td><strong>3.1.6.1.8</strong></td>
</tr>
<tr class="even">
<td>7.3.8.h</td>
<td>Administração da vacina antipólio ao recém-nascido</td>
<td><strong>3.1.6.1.9</strong></td>
</tr>
<tr class="odd">
<td>7.3.8.i</td>
<td>Entrega de rede mosquiteira tratada para o lactente</td>
<td><strong>3.1.6.1.10</strong></td>
</tr>
<tr class="even">
<td>7.3.8.j</td>
<td>Articulação com agentes comunitários para o seguimento do recém-nascido</td>
<td><strong>3.1.6.1.11</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="planeamento-familiar" class="level4">
<h4 class="anchored" data-anchor-id="planeamento-familiar">7.3.9 Planeamento familiar</h4>
<p><strong>PORTA:</strong> <strong>Esta unidade presta serviços de planeamento familiar — aconselhamento, prescrição ou fornecimento de métodos contraceptivos?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicadores: <strong>3.1.1.1.1</strong>, <strong>1.3.2.1.3</strong></em></p>
</blockquote>
<p><em>ENUNCIADO A LER: “Vou ler uma lista de métodos contraceptivos. Para cada um, diga-me se esta unidade o fornece ou o coloca habitualmente. Considere a prática habitual, e não uma rutura pontual de stock.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Método</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.9.a</td>
<td>Pílula contraceptiva combinada</td>
<td><strong>3.1.1.1.3</strong></td>
</tr>
<tr class="even">
<td>7.3.9.b</td>
<td>Pílula só de progestagénio</td>
<td><strong>3.1.1.1.4</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.c</td>
<td>Contraceptivo injectável combinado</td>
<td><strong>3.1.1.1.5</strong></td>
</tr>
<tr class="even">
<td>7.3.9.d</td>
<td>Contraceptivo injectável só de progestagénio</td>
<td><strong>3.1.1.1.6</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.e</td>
<td>Preservativo masculino</td>
<td><strong>3.1.1.1.7</strong></td>
</tr>
<tr class="even">
<td>7.3.9.f</td>
<td>Preservativo feminino</td>
<td><strong>3.1.1.1.8</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.g</td>
<td>Dispositivo intrauterino</td>
<td><strong>3.1.1.1.9</strong></td>
</tr>
<tr class="even">
<td>7.3.9.h</td>
<td>Implante subcutâneo</td>
<td><strong>3.1.1.1.10</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.i</td>
<td>Contracepção de emergência</td>
<td><strong>3.1.1.1.11</strong></td>
</tr>
<tr class="even">
<td>7.3.9.j</td>
<td>Esterilização masculina (vasectomia)</td>
<td><strong>3.1.1.1.12</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.k</td>
<td>Esterilização feminina (laqueação de trompas)</td>
<td><strong>3.1.1.1.13</strong></td>
</tr>
<tr class="even">
<td>7.3.9.l</td>
<td>Colar do ciclo, para o método dos dias fixos</td>
<td><strong>3.1.1.1.14</strong></td>
</tr>
<tr class="odd">
<td>7.3.9.m</td>
<td>Articulação com agentes comunitários para distribuição de métodos</td>
<td><strong>3.1.1.1.15</strong></td>
</tr>
</tbody>
</table>
<p><strong>Calculado:</strong> <strong>3.1.1.1.2</strong> oferta de pelo menos um método moderno de contracepção.</p>
</section>
<section id="a-7.3.12-vih" class="level4">
<h4 class="anchored" data-anchor-id="a-7.3.12-vih">7.3.10 a 7.3.12 VIH</h4>
<p><strong>PORTA A:</strong> <strong>Esta unidade realiza testes de VIH com aconselhamento, a pedido ou por indicação clínica?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicadores: <strong>3.2.4.1.1</strong>, <strong>1.3.2.3.3</strong></em></p>
</blockquote>
<blockquote class="blockquote">
<p>7.3.10.a Testagem de adolescentes e adultos (15 anos ou mais) — <strong>3.2.4.1.2</strong><br>
7.3.10.b Testagem de crianças de 5 a 14 anos — <strong>3.2.4.1.3</strong><br>
7.3.10.c Testagem de crianças menores de 5 anos — <strong>3.2.4.1.4</strong></p>
</blockquote>
<p><strong>PORTA B:</strong> <strong>Esta unidade fornece tratamento antirretroviral ou faz o seguimento de doentes já em tratamento antirretroviral?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicadores: <strong>3.2.5.1.1</strong>, <strong>1.3.2.3.5</strong></em></p>
</blockquote>
<blockquote class="blockquote">
<p>7.3.12.a Tratamento antirretroviral a adultos e adolescentes — <strong>3.2.5.1.2</strong><br>
7.3.11.a Tratamento antirretroviral a crianças de 5 a 14 anos — <strong>3.2.5.1.3</strong><br>
7.3.11.b Tratamento antirretroviral a crianças menores de 5 anos — <strong>3.2.5.1.4</strong>, <strong>1.3.2.3.6</strong><br>
7.3.12.b Dispensa ou prescrição de medicamentos antirretrovirais — <strong>3.2.5.1.5</strong><br>
7.3.12.c Consultas de seguimento clínico de doentes em tratamento — <strong>3.2.5.1.6</strong><br>
7.3.12.d Aconselhamento e seguimento da adesão ao tratamento — <strong>3.2.5.1.7</strong></p>
</blockquote>
</section>
<section id="tuberculose" class="level4">
<h4 class="anchored" data-anchor-id="tuberculose">7.3.13 Tuberculose</h4>
<p><strong>PORTA:</strong> <strong>Esta unidade presta algum serviço relacionado com a tuberculose — diagnóstico, tratamento ou seguimento de doentes?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicadores: <strong>3.2.3.1.1</strong>, <strong>1.3.2.3.7</strong></em></p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Serviço</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.13.a</td>
<td>Diagnóstico ou tratamento de tuberculose resistente aos medicamentos</td>
<td><strong>3.2.3.1.2</strong></td>
</tr>
<tr class="even">
<td>7.3.13.b</td>
<td>Realização de testes de diagnóstico da tuberculose</td>
<td><strong>3.2.3.1.3</strong>, <strong>1.3.2.3.8</strong></td>
</tr>
<tr class="odd">
<td>7.3.13.c</td>
<td>Consultas de seguimento clínico e prescrição de medicamentos</td>
<td><strong>3.2.3.1.4</strong>, <strong>1.3.2.3.9</strong></td>
</tr>
<tr class="even">
<td>7.3.13.d</td>
<td>Reabastecimento de medicamentos nas consultas de seguimento</td>
<td><strong>3.2.3.1.5</strong></td>
</tr>
<tr class="odd">
<td>7.3.13.e</td>
<td>Apoio à adesão ao tratamento, incluindo tratamento sob observação directa</td>
<td><strong>3.2.3.1.6</strong></td>
</tr>
<tr class="even">
<td>7.3.13.f</td>
<td>Oferta de teste de VIH a todos os doentes com tuberculose</td>
<td><strong>3.2.3.1.7</strong></td>
</tr>
<tr class="odd">
<td>7.3.13.g</td>
<td>Articulação com agentes comunitários para busca de faltosos ou apoio ao tratamento</td>
<td><strong>3.2.3.1.8</strong></td>
</tr>
<tr class="even">
<td>7.3.13.h</td>
<td>Quarto ou enfermaria de internamento dedicado ao isolamento respiratório</td>
<td><strong>3.2.3.1.9</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="malária-bloco-novo" class="level4">
<h4 class="anchored" data-anchor-id="malária-bloco-novo">7.3.18 Malária — bloco novo</h4>
<p><strong>PORTA:</strong> <strong>Esta unidade faz diagnóstico ou tratamento da malária?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicadores: <strong>1.3.2.3.1</strong>, <strong>3.2.2.1.1</strong></em></p>
</blockquote>
<blockquote class="blockquote">
<p>7.3.18.a Diagnóstico por teste rápido — <strong>3.2.2.1.3</strong><br>
7.3.18.b Diagnóstico por microscopia (gota espessa) — <strong>3.2.2.1.4</strong><br>
7.3.18.c Tratamento iniciado apenas com base em sinais e sintomas, sem teste laboratorial — <strong>3.2.2.1.5</strong><br>
7.3.18.d Tratamento da malária com medicamentos antimaláricos — <strong>3.2.2.1.6</strong><br>
7.3.18.e Articulação com agentes comunitários para diagnóstico ou tratamento da malária — <strong>3.2.2.1.7</strong></p>
</blockquote>
</section>
<section id="doenças-não-transmissíveis-bloco-novo" class="level4">
<h4 class="anchored" data-anchor-id="doenças-não-transmissíveis-bloco-novo">7.3.19 Doenças não transmissíveis — bloco novo</h4>
<p><strong>PORTA:</strong> <strong>Esta unidade faz diagnóstico, tratamento ou seguimento de doentes com alguma doença crónica não transmissível?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não — <em>Indicador: <strong>1.3.2.4.1</strong></em></p>
</blockquote>
<p><em>ENUNCIADO A LER: “Vou ler uma lista de condições. Para cada uma, diga-me se esta unidade faz diagnóstico, tratamento ou seguimento regular de doentes com essa condição. Responda pelo que a unidade faz na prática, e não pela existência de uma consulta de especialidade.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Condição</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.3.19.a</td>
<td>Doenças cardiovasculares, incluindo hipertensão arterial</td>
<td><strong>1.3.2.4.2</strong></td>
</tr>
<tr class="even">
<td>7.3.19.b</td>
<td>Diabetes</td>
<td><strong>1.3.2.4.3</strong></td>
</tr>
<tr class="odd">
<td>7.3.19.c</td>
<td>Doença respiratória crónica — asma ou doença pulmonar obstrutiva crónica</td>
<td><strong>1.3.2.4.4</strong></td>
</tr>
<tr class="even">
<td>7.3.19.d</td>
<td>Cancro do colo do útero, incluindo rastreio</td>
<td><strong>1.3.2.4.6</strong></td>
</tr>
<tr class="odd">
<td>7.3.19.e</td>
<td>Cancro da mama, incluindo rastreio</td>
<td><strong>1.3.2.4.7</strong></td>
</tr>
<tr class="even">
<td>7.3.19.f</td>
<td>Perturbações mentais — depressão, ansiedade, psicose, uso de substâncias</td>
<td><strong>1.3.2.5.1</strong></td>
</tr>
<tr class="odd">
<td>7.3.19.g</td>
<td>Doenças neurológicas, incluindo epilepsia</td>
<td><strong>1.3.2.5.2</strong></td>
</tr>
</tbody>
</table>
<p><strong>Calculado:</strong> <strong>1.3.2.4.5</strong> oferta de algum serviço relacionado com cancro.</p>
<div style="border-left:5px solid #b7950b;background:#fdf6e3;padding:10px 14px;border-radius:5px;">
<p><strong>Porque a instrução final do enunciado é essencial.</strong> Sem ela, um respondente de um centro de saúde sem endocrinologista responde “não” à diabetes, mesmo que ali se diagnostique e trate diabetes todos os dias. A instrução “responda pelo que a unidade faz na prática, e não pela existência de uma consulta de especialidade” é o que separa esta pergunta da caixa “9. Endocrinologia” da Ficha atual — e é o que torna o dado útil para planear a descentralização do manejo das doenças crónicas.</p>
</div>
</section>
<section id="a-7.3.17-extensão-comunitária" class="level4">
<h4 class="anchored" data-anchor-id="a-7.3.17-extensão-comunitária">7.3.15 a 7.3.17 Extensão comunitária</h4>
<p><strong>7.3.15</strong> <strong>Nos últimos 12 meses, esta unidade organizou brigadas móveis — deslocações de equipas desta unidade a locais fora do recinto, para prestar cuidados?</strong></p>
<blockquote class="blockquote">
<p>1 Sim, regularmente · 2 Sim, ocasionalmente · 3 Não</p>
</blockquote>
<p><strong>7.3.16</strong> <strong>Nos últimos 12 meses, esta unidade organizou equipas avançadas — postos de atendimento temporários instalados fora do recinto?</strong></p>
<blockquote class="blockquote">
<p>1 Sim, regularmente · 2 Sim, ocasionalmente · 3 Não</p>
</blockquote>
<p><strong>7.3.17</strong> <strong>Existem agentes de desenvolvimento comunitário e sanitário que trabalham na área de abrangência desta unidade e com ela articulam?</strong> Se sim, quantos?</p>
<blockquote class="blockquote">
<p>1 Sim, |__|__| agentes · 2 Não · 98 Não sabe</p>
</blockquote>
<p><em>Indicador: <strong>[MS]</strong> — descrevem a extensão do serviço para fora das paredes da unidade, dimensão que o HHFA praticamente não cobre e que é contributo próprio do Mapa Sanitário.</em></p>
</section>
</section>
<section id="e-7.5-serviços-de-gestão-e-serviços-gerais" class="level3">
<h3 class="anchored" data-anchor-id="e-7.5-serviços-de-gestão-e-serviços-gerais">7.4 e 7.5 Serviços de gestão e serviços gerais</h3>
<p><strong>7.4.1 a 7.4.17</strong> <em>ENUNCIADO A LER: “Vou ler uma lista de serviços e órgãos de gestão. Para cada um, diga-me se existe nesta unidade e se esteve em funcionamento nos últimos 3 meses.”</em></p>
<blockquote class="blockquote">
<p>1 Existe e funcionou nos últimos 3 meses · 2 Existe mas não funcionou nos últimos 3 meses · 3 Não existe</p>
</blockquote>
<p><em>Indicador: <strong>[MS]</strong>. A escala de três pontos substitui a caixa de 0-1 e distingue o órgão constituído do órgão activo, sem acrescentar perguntas.</em></p>
<p><strong>7.5.7</strong> <strong>Esta unidade dispõe de um meio de comunicação com o exterior — telefone fixo, telemóvel ou rádio — pago ou fornecido pela própria unidade?</strong><br>
<em>NÃO CONSIDERAR TELEMÓVEIS PESSOAIS DOS PROFISSIONAIS.</em></p>
<blockquote class="blockquote">
<p>1 Sim, e está a funcionar · 2 Sim, mas está avariado · 3 Não, existem apenas telemóveis pessoais dos profissionais · 4 Não há qualquer meio de comunicação com o exterior</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.1.1.1.5</strong> (conta apenas a opção 1).</em></p>
<p><strong>7.5.7.1</strong> <strong>Esta unidade tem pelo menos um computador a funcionar?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não</p>
</blockquote>
<p><strong>7.5.7.2</strong> <strong>Há acesso a correio electrónico ou à internet nesta unidade hoje?</strong></p>
<blockquote class="blockquote">
<p>1 Sim, através de equipamento da unidade · 2 Sim, mas apenas através de equipamento pessoal dos profissionais · 3 Não há acesso</p>
</blockquote>
<p><strong>7.5.7.3</strong> <strong>O custo da ligação à internet é pago ou reembolsado pela gestão desta unidade?</strong></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não · 97 Não se aplica</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.1.1.1.6</strong> = 7.5.7.1 igual a 1 <strong>e</strong> 7.5.7.2 igual a 1 <strong>e</strong> 7.5.7.3 igual a 1.</em></p>
<p><strong>7.5.1</strong> <strong>Esta unidade tem acesso a uma ambulância ou a outro veículo em condições de funcionamento para o transporte de emergência de doentes — quer esteja estacionado nesta unidade, quer possa ser chamado de outro local?</strong></p>
<blockquote class="blockquote">
<p>1 Sim, ambulância · 2 Sim, outro tipo de veículo · 3 Não</p>
</blockquote>
<p><em>SE 3, PASSAR A 7.5.2.</em></p>
<p><strong>7.5.1.1</strong> <strong>Esse veículo está disponível hoje, em condições de funcionamento, com combustível e com motorista?</strong><br>
<em>SE O RESPONDENTE NÃO TIVER A CERTEZA, PEDIR QUE CONFIRME COM QUEM SAIBA.</em></p>
<blockquote class="blockquote">
<p>1 Sim · 2 Não · 98 Não sabe</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>2.1.1.1.7</strong> = 7.5.1 igual a 1 ou 2 <strong>e</strong> 7.5.1.1 igual a 1.</em></p>
<p><strong>7.5.2 a 7.5.18</strong> <em>ENUNCIADO A LER: “Vou ler uma lista de serviços gerais de apoio. Para cada um, diga-me se existe nesta unidade e se esteve em funcionamento nos últimos 3 meses.”</em></p>
<blockquote class="blockquote">
<p>Cozinha · Refeitório ou cantina · Lavandaria · Morgue · Higiene e limpeza · Manutenção · Segurança · Salão de actos · Biblioteca · Residência · Capela · Parqueamento · Ajardinamento · Videovigilância · Gabinete do utente<br>
1 Existe e funcionou nos últimos 3 meses · 2 Existe mas não funcionou · 3 Não existe</p>
</blockquote>
<p><strong>7.5.5.2</strong> <strong>Quantas gavetas mortuárias tem a morgue desta unidade?</strong> |__|__| · 97 Não tem morgue</p>
<hr>
</section>
</section>
<section id="secção-8-camas" class="level2">
<h2 class="anchored" data-anchor-id="secção-8-camas">SECÇÃO 8 — Camas</h2>
<p><em>ENUNCIADO A LER: “Vou perguntar pelo número de camas desta unidade. Conte apenas as camas que estão instaladas e disponíveis para receber doentes hoje. Não conte camas avariadas, guardadas em armazém, nem camas previstas mas ainda não instaladas.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Pergunta</th>
<th>Campo</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8.1.1</td>
<td>Camas de observação — onde o doente permanece algumas horas e não pernoita</td>
<td>|__|__|__|</td>
<td><strong>[MS]</strong> (excluídas por definição no HHFA)</td>
</tr>
<tr class="even">
<td>8.1.2</td>
<td>Camas de internamento de tamanho adulto</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.1.1</strong>; com 3.1 → <strong>1.1.1.1.3</strong></td>
</tr>
<tr class="odd">
<td>8.1.2.1</td>
<td>Camas de internamento de tamanho pediátrico</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.1.2</strong></td>
</tr>
<tr class="even">
<td>8.1.5</td>
<td>Berços para recém-nascidos</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.1.3</strong></td>
</tr>
<tr class="odd">
<td>8.1.6</td>
<td>Das camas contadas acima, quantas estão dedicadas à maternidade</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.1</strong>; com 3.1 → <strong>1.1.1.1.4</strong></td>
</tr>
<tr class="even">
<td>8.1.7</td>
<td>Quantas estão dedicadas à cirurgia</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.2</strong></td>
</tr>
<tr class="odd">
<td>8.1.8</td>
<td>Quantas estão dedicadas à psiquiatria</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.3</strong></td>
</tr>
<tr class="even">
<td>8.1.9</td>
<td>Quantas estão dedicadas ao banco de urgência</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.4</strong></td>
</tr>
<tr class="odd">
<td>8.1.10</td>
<td>Quantas são camas de cuidados intensivos de adulto</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.5</strong></td>
</tr>
<tr class="even">
<td>8.1.11</td>
<td>Quantas são camas de cuidados intensivos pediátricos</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.6</strong></td>
</tr>
<tr class="odd">
<td>8.1.12</td>
<td>Quantos são berços de cuidados intensivos neonatais</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.7</strong></td>
</tr>
<tr class="even">
<td>8.1.13</td>
<td>Quantas são camas de cuidados intermédios</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.8</strong></td>
</tr>
<tr class="odd">
<td>8.1.14</td>
<td>Quantas são camas de isolamento</td>
<td>|__|__|__|</td>
<td><strong>1.1.2.2.9</strong></td>
</tr>
<tr class="even">
<td>8.1.3</td>
<td>Marquesas de parto instaladas e utilizáveis</td>
<td>|__|__|</td>
<td><strong>[MS]</strong></td>
</tr>
<tr class="odd">
<td>8.1.4</td>
<td>Cadeiras de estomatologia instaladas e utilizáveis</td>
<td>|__|__|</td>
<td><strong>[MS]</strong></td>
</tr>
</tbody>
</table>
<p><em>VERIFICAÇÃO DE CONSISTÊNCIA: a soma de 8.1.6 a 8.1.14 não pode exceder a soma de 8.1.2 e 8.1.2.1.</em></p>
<hr>
</section>
<section id="secção-9-aparelhos" class="level2">
<h2 class="anchored" data-anchor-id="secção-9-aparelhos">SECÇÃO 9 — Aparelhos</h2>
<p><strong>Única secção que exige inquiridor com observação.</strong> Propõe-se que a contagem actual se mantenha no preenchimento autorreferido, e que as duas colunas de verificação sejam aplicadas apenas nas unidades visitadas. O mesmo formulário serve assim os dois modos.</p>
<p><em>ENUNCIADO A LER, APENAS EM VISITA: “Vou perguntar por alguns aparelhos que devem existir na área principal de atendimento desta unidade. Para cada um, peço que me mostre o aparelho e que me diga, quando for aplicável, se está a funcionar. Considere apenas os aparelhos disponíveis na área de atendimento, e não os guardados em armazém.”</em></p>
<blockquote class="blockquote">
<p><strong>Coluna A — disponibilidade:</strong> 1 Observado · 2 Referido, não visto · 3 Não tem<br>
<strong>Coluna B — funcionamento:</strong> 1 Sim, funciona · 2 Não funciona · 98 Não sabe</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Item</th>
<th>Indicador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9.1.4 ◆</td>
<td>Balança de adulto</td>
<td><strong>2.2.1.1.8</strong></td>
</tr>
<tr class="even">
<td>9.1.16 ◆</td>
<td>Balança de criança, com graduação de 250 g</td>
<td><strong>2.2.1.1.9</strong></td>
</tr>
<tr class="odd">
<td>9.1.3 ◆</td>
<td>Balança de bebé, com graduação de 100 g</td>
<td><strong>2.2.1.1.10</strong></td>
</tr>
<tr class="even">
<td>9.1.8 ◆</td>
<td>Aparelho de medir a tensão arterial, digital ou esfigmomanómetro manual</td>
<td><strong>2.2.1.1.3</strong></td>
</tr>
<tr class="odd">
<td>9.1.7 ◆</td>
<td>Estetoscópio clínico</td>
<td><strong>2.2.1.1.2</strong></td>
</tr>
<tr class="even">
<td>9.1.17 ◆</td>
<td>Termómetro</td>
<td><strong>2.2.1.1.1</strong></td>
</tr>
<tr class="odd">
<td>9.1.18 ◆</td>
<td>Oxímetro de pulso</td>
<td><strong>2.2.1.1.4</strong></td>
</tr>
<tr class="even">
<td>9.1.19 ◆</td>
<td>Foco de exame orientável para observar o doente (lanterna aceitável)</td>
<td><strong>2.2.1.1.5</strong></td>
</tr>
<tr class="odd">
<td>9.1.20 ◆</td>
<td>Otoscópio</td>
<td><strong>2.2.1.1.6</strong></td>
</tr>
<tr class="even">
<td>9.1.21 ◆</td>
<td>Oftalmoscópio</td>
<td><strong>2.2.1.1.7</strong></td>
</tr>
<tr class="odd">
<td>9.1.22 ◆</td>
<td>Fita métrica</td>
<td><strong>2.2.1.1.11</strong></td>
</tr>
<tr class="even">
<td>9.1.23 ◆</td>
<td>Craveira ou estadiómetro</td>
<td><strong>2.2.1.1.12</strong></td>
</tr>
</tbody>
</table>
<p><strong>Contagem mantida, com enunciado precisado.</strong> <em>“Para cada um dos aparelhos seguintes, indique quantas unidades existem nesta unidade sanitária e estavam em condições de utilização no último mês.”</em> — Esterilizador (estufa ou autoclave) · Mini-arca do PAV · Aparelho de raios X · Estetoscópio de Pinard · Ecógrafo de obstetrícia · Kit para exame vaginal com espéculo · Kit de evacuação uterina · Ressuscitador neonatal · Kit de parto instrumental · Kit de parto descartável · Kit de cesariana.</p>
<p><em>Indicador: <strong>[MS]</strong> para a contagem. <strong>Calculados com a lista completa da grelha:</strong> <strong>2.2.1.1.13</strong> e <strong>2.2.1.1.14</strong>.</em></p>
<hr>
</section>
<section id="secção-10-meios-de-transporte" class="level2">
<h2 class="anchored" data-anchor-id="secção-10-meios-de-transporte">SECÇÃO 10 — Meios de transporte</h2>
<p><em>ENUNCIADO A LER: “Vou perguntar pelos veículos afectos a esta unidade sanitária. Conte apenas os veículos que pertencem a esta unidade ou que estão permanentemente afectos a ela. Para cada tipo, indique quantos estão em condições de circular hoje e quantos estão imobilizados por avaria ou falta de documentação.”</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Nº</th>
<th>Tipo de veículo</th>
<th>Em condições de circular</th>
<th>Imobilizados</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10.1.1</td>
<td>Ambulância</td>
<td>|__|__|</td>
<td>|__|__|</td>
</tr>
<tr class="even">
<td>10.1.2</td>
<td>Viatura ligeira</td>
<td>|__|__|</td>
<td>|__|__|</td>
</tr>
<tr class="odd">
<td>10.1.3</td>
<td>Viatura todo-o-terreno</td>
<td>|__|__|</td>
<td>|__|__|</td>
</tr>
<tr class="even">
<td>10.1.4</td>
<td>Motorizada</td>
<td>|__|__|</td>
<td>|__|__|</td>
</tr>
<tr class="odd">
<td>10.1.5</td>
<td>Outro (especificar)</td>
<td>|__|__|</td>
<td>|__|__|</td>
</tr>
</tbody>
</table>
<p><em>Indicador: <strong>[MS]</strong> — informação que o HHFA não recolhe e que é essencial à gestão logística da rede.</em></p>
<hr>
</section>
<section id="secção-11-pessoal-afecto-à-unidade" class="level2">
<h2 class="anchored" data-anchor-id="secção-11-pessoal-afecto-à-unidade">SECÇÃO 11 — Pessoal afecto à unidade</h2>
<section id="secção-nova" class="level3">
<h3 class="anchored" data-anchor-id="secção-nova"><em>Secção nova</em></h3>
<div style="border-left:5px solid #1e8449;background:#eafaf1;padding:10px 14px;border-radius:5px;">
<p><strong>A secção que fecha a maior lacuna da Ficha, e a mais barata de todas.</strong> A informação sai do mapa de pessoal da unidade, não exige verificação física, e cruzada com a população adstrita da Secção 3 produz dezasseis densidades de profissionais por 10 000 habitantes.</p>
</div>
<p><strong>11.1</strong> <strong>Esta unidade dispõe de um quadro de pessoal aprovado, que indica o número autorizado de profissionais por qualificação?</strong><br>
<em>SE SIM, PEDIR PARA VER O DOCUMENTO.</em></p>
<blockquote class="blockquote">
<p>1 Sim, observado · 2 Sim, referido mas não visto · 3 Não dispõe</p>
</blockquote>
<p><em>Indicador do HHFA: <strong>1.2.1.1.1</strong>.</em></p>
<p><strong>11.2</strong> <em>ENUNCIADO A LER: “Vou ler uma lista de categorias profissionais. Para cada uma, diga-me quantas pessoas dessa categoria estão actualmente afectas a esta unidade sanitária, e quantas dessas são mulheres. Conte as pessoas afectas ao quadro desta unidade, incluindo as que estejam de férias ou de baixa, e não apenas as que estão presentes hoje. Não conte pessoal em visita nem pessoal voluntário, que são perguntados adiante.”</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Nº</th>
<th>Categoria profissional</th>
<th>Total</th>
<th>Mulheres</th>
<th>Indicadores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>11.2.a</td>
<td>Médicos generalistas</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.2</strong>, <strong>1.2.2.2.1</strong>, <strong>1.2.3.2.2</strong></td>
</tr>
<tr class="even">
<td>11.2.b</td>
<td>Médicos especialistas em medicina familiar</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.3</strong>, <strong>1.2.2.2.2</strong></td>
</tr>
<tr class="odd">
<td>11.2.c</td>
<td>Médicos especialistas — área médica</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.6</strong>, <strong>1.2.2.3.2</strong></td>
</tr>
<tr class="even">
<td>11.2.d</td>
<td>Médicos especialistas — pediatria</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.7</strong>, <strong>1.2.2.3.3</strong></td>
</tr>
<tr class="odd">
<td>11.2.e</td>
<td>Médicos especialistas — ginecologia e obstetrícia</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.8</strong>, <strong>1.2.2.3.4</strong></td>
</tr>
<tr class="even">
<td>11.2.f</td>
<td>Médicos especialistas — área cirúrgica</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.9</strong>, <strong>1.2.2.3.5</strong></td>
</tr>
<tr class="odd">
<td>11.2.g</td>
<td>Médicos especialistas — psiquiatria</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.2.10</strong>, <strong>1.2.2.3.6</strong></td>
</tr>
<tr class="even">
<td>11.2.h</td>
<td>Enfermeiros</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.3.2</strong>, <strong>1.2.2.1.3</strong></td>
</tr>
<tr class="odd">
<td>11.2.i</td>
<td>Parteiras</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.3.3</strong>, <strong>1.2.2.1.4</strong></td>
</tr>
<tr class="even">
<td>11.2.j</td>
<td>Enfermeiros-parteiros com dupla formação</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.3.4</strong></td>
</tr>
<tr class="odd">
<td>11.2.k</td>
<td>Técnicos de medicina</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.3.1</strong>, <strong>1.2.2.1.2</strong></td>
</tr>
<tr class="even">
<td>11.2.l</td>
<td>Estomatologistas</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.4.1</strong>, <strong>1.2.2.4.1</strong></td>
</tr>
<tr class="odd">
<td>11.2.m</td>
<td>Farmacêuticos</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.4.2</strong>, <strong>1.2.2.4.2</strong></td>
</tr>
<tr class="even">
<td>11.2.n</td>
<td>Nutricionistas</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.4.6</strong>, <strong>1.2.2.4.6</strong></td>
</tr>
<tr class="odd">
<td>11.2.o</td>
<td>Fisioterapeutas</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.4.4</strong>, <strong>1.2.2.4.4</strong></td>
</tr>
<tr class="even">
<td>11.2.p</td>
<td>Técnicos de laboratório</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.5.2</strong></td>
</tr>
<tr class="odd">
<td>11.2.q</td>
<td>Técnicos de imagiologia</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.5.1</strong></td>
</tr>
<tr class="even">
<td>11.2.r</td>
<td>Técnicos de farmácia</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.5.3</strong></td>
</tr>
<tr class="odd">
<td>11.2.s</td>
<td>Técnicos de estatística e registos clínicos</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.5.5</strong></td>
</tr>
<tr class="even">
<td>11.2.t</td>
<td>Outros profissionais de saúde</td>
<td>|__|__|__|</td>
<td>|__|__|__|</td>
<td><strong>1.2.1.4.9</strong>, <strong>1.2.1.5.6</strong></td>
</tr>
</tbody>
</table>
<p><em>VERIFICAÇÃO DE CONSISTÊNCIA: o número de mulheres não pode exceder o total, em nenhuma linha.</em></p>
<p><strong>11.3</strong> <strong>Com que frequência esta unidade recebe visitas de médicos especialistas que não estão afectos a ela?</strong><br>
<em>CONSIDERAR OS ÚLTIMOS 12 MESES.</em></p>
<blockquote class="blockquote">
<p>1 Nunca recebe · 2 Diária ou semanalmente · 3 Pelo menos uma vez por mês · 4 Pelo menos uma vez por trimestre · 5 Com menor frequência</p>
</blockquote>
<p><em>Indicadores do HHFA: <strong>1.2.3.3.1</strong> a <strong>1.2.3.3.4</strong>.</em></p>
<p><strong>11.4 a 11.7</strong> <em>ENUNCIADO A LER: “Para cada um dos cargos seguintes, diga-me se a pessoa que o ocupa tem formação específica em gestão — um curso, uma pós-graduação ou uma qualificação reconhecida em gestão de serviços de saúde ou em administração.”</em></p>
<blockquote class="blockquote">
<p>11.4 Director da unidade · 11.5 Administrador · 11.6 Director clínico · 11.7 Director de enfermagem<br>
1 Sim · 2 Não · 97 O cargo não existe nesta unidade · 98 Não sabe</p>
</blockquote>
<p><em>Indicadores do HHFA: <strong>1.2.3.4.1</strong> a <strong>1.2.3.4.4</strong>.</em></p>
<p><strong>11.8</strong> <strong>Esta unidade tem profissionais que trabalham em regime de voluntariado, sem vínculo remunerado?</strong> Se sim, de que categorias?</p>
<blockquote class="blockquote">
<p>11.8.a Médico generalista — <strong>1.2.3.5.1</strong><br>
11.8.b Médico especialista — <strong>1.2.3.5.2</strong><br>
11.8.c Enfermeiro ou parteira — <strong>1.2.3.5.3</strong></p>
</blockquote>
<p><strong>Calculados:</strong> <strong>1.2.1.2.1</strong> total de médicos, <strong>1.2.1.2.4</strong> e <strong>1.2.1.2.5</strong>, <strong>1.2.3.1.1 a 1.2.3.1.7</strong> proporção de mulheres por categoria, <strong>1.2.3.2.1</strong> e <strong>1.2.3.2.3</strong> unidades com pelo menos um médico.</p>
<p><em>As categorias profissionais carecem de validação face à carreira dos profissionais de saúde de Angola.</em></p>
<hr>
</section>
</section>
<section id="indicadores-do-hhfa-capturados-por-esta-versão" class="level2" style="border-left:6px solid #1e8449;background:#eafaf1;padding:16px 18px;border-radius:6px;">
<h2 class="anchored" data-anchor-id="indicadores-do-hhfa-capturados-por-esta-versão">Indicadores do HHFA capturados por esta versão</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Dimensão</th>
<th>Subárea</th>
<th>Captados</th>
<th>Total na subárea</th>
<th>Modo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1. Disponibilidade geral</strong></td>
<td>1.1.1 Densidade de infraestrutura</td>
<td>4</td>
<td>4</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td></td>
<td>1.1.2 Camas</td>
<td>12</td>
<td>12</td>
<td>Autorreferido</td>
</tr>
<tr class="odd">
<td></td>
<td>1.2.1 Número de profissionais</td>
<td>26</td>
<td>31</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td></td>
<td>1.2.2 Densidade de profissionais</td>
<td>16</td>
<td>20</td>
<td>Autorreferido</td>
</tr>
<tr class="odd">
<td></td>
<td>1.2.3 Outros indicadores de pessoal</td>
<td>21</td>
<td>21</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td></td>
<td>1.3.1 Ambulatório e internamento</td>
<td>8</td>
<td>8</td>
<td>Autorreferido</td>
</tr>
<tr class="odd">
<td></td>
<td>1.3.2 Disponibilidade de serviços específicos</td>
<td>40</td>
<td>46</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td></td>
<td>1.3.3 Tecnologias e procedimentos</td>
<td>36</td>
<td>36</td>
<td>Autorreferido</td>
</tr>
<tr class="odd">
<td></td>
<td>1.4.1 Pontuações de densidade</td>
<td>3</td>
<td>3</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td></td>
<td><strong>Subtotal da dimensão 1</strong></td>
<td><strong>166</strong></td>
<td><strong>428</strong></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>2. Prontidão geral</strong></td>
<td>2.1.1 Comodidades básicas</td>
<td>6</td>
<td>9</td>
<td>5 autorreferidos, 1 com observação</td>
</tr>
<tr class="even">
<td></td>
<td>2.2.1 Equipamento básico</td>
<td>14</td>
<td>14</td>
<td>Observação</td>
</tr>
<tr class="odd">
<td></td>
<td>2.5.1 Precauções-padrão (parcial)</td>
<td>4</td>
<td>15</td>
<td>2 autorreferidos, 2 com observação</td>
</tr>
<tr class="even">
<td></td>
<td>2.7.1 Sistemas de referência</td>
<td>6</td>
<td>6</td>
<td>3 autorreferidos, 3 com observação</td>
</tr>
<tr class="odd">
<td></td>
<td><strong>Subtotal da dimensão 2</strong></td>
<td><strong>30</strong></td>
<td><strong>225</strong></td>
<td></td>
</tr>
<tr class="even">
<td><strong>3. Disponibilidade específica</strong></td>
<td>3.1.1 Planeamento familiar</td>
<td>15</td>
<td>15</td>
<td>Autorreferido</td>
</tr>
<tr class="odd">
<td></td>
<td>3.1.2 Cuidados pré-natais</td>
<td>13</td>
<td>16</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td></td>
<td>3.1.3 Parto e cuidados obstétricos básicos</td>
<td>29</td>
<td>29</td>
<td>Autorreferido</td>
</tr>
<tr class="odd">
<td></td>
<td>3.1.4 Cuidados obstétricos completos</td>
<td>4</td>
<td>4</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td></td>
<td>3.1.6 Cuidados pós-parto</td>
<td>11</td>
<td>11</td>
<td>Autorreferido</td>
</tr>
<tr class="odd">
<td></td>
<td>3.1.8 Saúde da criança</td>
<td>13</td>
<td>13</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td></td>
<td>3.2.1 Vacinação</td>
<td>25</td>
<td>25</td>
<td>Autorreferido</td>
</tr>
<tr class="odd">
<td></td>
<td>3.2.2 Malária</td>
<td>8</td>
<td>8</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td></td>
<td>3.2.3 Tuberculose</td>
<td>9</td>
<td>9</td>
<td>Autorreferido</td>
</tr>
<tr class="odd">
<td></td>
<td>3.2.4 Testagem do VIH</td>
<td>4</td>
<td>4</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td></td>
<td>3.2.5 Tratamento antirretroviral</td>
<td>7</td>
<td>7</td>
<td>Autorreferido</td>
</tr>
<tr class="odd">
<td></td>
<td>3.5.1 Urgência</td>
<td>10</td>
<td>10</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td></td>
<td><strong>Subtotal da dimensão 3</strong></td>
<td><strong>148</strong></td>
<td><strong>1 484</strong></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>4. Gestão e finanças</strong></td>
<td>4.2.1 Orçamento (âncora)</td>
<td>1</td>
<td>11</td>
<td>Autorreferido</td>
</tr>
<tr class="even">
<td><strong>TOTAL</strong></td>
<td></td>
<td><strong>345 indicadores</strong></td>
<td><strong>2 604</strong></td>
<td><strong>≈ 94% autorreferidos</strong></td>
</tr>
</tbody>
</table>
<p><strong>Dezanove subáreas ficam completas</strong> — todos os seus indicadores passam a ser calculáveis, sem lacunas: camas, densidade de infraestrutura, pontuações de densidade, ambulatório e internamento, tecnologias e procedimentos, outros indicadores de pessoal, planeamento familiar, parto e cuidados obstétricos básicos e completos, cuidados pós-parto, saúde da criança, vacinação, malária, tuberculose, testagem do VIH, tratamento antirretroviral, urgência, equipamento básico e sistemas de referência.</p>
</section>
<section id="o-que-esta-versão-produz-e-o-que-deixa-para-depois" class="level2" style="border-left:6px solid #6c3483;background:#f4ecf7;padding:14px 18px;border-radius:6px;">
<h2 class="anchored" data-anchor-id="o-que-esta-versão-produz-e-o-que-deixa-para-depois">O que esta versão produz, e o que deixa para depois</h2>
<p><strong>345 indicadores do HHFA</strong>, dos 2 604 do inventário. O número isolado diz menos do que a sua composição: <strong>dezanove subáreas ficam completas</strong>, e são precisamente as de disponibilidade — aquilo para que a Ficha do Mapa Sanitário foi desenhada. O instrumento passa a produzir, em linguagem internacionalmente comparável, exatamente o que já se propunha medir.</p>
<p><strong>Mais de nove em cada dez rendem em modo autorreferido.</strong> Só a Secção 9 exige observação por inteiro, e pode ser aplicada apenas nas unidades visitadas sem que o formulário deixe de funcionar nas restantes.</p>
<p><strong>O ganho maior, porém, não está no número de indicadores.</strong> Está na formulação. Uma pergunta escrita por extenso, com a unidade, o período e o ponto de referência dentro dela, produz a mesma resposta independentemente de quem a faz — e é isso que torna comparáveis duas unidades, duas províncias e duas edições do Mapa Sanitário. Vários quesitos deste formulário não acrescentam nenhum indicador novo e mantêm-se aqui por essa razão apenas: a distância à unidade de referência, o estado de conservação, a frota, as especialidades, os serviços gerais. São <strong>[MS]</strong>, são contributo próprio do Mapa, e ganham em precisão sem mudar de propósito.</p>
<p><strong>Três quesitos ficam deliberadamente por resolver</strong>, e convém dizê-lo: a farmácia (7.2.10), a esterilização e a distribuição de albendazol mantêm-se como perguntas de existência. Nos três casos o indicador do HHFA correspondente depende de verificação física — medicamento dentro da validade, equipamento a funcionar, produto observado — e não há forma honesta de o produzir em modo autorreferido. Mantêm-se como estão até que a decisão sobre a observação seja tomada.</p>
<p><strong>O que fica para a fase seguinte</strong> é a dimensão da prontidão: normas disponíveis, pessoal formado, medicamentos e meios de diagnóstico verificados. São os incrementos de Tipo 3 e de Tipo 4 do documento 4, e todos exigem inquiridor com observação. Ficam de fora desta versão não por serem menos importantes — são, em muitos casos, mais —, mas porque a sua adoção depende de uma decisão sobre o modo de recolha que ainda não está tomada.</p>
</section>



</main> <!-- /main -->
<script>
(function () {
  var html = document.documentElement;
  var pt = (html.lang || "pt").toLowerCase().indexOf("pt") === 0;
  var L = pt
    ? { font: "Tipo de letra", size: "Tamanho", sans: "Sans", serif: "Serifa", legible: "Legível",
        smaller: "Diminuir letra", larger: "Aumentar letra", reset: "Tamanho normal",
        lang: "Idioma", other: "English", otherTitle: "Read this page in English", tools: "Leitura" }
    : { font: "Typeface", size: "Size", sans: "Sans", serif: "Serif", legible: "Legible",
        smaller: "Smaller text", larger: "Larger text", reset: "Normal size",
        lang: "Language", other: "Português", otherTitle: "Ler esta página em português", tools: "Reading" };

  function get(k) { try { return localStorage.getItem(k); } catch (e) { return null; } }
  function set(k, v) { try { localStorage.setItem(k, v); } catch (e) {} }

  function el(tag, attrs, text) {
    var n = document.createElement(tag);
    for (var a in attrs) n.setAttribute(a, attrs[a]);
    if (text) n.textContent = text;
    return n;
  }

  // Counterpart page in the other language: same file name in the sibling folder.
  function otherLangUrl() {
    var from = pt ? "/pt/" : "/en/", to = pt ? "/en/" : "/pt/";
    var p = location.pathname, i = p.lastIndexOf(from);
    if (i < 0) return null;
    return p.slice(0, i) + to + p.slice(i + from.length) + location.hash;
  }

  function build() {
    var box = el("div", { "class": "reader-tools", role: "group", "aria-label": L.tools });

    box.appendChild(el("span", { "class": "reader-label" }, L.font));
    var fonts = el("div", { "class": "reader-group" });
    var cur = get("reader-font") || "sans";
    [["sans", L.sans], ["serif", L.serif], ["legible", L.legible]].forEach(function (f) {
      var b = el("button", { type: "button", "aria-pressed": String(cur === f[0]) }, f[1]);
      b.addEventListener("click", function () {
        if (f[0] === "sans") html.removeAttribute("data-font"); else html.setAttribute("data-font", f[0]);
        set("reader-font", f[0]);
        fonts.querySelectorAll("button").forEach(function (x) {
          x.setAttribute("aria-pressed", String(x === b));
        });
      });
      fonts.appendChild(b);
    });
    box.appendChild(fonts);

    box.appendChild(el("span", { "class": "reader-label" }, L.size));
    var sizes = el("div", { "class": "reader-group" });
    function size() { return parseInt(html.getAttribute("data-fontsize") || "0", 10); }
    function applySize(n) {
      n = Math.max(-1, Math.min(2, n));
      if (n === 0) html.removeAttribute("data-fontsize"); else html.setAttribute("data-fontsize", String(n));
      set("reader-fontsize", String(n));
    }
    [["A−", L.smaller, -1], ["A", L.reset, 0], ["A+", L.larger, 1]].forEach(function (s) {
      var b = el("button", { type: "button", title: s[1], "aria-label": s[1] }, s[0]);
      b.addEventListener("click", function () { applySize(s[2] === 0 ? 0 : size() + s[2]); });
      sizes.appendChild(b);
    });
    box.appendChild(sizes);

    var url = otherLangUrl();
    if (url) {
      box.appendChild(el("span", { "class": "reader-label" }, L.lang));
      box.appendChild(el("a", { "class": "reader-lang", href: url, title: L.otherTitle, hreflang: pt ? "en" : "pt" }, L.other));
    }
    return box;
  }

  function mount() {
    var host = document.querySelector("#quarto-sidebar .sidebar-menu-container");
    if (!host) return;
    host.parentNode.insertBefore(build(), host);
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", mount);
  else mount();
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-decisoes.html" class="pagination-link" aria-label="Decisões que teremos que tomar para avançarmos juntos">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Decisões que teremos que tomar para avançarmos juntos</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./anexo-1.html" class="pagination-link" aria-label="Anexo 1 — Proposta de questionário">
        <span class="nav-page-text">Anexo 1 — Proposta de questionário</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/filustrias/mapa_sanitario_hhfa/blob/main/pt/06-ficha-revista.qmd" class="toc-action"><i class="bi bi-github"></i>Ver o código fonte</a></li><li><a href="https://github.com/filustrias/mapa_sanitario_hhfa/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>